### ISSUE TITLE
Git | Create Pull request / issue request templates

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1011]
> https://github.com/blog/2111-issue-and-pull-request-templates
https://github.com/Fourdee/DietPi/pull/1008#issuecomment-307788094

**Comment by Fourdee** [comment]
https://github.com/Fourdee/DietPi/blob/testing/PULL_REQUEST_TEMPLATE.md

**Comment by noplanman** [comment]
If I may leave a suggestion, it makes sense to make the text in the template an HTML comment, so that the text itself wouldn't get added to the PR comment if somebody leaves it there.

Example here: https://github.com/php-telegram-bot/core/tree/master/.github

(Also, you can move it to a `.github` folder to keep it stored nicely separately)

P.S. Awesome how actively you implement new ideas! 🎉

**Comment by Fourdee** [comment]
@noplanman 

> HTML comment, so that the text itself wouldn't get added to the PR comment if somebody leaves it there.

Nice 👍 

I'll be borrowing your ```.md``` templates 😉

**Comment by noplanman** [comment]
> I'll be borrowing your .md templates 😉

The beauty of open source 😇

(DietPi FTW by the way! Loving the simplicity and lightweightness 😍)

**Comment by Fourdee** [comment]
https://github.com/Fourdee/DietPi/blob/testing/ISSUE_TEMPLATE.md

**Comment by Fourdee** [comment]
@noplanman 

Many thanks again for your help on this 👍 

I'll mark this as completed (will add to them as needed in future), should start seeing this active once v152 is released (merged to master)?

**Comment by Fourdee** [comment]
Lets put them in the .github folder

**Comment by Fourdee** [comment]
https://github.com/Fourdee/DietPi/tree/testing/.github
