### ISSUE TITLE
dietpi-software fails when dpkg is on interrupted state

### ISSUE THREAD

**Issue by blamoo** [MichaIng/DietPi#106]
`dietpi-software` marks software as installed, but won't install anything unless you run `dpkg --configure -a`
Even with this error, it still says the software is installed on `dietpi-software` and `dietpi-uninstall`.

**Comment by Fourdee** [comment]
Hi Blamoo,.

Sounds like a previous apt-get install failed, this would cause dpkg to prevent further installations, until the issue is resolved.

I'll need to check your settings, can you send me a bug report please:
dietpi-bugreport

Also, can you remember which software you installed, prior to the error being displayed?

Notes to self:
- Check dpkg for failed state before dietpi-software runs installations, or, before each apt-get?
- Check /DietPi/dietpi/.installed against dpkg -l  to confirm installed?

**Comment by blamoo** [comment]
k, I can't do it right now but I'll try to reproduce it tonight.

**Comment by Fourdee** [comment]
I've added some error checking to v100 to help with debugging. This will inform the user and provide the apt error code if this re-occurs.
