### ISSUE TITLE
DietPi-Software Removal | JRiver

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1080]
> http://dietpi.com/phpbb/viewtopic.php?f=11&t=2058&p=8002#p8002

Same issues as per implementation I experienced. Unknown cause / solution:
https://github.com/Fourdee/DietPi/issues/988

**Comment by Fourdee** [comment]
🈴 Confirmed with 2x RPi 3's. Unknown cause at the moment, further testing required.

Nudging to v155 to allow release of v154.

**Comment by Fourdee** [comment]
I dont believe this to be a DietPi issue, various clean identical installs, some will work, others wont. Putting this down to a possible bug in Jriver.

**Comment by Fourdee** [comment]
Note to self, 2 install count on survey. Flag for removal?

**Comment by Fourdee** [comment]
Marking as flagged for removal due to low install count.

**Comment by MichaIng** [comment]
@Fourdee 
Makes sense with our install method. The used repo points to wheezy: http://dist.jriver.com/latest/mediacenter/mediacenter22native.list
- <s>Could be tested it Jessie, Stretch dist is available as well, but I doubt, since the below:</s>
- http://dist.jriver.com/stable/mediacenter/mediacenter24.list Jessie repo available.
- Stretch repo as Beta: http://dist.jriver.com/beta/mediacenter/mediacenter24.list

There are deb packages to be used with Jessie: https://yabb.jriver.com/interact/index.php/topic,115942.0.html?PHPSESSID=vmvle9q70m4vr5it77qda9o2q4

We could test to use them with Stretch, but there is no official Stretch release.

**Comment by Fourdee** [comment]
@MichaIng 

> We could test to use them with Stretch, but there is no official Stretch release.

Yep, the software is somewhat buggy at its core, and, with the low install count (2 currently: https://dietpi.com/survey/), not worth our time implementing and providing support for, I believe.

**Comment by Fourdee** [comment]
Done.
