### ISSUE TITLE
Dietpi hangs at boot after first-run upgrade | XU4 

### ISSUE THREAD

**Issue by joaofl** [MichaIng/DietPi#1105]
### - https://github.com/Fourdee/DietPi/issues/1105#issuecomment-321542109

---

After flashing the image DietPi_v151_OdroidXU4-armv7-(Jessie), during first time boot, the Dietpi updates itself from 151 to 154 and reboots. Next, it asks for softwares to be installed, and without selecting any, I click Go, what leads to an "apt upgrade".

The first upgrade takes some 20 min, and after it, it reboots automatically, but hangs during boot as on the picture below.

If I unplug it, and plug again, it does not boot anymore.
Happened 3 times in a row, with different SD cards, and with/without external USB drives plugged into the USB.

** the same does not happen with the image containing the kernel 4.9

![p_20170809_044419_1](https://user-images.githubusercontent.com/8092452/29105149-d95d2f62-7cc2-11e7-9899-76e2786d80e9.jpg)

**Comment by Fourdee** [comment]
@joaofl 

Thanks for the report 👍  I'll take a look.

**Comment by Fourdee** [comment]
- 🈴 initramfs: No drives/partitions listed in ```blkid```
Kernel date 7th Aug
- 🈺 Changes to the ```/boot/boot.ini``` boot up code **required**, due to new support for eMMC 5.1 AFAIK
https://github.com/Fourdee/DietPi/commit/6a7bed1e87bc96d9bdc2e459f03e35676205bcd5#diff-8c4a8f176043d56dac80fbbdf318e3f7

---

### - 🈯️ XU4 image updated: http://dietpi.com/downloads/images/DietPi_OdroidXU4-armv7-(Jessie).7z

---

### Existing installations, if you experience failure to boot, after the kernel upgrade (```apt-get upgrade```):
- You will need to replace ```/boot/boot.ini``` with the following file: https://github.com/Fourdee/DietPi/blob/testing/boot_xu4.ini
- System will now boot

**Comment by Fourdee** [comment]
@joaofl 

Image updated: https://github.com/Fourdee/DietPi/issues/1105#issuecomment-321542109

Thanks for reporting this 👍

**Comment by Fourdee** [comment]
Completed, however existing installations will need to manually update their ```boot.ini``` after kernel upgrade:
https://github.com/Fourdee/DietPi/issues/1105#issuecomment-321542109

**Comment by KevinHaendel** [comment]
### I tried the following:
First, I used this image here: http://dietpi.com/downloads/images/DietPi_OdroidXU4-armv7-(Jessie).7z , and then I replaced the boot.ini file **before** and **after** "apt-get upgrade". But in both cases it is still not working.


### I used a workaround until this is working again:
I typed "apt-mark hold uboot" to prevent uboot from upgrading, this solves my problem, but I hope I can update it again in the future.

**Comment by joaofl** [comment]
At some point the new image provided by @Fourdee worked out. But yesterday it seems that upgrading the uboot caused some issue (again). Again it hanged during boot. Not even the hearbeat LED blinks.

Not sure what to do.
