### ISSUE TITLE
kodi don't start

### ISSUE THREAD

**Issue by Nibeck1309** [MichaIng/DietPi#111]
Hello,

Reference CODE: b827eb45e355-0

I'm using dietpi-sofware for installing kodi.

When i want to launch it, i have this error message :+1: 

/DietPi/dietpi/misc/rpi_kodi_noblackscreen_run: ligne 25: kodi-standalone : commande introuvable

Thanks for your help

**Comment by Fourdee** [comment]
Hi Nibeck1309,

Thanks for the report.

It appears you are using additional/modified apt sources that are causing your issue. 
Your system is installing kodi: 5:14.2+repack-dmo1b1 , instead of 2:14.2-1wheezy from the official Raspbian Jessie Repo.

5:14.2+repack-dmo1b1 is missing the command kodi-standalone.

Please check your custom apt sources, disabling any that are overriding the Kodi package from the Raspbian repo. Then reinstall Kodi.

**Comment by Fourdee** [comment]
Update: 
It appears Kodi:5:14.2+repack-dmo1b1 is being installed from the debian-multimedia repo (which is added during FFmpeg installation). 

I'll look into this further and get back to you.

**Comment by Nibeck1309** [comment]
OK thanks for report.

**Comment by Fourdee** [comment]
Ok this will be fixed for v101. After installing FFMPEG, the deb.multimedia repo will be removed.

You will need to manually re-install Kodi on your system, please do the following:
- use dietpi-uninstall and select Kodi for removal
- run below in terminal to remove deb.multimedia repo
  
  > sed -i '/www.deb-multimedia.org jessie main non-free/d' /etc/apt/sources.list
  > /DietPi/dietpi/dietpi-apt-get_update 2
- Now you can run dietpi-software and select Kodi for installation.

**Comment by Nibeck1309** [comment]
Hello,

Thanks for answer.

use dietpi-uninstall and select Kodi for removal
run below in terminal to remove deb.multimedia repo

sed -i '/www.deb-multimedia.org jessie main non-free/d' /etc/apt/sources.list
/DietPi/dietpi/dietpi-apt-get_update 2
Now you can run dietpi-software and select Kodi for installation

That works perfectly.

I'm install kodi and it work

Thanks
