### ISSUE TITLE
Emby Server fails to install, due to missing package deps, not available in Debian repos.

### ISSUE THREAD

**Issue by damien92220** [MichaIng/DietPi#1150]
Hi all,
error when i want install Emby Server

#### Required Information:
- DietPi Version: 155
- SBC Device: Asus Tinker Board
- Power supply used: 5v 3A

#### Additional Information (if applicable):
- Emby Server
- Can this issue be replicated on a fresh installation of DietPi? Yes

#### Actual behaviour:
Apt-get has failed:
- Apt string = emby-server embymagick
- Error code = 100
- Software Title = Emby Server: web interface media streaming server

#### Steps to reproduce:
With new clean install

#### Did you submit a ```dietpi-bugreport```?
dietpi-software_apt.log = E: Unable to correct problems, you have held broken packages.

**Comment by Fourdee** [comment]
@damien92220 

Thanks for the report 👍 

We'll investigate.

**Comment by Fourdee** [comment]
```
root@DietPi:~# apt-get install -f
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@DietPi:~# apt-get install emby-server embymagick
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 embymagick : Depends: libpng12-0 (>= 1.2.13-4) but it is not installable
              Depends: libwebp5 but it is not installable

```

---

Attempt with Emby debian 8 repo:
```
root@DietPi:~# apt-get install emby-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 emby-server : Depends: libembysqlite3-0 but it is not installable
               Depends: embymagick but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by Fourdee** [comment]
Ok, lets pull in the missing packages for ARMv7/v8 from various sources, prior to install.
A little messy/hacky, but will resolve the current install issue, at least for now.
Tests:
- 🈯️ ARMv8 Stretch
- 🈯️ ARMv7 Jessie
- 🈯️ ARMv7 Stretch
![image](https://user-images.githubusercontent.com/7077026/32146379-743c7ba0-bcce-11e7-84de-b0c1a39c1064.png)

**Comment by Fourdee** [comment]
Completed

**Comment by DncrJim** [comment]
As I mentioned in another post, Emby does not behave very well with mono 5.4.x, and one of the first requests by the developers when anything goes wrong is to downgrade to mono 4.8.1 (last supported), Downgrading already installed mono/emby tends to break things, at least for me. Unfortunately, even if I lock mono at that release, using the dietpi software installer tries to upgrade mono, and then breaks it mono, so I can't use dietpi-software to install it.. 

My lack of skill is going to show here, but can someone give me a quick lesson in how to manually pull the packages and where to find them? I am getting 
```
emby-server : Depends: libembysqlite3-0 but it is not installable
              Depends: embymagick but it is not installable
```
exactly as discussed above.

I've also read through the instructions at this link and one other thread whose link eludes me right now: 
https://emby.media/community/index.php?/topic/19415-debian/page-11

What I'm looking for is a way to add these dependencies myself between installing mono 4.8.1 and emby-server so that I can get a known 'good' configuration with the 'correct' version of mono to submit to the Emby github for troubleshooting.

the following produces a 404 error:  (yes, I know it's also the wrong one, but it was in one of the solutions)
wget http://ftp.de.debian.org/debian/pool/main/libj/libjpeg8/libjpeg8_8d1-2_arm64.deb
and this one didn't change anything:
wget ftp.de.debian.org/debian/pool/main/libj/libjpeg8/libjpeg-progs_8d-1+deb7u1_armhf.deb
dpkg -i libjpeg-progs_8d-1+deb7u1_armhf.deb.1

Yes, I have been fully versed by a number of people that I should be using the current version whenever possible and why, but it that doesn't solve my current problem.

See Also: https://github.com/Fourdee/DietPi/issues/619

Thanks in advance...

**Comment by ryaneneal** [comment]
I was able to install it on Stretch with this, as su:
curl -sSL https://get.docker.com/ | sh
docker run -it --rm -v /usr/local/bin:/target emby/embyserver:armv7 instl
