### ISSUE TITLE
DietPi-Software | DietPi-Cam - Motion detection blank.

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#120]
> http://fuzon.co.uk/phpbb/posting.php?mode=quote&f=11&p=854#pr854
> 
> Motion detection starts up, it shows up in the log file and the motion service is listed as running on the system, but the weird thing is that motion.php page is utterly blank and no recording is being triggered.
> I'm really just stumbling around in the dark here. I've been working my way through http://elinux.org/RPi-Cam-Web-Interface but it's quite dense reading and doesn't really have a quickstart section, explaining the basics.
> i'd have a proper go at reading the forum thread at https://www.raspberrypi.org/forums/view ... 43&t=63276 but it's 121 pages long!

**Comment by Fourdee** [comment]
Jessie: motion.php blank.
Wheezy: ..................

Note to self:
- Test wheezy motion.php.
- Update DietPi-Cam to latest RPi-Camweb

**Comment by Fourdee** [comment]
Confirmed working on Wheezy. Appears to be a bug in RPi-cam-web-interface on Jessie.

Will attempt to update DietPi-Cam version to latest RPi-cam-web-interface version for a resolution.

**Comment by Fourdee** [comment]
For DietPi v103:
I've updated DietPiCam to match the current RPi cam control (v6.0.19), but, still having a blank page on jessie for motion.

Turns out this is a known issue for Jessie: https://github.com/silvanmelchior/RPi_Cam_Web_Interface/issues/214#issuecomment-152719047
Looks like the cause is with the motion package installation. No doubt the libraries are different to Wheezy.

**Comment by R1CH-T** [comment]
Hey Dan,

Last week, I upgraded to v117 and had another go at setting up DietPiCam (on Jessie), but I'm still experiencing the "blank motion detection page" problem.

I am also still having some problems getting motion detection working at all. (Although I got it to work in a limited fashion in the Wheezy version).
This may well be due to my own ignorance and/or inexperience, but I plan to slowly plug away at this.

I notice that there have been some bug reports and minor tweaks to this module recently and thought that maybe, if you get the chance this week: Could you pull in the latest version and add it to a testing branch, so that I can test it this weekend and maybe have a go at trying to get motion detection working for me?

Sorry to bother you, but I'd like to see this working properly on the mainline DietPi.
If you don't have the time, I completely understand.

Thanks,
Rich.

**Comment by Fourdee** [comment]
@R1CH-T 

Yep no worries. I need to update and test the installation anyway, hopefully the motion detection has been fixed by the RPiwebcam devs.

I'll mark this for v119 (https://github.com/Fourdee/DietPi/milestones/v119). Will take a look once v118 (https://github.com/Fourdee/DietPi/milestones/v118) is completed and released.

**Comment by Fourdee** [comment]
Updated to 6.1.6: https://github.com/Fourdee/RPi_Cam_Web_Interface/tree/6.1.6

Internal motion detection working well:
![image](https://cloud.githubusercontent.com/assets/7077026/15359991/b479c8a6-1d03-11e6-9782-9f7f2ab152f5.png)

External motion = error when loading motion options:

```
(mod_fastcgi.c.2695) FastCGI-stderr: PHP message: PHP Warning:  file_get_contents(http://127.0.0.1:6642/0/config/list): failed to open stream: Connection refused in /var/www/dietpicam/motion.php on line 25
```

I'll set config to default to internal motion: https://github.com/Fourdee/RPi_Cam_Web_Interface/commit/6ca0d16ea7d43cfc501372b18280d50271e273d2

**Comment by Fourdee** [comment]
I've also managed to remove 2 conf files from DietPi-Ramdisk. Should free up some memory.
https://github.com/Fourdee/DietPi/commit/a1e5d704e25133f81c2ea85b3775439d8a936e5b

**Comment by R1CH-T** [comment]
Hi.
I just changed to the "Testing" branch, updated to v119 and installed DietPiCam.
I can confirm that internal motion detection now works flawlessly. Fantastic work!
I may need to play around with it and adjust the sensitivity or maybe create a mask, but apart from that, it's working great.
Thanks for your efforts, Dan.
:+1:
