### ISSUE TITLE
DietPi-Software | Emby requires mono 4.x?

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1322]
> http://dietpi.com/phpbb/viewtopic.php?f=11&t=2599&p=10056#p10054

**Comment by Fourdee** [comment]
Notes, Emby:
- ARM = http://download.opensuse.org/repositories/home:/emby/xUbuntu_14.04/
- x86_64 = http://download.opensuse.org/repositories/home:/emby/Debian_VERSION

Notes Mono:
- ```deb http://download.mono-project.com/repo/debian $DISTRO_NAME main```

#### ToDo:
- Check installed mono version currently
- Test if ```deb http://download.mono-project.com/repo/debian wheezy/snapshots/4.8.1.0 main``` works on all distros
-- If so, consider downgrading Mono for Emby installs, however, this may break other software installed that pre-req's Mono.

**Comment by LexiconCode** [comment]
I'm willing to test this

**Comment by MichaIng** [comment]
https://emby.media/community/index.php?/topic/52758-odroid-xu4-frequent-crashes/

In the last post they also say, that for x64 builds they moved to .net core and that's also the plan for arm. There should be kept an eye on this development and so far respected for our native and vm images.

**Comment by Fourdee** [comment]
As mono is a shared library, installed for many programs in dietpi-software, changing the version for one specific item, may break other software installations that use mono.

As such, we'll stick with the mono version as provided by its repo.

I'll mark this as closed.

**Comment by bokiroki** [comment]
@Fourdee i installed emby to see if it's better than plex (plex hate subtitles :unamused: ) and it's crashing also i guess because of mono..
So i will install fresh dietpi.. Whats the easiest way to install emby with older mono? they said latest version they suport is 4.8.1. from forum post from December 14 2017. i will install beside emby (radarr, sonarr, jackett, deluge)
On this forum thread they have .net core version for arm devices (i'm on raspberry pi 3). with this .net core we don't need mono, or?
https://emby.media/community/index.php?/topic/50012-emby-server-for-net-core/

Edit: this was posted yesterday, he is using dietpi, and has the same problem as me.. he mentioned mono version 5.1, but dev did't said anything about mono.. so i guess mono is not the problem..
https://emby.media/community/index.php?/topic/58103-raspberry-pi-3-crashes-not-transcoding-performance-issue/

Edit 2: on forum they said to me to uninstall emby trough dietpi-software, and install it with website instruction https://emby.media/linux-server.html
i deleted emby and ffmpeg, and installed deb file and everything works now well..didnt changed anything else, mono is the same version 5.10
