### ISSUE TITLE
DietPi-Software | MySQL/MariaDB: mysqld fails after update to v160

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1324]
Seems to be related to core environment creation:
`[ERROR] mysqld: Can't create/write to file '/var/lib/mysql/aria_log_control' (Errcode: 13 "Permission denied")`

`chmod +x /mnt/dietpi_userdata` solved the problem for me. We should verify that the folder was executable before, so we do not change something after all, but I guess, as this seems to be necessary for mysqld to access it's mysql subfolder.

**Comment by MichaIng** [comment]
Jep `dietpi_userdata`, it is made executable during dietpi-software execution: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software#L8599

**Comment by Fourdee** [comment]
@MichaIng 
Thanks 👍 

I'll check

**Comment by Fourdee** [comment]
@MichaIng 

https://github.com/Fourdee/DietPi/commit/39fb3fdc29da46f93c09ce03522a4134ccebe8f7 should do it (currently runs during dietpi-update patch), but if we can verify with another test, i'd be grateful.

I've not been able to replicate it since with testing https://github.com/Fourdee/DietPi/pull/1319#pullrequestreview-84664248, although thats mariaDB default install?

**Comment by MichaIng** [comment]
@Fourdee 
Jep looks good, will test later, have to rewind first my VM to v159.

**Comment by MichaIng** [comment]
Works like a charm, tested on VM Stretch with LAAP stack. 👍
