### ISSUE TITLE
[dupe] Dietpi-Software | Mosquitto repo package has broken dependencies

### ISSUE THREAD

**Issue by borpin** [MichaIng/DietPi#1381]
#### Required Information:
- DietPi Version | New RaspberryPi Stretch image

#### Additional Information (if applicable):
- Mosquitto
- Can this issue be replicated on a fresh installation of DietPi? Yes

#### Expected behaviour:
Mosquitto installed by dietpi-software.

#### Actual behaviour:
Install fails
````
The following packages have unmet dependencies:
 mosquitto : Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
             Depends: libwebsockets3 (>= 1.2) but it is not installable
````
#### Steps to reproduce:
Attempt install

#### Did you submit a ```dietpi-bugreport```?
No

#### Extra details:
Removing the mosquitto.org repo enabled mosquitto to be installed.
Debian repos are at 1.4.10 and mosquitto repo is at 1.4.14.
There is a fix here https://www.eclipse.org/forums/index.php?t=msg&th=1089302&goto=1773991&

**Comment by Fourdee** [comment]
@borpin 

Thanks for the report 👍 

This is resolved for v6.0, please see link below for fix now:
https://github.com/Fourdee/DietPi/issues/1306#issuecomment-352167350

EDIT: further issues may still exist, due to mosq repo, please read ticket above.

I'll mark as closed (dupe), please reopen if required.
