### ISSUE TITLE
RPi Cam Control / MotionEye Problem

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#1564]
Hello, i Installed both softwares RPi Cam Control - RPi Camera / Web Interface Surveillance
- MotionEye - Camera / Web Interface Surveillance on latest dietpi Stretch in a RaspberryPi3 but upon first boot after installation the dietpiOS keeps rebooting by it self,anyone know whats wrong?

**Comment by Fourdee** [comment]
@symbios24 

Hi,

Thanks for the report 👍 

- 🈯️ RPi cam is fixed in v6.3: https://github.com/Fourdee/DietPi/issues/1512

--- 

Motion notes:
- 🈴 Missing ```build-essential```, fails to build. ```zlib1g-dev``` is installed
```
 The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
```

🈯️ fixed for v6.3 https://github.com/Fourdee/DietPi/commit/264062494de1e0667f107a26910452d5a1a83acf

Once ```build-essential``` is installed, installs fine and unable to replicate automatic reboot.

I did experience reboots previously, due to the sunny connector being 50% disconnected. Please ensure the sunny connector and ribbon cable is fully connected.
![image](https://user-images.githubusercontent.com/7077026/36739847-dde6cede-1bd8-11e8-9039-080a9e085fb1.png)


I'll mark this as closed, unable to replicate auto reboot. If problems persist after sunny connector re-seat and v6.3, please reopen.

**Comment by symbios24** [comment]
But 6.3 is not released yet..

**Comment by Fourdee** [comment]
@symbios24 

> But 6.3 is not released yet..

Wont be long, eta mid-end next week.
