### ISSUE TITLE
ntp behind http/tcp proxy

### ISSUE THREAD

**Issue by TheRinger** [MichaIng/DietPi#1591]
NTP service is using UDP protocol to sync the time. So HTTP/TCP proxy may not work for it.
An alternative for this is htpdate package available in debian/ubuntu repos, it would allow bootstrapping installs behind http/tcp proxies.

**Comment by MichaIng** [comment]
@TheRinger 
Thanks for your request.

Actually we plan to fully switch to systemd-timesyncd, but as far as I could find out, the issue is the same there.

If considering an alternative to sync through proxies, I would take a look at tlsdate: https://github.com/ioerror/tlsdate
Secure TLS connection at least. What I don't like about both projects, is that they are not actively developed for years... But use case is reasonable, although I would expect a local ntp server behind a http proxy always :wink:.

**Comment by TheRinger** [comment]
I'll do some reading about systemd-timesyncd. Comcast's public internet gateway (xfinitywifi) in the United States blocks udp so I ended up using htpdate in order to sync.

**Comment by Fourdee** [comment]
> Actually we plan to fully switch to systemd-timesyncd

I'll mark as closed.

> , but as far as I could find out, the issue is the same there.

However, if this is still an issue for any user, please reopen.
