### ISSUE TITLE
Weird characters when typing special characters

### ISSUE THREAD

**Issue by grenzor** [MichaIng/DietPi#1617]
When I try to type some special character it never types it but instead types some other random character. For example when `/` key is typed it types `-` and for other special character keys it types other stuff as shown in screenshot below. Makes it almost impossible to use terminal commands. Letters and numbers type out just fine.

Screenshot: https://i.imgur.com/Zl5uJGE.png

Using the latest DietPi Virtualbox image on Windows host.

**Comment by MichaIng** [comment]
@grenzor 
Thanks for your report.

Jep, that was a mistake by me, leaving german keyboard layout which does not get overwritten by dietpi.txt default "gb" (UK layout) during 1st run setup. To fix you should be able to just switch keyboard layout from within `dietpi-config`.

This issue is fixed with the newest VirtualBox image, uploaded yesterday: http://dietpi.com/downloads/images/

**Comment by grenzor** [comment]
Thanks, changed keyboard layout and all is fine now.
