### ISSUE TITLE
Dietpi Auto-Config over UI

### ISSUE THREAD

**Issue by parthgujar** [MichaIng/DietPi#1619]
This is more like a enhancement/feature request. I think it would help beginners all over the world who want to get started with rpi/clones.
The two options on top of my mind are 
1. Using MQTT publisher-subscriber model, we could possibly let devices in local network discover a fresh install and configure the O.S (dietpi-software, dietpi-software) with a Android/iOS app over MQTT.
2. Create a http web page after fresh install that gives config options and even like a guided tour.  

I personally do not have the technical knowledge to build them myself, so lets collaborate? Someone else could take over too. I've found dietpi extremely useful, the convenience with install and config is nothing short of a boon.
Excuse me if this is not the right place to post. Does this belong to the forum?

Creating a bug report/issue:

#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```?
- SBC Device (EG: RPi 3)?
- Power supply used (EG: 5v 1A RAVpower)?
- SD card used (EG: Sandisk ultra)?
- Distro (EG: Jessie) | ```uname -a```?

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

**Comment by Fourdee** [comment]
@parthgujar 

> Create a http web page after fresh install that gives config options and even like a guided tour.

We had a look at creating a fully featured GUI/web front-end for DietPi in the past, which could replace the whiptail system. However, its a huge undertaking and would require collaboration with web coder/s (which we lack) to pull it off.

In short, its a feature I'd love to have in DietPi, however, due to the time involved to pull it off, it would most certainly impact our current support/fixes/enhancements for end users.

I'll mark this as closed for now, however, please feel free to continue discussions.
