### ISSUE TITLE
dietpi-letsencrypt

### ISSUE THREAD

**Issue by MrSuttonmann** [MichaIng/DietPi#162]
Hi,

I'm trying to run dietpi-letsencrypt, but it gives me the following error:

```
Error: Lets encrypt scripts not installed ( /etc/letsencrypt_scripts ).
Please install LetsEncrypt with DietPi-Software before running this program.
```

If I then run DietPi-Software, I can't find LetsEncrypt in the software listing at all. What gives?

Also in dietpi-banner, you've got a typo on line 80.

**Comment by Fourdee** [comment]
@jameshyde 
Lets encrypt has been disabled for the DietPi RPi Wheezy image as Letsencrypt-auto script fails to install on RPi Wheezy. see: http://fuzon.co.uk/phpbb/viewtopic.php?f=11&t=261&p=1094#p1094

Its been a few weeks since I last tested Letsencrypt-auto on Wheezy, so if you want to try it, you will need to add the following line to the dietpi-software script under wheezy to allow for the installation option. https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software#L4649:
`"LetsEncrypt" "Free, auto SSL cert install allowing https://" $letsencrypt_w \`

`echo -e "\e[1m dietpi-software\e[0m  = Select optmized software for installation."` Good spot :+1:
