### ISSUE TITLE
DietPi-Config | Testing - v6.5 Layout

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#1636]
Layout `dietpi-config` whiptail menu:

Dietpi v6.4:

![180318-0009](https://user-images.githubusercontent.com/17237601/37571768-5adaa00a-2b01-11e8-800a-aa31bf318411.gif)

Dietpi v6.5:

![180318-0008](https://user-images.githubusercontent.com/17237601/37571772-786c0f0a-2b01-11e8-81d9-29a2e1a8b57c.gif)

**Comment by Fourdee** [comment]
@k-plan 

Due to roll out of G_WHIP in DietPi code. This automatically scales window based on screen dimensions against text lines and optional content: https://github.com/Fourdee/DietPi/issues/1546#issuecomment-370173876
Allows us to remove the hard defined whiptail scaling.

#### Completed:
- 🈯️ DietPi-Software
- 🈯️ DietPi-Cron

#### Started
- DietPi-Config

I'am rolling this out gradually in the code, when possible :)

**Comment by k-plan** [comment]
@Fourdee 

> Allows us to remove the hard defined whiptail scaling.
> - DietPi-Config
>
> I'am rolling this out gradually in the code, when possible.

Ahh ... okay. Make sense. :+1: 

A little side note:
 - it will looks not so puzzling, if you will centred the first line ( `Hardware : RPi Zero W` ) as well, so it will  look more like the old whiptail dialogue before.

![2018-03-19 17-43-53](https://user-images.githubusercontent.com/17237601/37609411-571b9090-2b9d-11e8-9699-1eb67991b6f8.png)


Can we close this ticket?

**Comment by Fourdee** [comment]
@k-plan 

> it will looks not so puzzling, if you will centred the first line ( Hardware : RPi Zero W ) as well, so it will look more like the old whiptail dialogue before.

Can't centre the text in whiptail, we'd need to resize X based on max string length per line.

Would be nice to have implemented, leave ticket open for now, i'll see if I can get round to it.

**Comment by MichaIng** [comment]
If dialog size and text length is known, we could calculate how much space we need to add to beginning of header string to make it look aligned to centre.

Or set max dialog length based on header/text length.

**Comment by Fourdee** [comment]
@MichaIng 

> If dialog size and text length is known, we could calculate how much space we need to add to beginning of header string to make it look aligned to centre.

👍 

My only concern (both methods) is the processing required to check each line of text for its length, and, all the menu/checklist entries (eg: dietpi-software 100+ ). I feel the tradeoff may overall slow the whiptail loading times.

**Comment by MichaIng** [comment]
@Fourdee
Yeah didn't see that the "header" in G_WHIP_MENU is message body, which can be of several lines of course. We would need to handle \n the as well... Might be better than to solve it by G_WHIP_SIZE_X_MAX in urgent cases then.

**Comment by Fourdee** [comment]
> Might be better than to solve it by G_WHIP_SIZE_X_MAX in urgent cases then.

Agree. I've set a limit for all exit prompts.
![image](https://user-images.githubusercontent.com/7077026/38175160-c6b6ac00-35cf-11e8-84ed-39e35f9bad2f.png)

**Comment by Fourdee** [comment]
I'll leave the remaining whiptail menus as automatic X max size for now. Yes, we could hard limit them all, however, should we send a commit that exceeds limits, adds additional checks that defeats the purpose of G_WHIP (to make whiptail + dev simple and effective)

Automatic X scaling based on input text contents is also a no go, due to the additional processing required to check each line of text.

I'll mark this as closed. X size of whiptail is based on the maximum available on screen, upto a set limit (140 i believe).
