### ISSUE TITLE
Automatic update during initial boot not skipping

### ISSUE THREAD

**Issue by EzTargetUK** [MichaIng/DietPi#164]
I'm not sure if this is me setting the options wrong, or a small logic error in the dietpi-software script.

In my dietpi.txt file I've set the following:
AUTO_DietpiSoftware_SkipUpdateRebootPrompt=1

When setting up a new install of the OS on a Raspberry Pi I keep getting the message saying that the DietPi has been updated to the latest version.

I've copied the code from line 3682 to the current test RPi, and the result is a 1, not the 0 that's on the line:

 # cat /DietPi/dietpi.txt | grep -ci -m1 '^AUTO_DietpiSoftware_SkipUpdateRebootPrompt=1'
1
 # cat /DietPi/dietpi.txt | grep -ci -m1 '^AUTO_DietpiSoftware_SkipUpdateRebootPrompt=0'
0

So I'm wondering if line 3682 in dietpi-software should be:

if (( $(cat /DietPi/dietpi.txt | grep -ci -m1 '^AUTO_DietpiSoftware_SkipUpdateRebootPrompt=1') == 1 )); then

**Comment by Fourdee** [comment]
@EzTargetUK 

```
So I'm wondering if line 3682 in dietpi-software should be:

if (( $(cat /DietPi/dietpi.txt | grep -ci -m1 '^AUTO_DietpiSoftware_SkipUpdateRebootPrompt=1') == 1 )); then
```

There was a logic/ordering error in the dietpi-software script which prevented this flag from being read, before the if statement. This occurs on the v104 images.

This has now been resolved: https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L3741-L3744

```
#Prompt user for reboot, if not overridden by automation flag
if (( $(cat /DietPi/dietpi.txt | grep -ci -m1 '^AUTO_DietpiSoftware_SkipUpdateRebootPrompt=1') == 0 )); then
    whiptail --title "$WHIP_TITLE" --msgbox "DietPi has been updated to the latest version.\nYour system will now reboot. Once completed, simply login to resume DietPi Setup. \n\nPress Enter to Continue." 13 65
fi
```

If AUTO_DietpiSoftware_SkipUpdateRebootPrompt=1, the -ci result will be 1, which will skip that section of code (the prompt).

Although this issue is now resolved https://github.com/Fourdee/DietPi/issues/158 , you will need to use the updated v105 image. This is because the dietpi-software script does not change/update until the script is terminated (eg: reboot) as it runs in memory.

I'll get the RPi Jessie v105 image updated and uploaded today then provide you with the URL. Let me know if you need the image for another device (eg: odroid) and i'll create that new image also.

**Comment by Fourdee** [comment]
All DIetPi ARM images have been updated to v106 which resolves the issue:
http://dietpi.com/downloads/images/
