### ISSUE TITLE
Kernel panic on boot

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#1691]
Not sure what happened, my RPi 3 was working dandy yesterday. Today it was unresponsive and a reboot produces the following error messages and hangs. I was on 6.6 before

https://imgur.com/a/htt5w

**Comment by Fourdee** [comment]
@gpioneer90 

Looks like a filesystem corruption on RootFS, usually due to:
- Power loss
- Insufficient PSU
- Unstable SD card

You'll probably want to reinstall the system from scratch. Please use a well branded SD card (eg: Sandisk) and official RPi PSU for stability.

I'll mark this as closed due to it being a hardware/power issue.

**Comment by ghost** [comment]
It all came in a pack from Fry's (a well known electronics retailer in the US). Bummer. Worth posting though in the rare case something is up with 6.6 and more people have this problem (hopefully not).
