### ISSUE TITLE
XRDP not showing Desktop Environment

### ISSUE THREAD

**Issue by SimoneBnc** [MichaIng/DietPi#1727]
#### Required Information:
- DietPi Version | ```6.7```?
- SBC Device (RPi 3)?
- Power supply used (5V 2A)?
- SD card used (Samsung 64GB UHS-3)?
- Distro Stretch

#### Additional Information (if applicable):
- Software title?  XRDP
- Can this issue be replicated on a fresh installation of DietPi?
Yes, just install MATE and XRDP 

#### Expected behaviour:

Like in earlier versions, like v150, you could open RDP connection, insert username and password and you had access to desktop
#### Actual behaviour:

On RDP client you are presented with login screen with Xorg as default, you type username and password and the login window disappears leaving the light blu background and nothing happens on the client side but if you look at the raspberry console you see the desktop environment being loaded.
#### Steps to reproduce:

Install dietpi, then MATE (or any other DE) and XRDP, then connect with any RDP client 
#### Did you submit a ```dietpi-bugreport```?

46b57397-f825-41eb-9e75-e1a274a45cc5-1

**Comment by Fourdee** [comment]
@SimoneBnc 

Thanks for the report 👍 

The login method has changed slightly for Debian Stretch, please verify the following login method was used:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=70#p2074

I'll run a test:
- MATE + XRDP

**Comment by SimoneBnc** [comment]
Actually I did use Xorg but it is opening the DE on the RPI console, unless there is something different to do.

**Comment by Fourdee** [comment]
Confirmed bug:
- 🈵 MATE
- 🈵 LXDE

REF: https://github.com/neutrinolabs/xrdp/issues/731#issuecomment-292903254
https://github.com/neutrinolabs/xrdp/issues/962#issuecomment-350811842

**Comment by Fourdee** [comment]
Tests:
- 🈵 Remove dietpi entries in ```.bashrc```
- 🈵modified startwm.sh ```mate-session```
- 🈵Latest .deb: http://ftp.us.debian.org/debian/pool/main/x/xrdp/xrdp_0.9.6-1_arm64.deb
- 🈵Running xrdp service under ```root```

Logs provide nothing to go on, simply states disconnections:
```/var/log/xrdp.log``` 
```
[20180424-09:19:19] [INFO ] connected client computer name: 4D-LAPTOP2
[20180424-09:19:19] [INFO ] TLS connection established from ::ffff:192.168.0.26 port 4074: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20180424-09:19:19] [DEBUG] xrdp_00003fe1_wm_login_mode_event_00000001
[20180424-09:19:20] [INFO ] Loading keymap file /etc/xrdp/km-00000809.ini
[20180424-09:19:20] [WARN ] local keymap file for 0x00000809 found and doesn't match built in keymap, using local keymap file
[20180424-09:19:22] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
[20180424-09:19:22] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20180424-09:19:23] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
[20180424-09:19:23] [DEBUG] return value from xrdp_mm_connect 0
[20180424-09:19:23] [INFO ] xrdp_wm_log_msg: login successful for display 11
[20180424-09:19:23] [DEBUG] xrdp_wm_log_msg: started connecting
[20180424-09:19:26] [DEBUG] Closed socket 19 (AF_UNIX)
[20180424-09:19:30] [DEBUG] Closed socket 19 (AF_UNIX)
[20180424-09:19:33] [DEBUG] Closed socket 19 (AF_UNIX)
[20180424-09:19:37] [DEBUG] Closed socket 19 (AF_UNIX)
[20180424-09:19:40] [DEBUG] Closed socket 19 (AF_UNIX)
```

**Comment by Fourdee** [comment]
Ok, appears its only functional with Xvnc + vncserver 4 installed. 
Could be an external bug with XRDP, limited to Xorg (although, unsure due to lack of any useful logs for debugging).
Either way, we'll make the changes to DietPi, to automatically install VNC4 server along with XRDP.
![image](https://user-images.githubusercontent.com/7077026/39176940-f81fe09e-47a5-11e8-8906-044b58c461ae.png)

### @SimoneBnc Workaround:
Install VNC4 server
```
 dietpi-software install 28
reboot
```
Use any password, not used for XRDP.

Then select Xvnc as connection method

**Comment by Fourdee** [comment]
NB: personal preference, using VNC4 on its own + RealVNC viewer seems much faster than XRDP, under Xvnc.

Resolved for v6.8, switching to Xvnc method. Marking as completed.

**Comment by SimoneBnc** [comment]
> Use any password, not used for XRDP.

Do you mean to create a new user or what?

**Comment by Ami011995** [comment]
I have also faced same issue with Cent OS 7-6 1810 (Core). I have installed Xrdp 0.9.7 on CentOS(64 Bit) in GUI mode. i am able to connect RDP through Xvnc but using Xorg is having blue screen problem.

OS: CentOS 7-6 1810
Architecture: 64 Bit
Xrdp version: 0.9.7
RDP Client: Windows 10 (RDP 10.2 Supported)

**Comment by MichaIng** [comment]
@Ami011995 
With 0.9.9 its the same.

But to be honest, if you're already install a VNC server, why not using it directly and skip all this RDP hassle? Also it is MUCH faster!! I use the (old) tiny portable TightVNC viewer: https://www.tightvnc.com/download/1.3.10/tightvnc-1.3.10_x86_viewer.zip

But I found a new approach to use the Xorg login option via XRDP:
- https://github.com/neutrinolabs/xorgxrdp
- https://packages.debian.org/buster/xorgxrdp (perhaps CentOS ships is as well)

The Debian package page makes it actually quite clear that these drivers are required for direct X server connection: https://packages.debian.org/buster/xrdp
On Jessie they did not yet exist, so were obviously integrated into the xrdp package (obviously source-wise), which is why this issue here came up with Stretch.
#### EDIT bingo, on Debian `apt install xorgxrdp` allows to connect via XRDP without VNC server via direct Xorg login method.
- At least I am presented the desktop, but mouse + keyboard not functional (this is a VM) 🤔.
________
But note this is the "DietPi" GitHub site, so you should consult the CentOS community in this.
