### ISSUE TITLE
FeatureRequest: /var/log to SD/USB-Drive

### ISSUE THREAD

**Issue by Gill-Bates** [MichaIng/DietPi#1766]
I would really apprechiate the feature, to shift the /var/log to USB/SD-Drive. Like already implemented for the UserData. Right now I must solve it with nasty Symlinks tricks which fail2ban dosen't really like.

**Comment by MichaIng** [comment]
@WTFMaster 
Thanks for your request.

Great idea, was already thinking the same by times. Combines benefits from persistent logging (available crash logs) and RAMlog (reduced SD writes) and gives even more flexibility (read logs from external system, in case of broken boot).

Generally would be possible via symlink or mountpoint. We just need to assure that all disk logging is started after ALL drives are mounted. But I think this should be already the case, as syslog/rsyslog/journalctl services start after fstab is handled, or at least write the early boot logs (before even rootfs is mounted) to disk afterwards? Needs testing.

Is quite larger tasks all together I think, would be good then to combine this with DietPi-RAMlog or merge it into a new system where RAM as logging location is just one option.

**€: Just checked with USB stick on VM with persistent journalctl logging:**
```
May 12 15:27:02 DietPi kernel: EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
...
May 12 15:27:02 DietPi systemd-journald[143]: Journal started
May 12 15:27:02 DietPi systemd-journald[143]: Runtime journal (/run/log/journal/a4dc74fd5cff44b5b068664f071d228f) is 2.4M, max 9.9M, 7.4M free.
May 12 15:27:02 DietPi systemd[1]: Starting Flush Journal to Persistent Storage...
May 12 15:27:02 DietPi systemd-journald[143]: Runtime journal (/run/log/journal/a4dc74fd5cff44b5b068664f071d228f) is 2.4M, max 9.9M, 7.4M free.
May 12 15:27:02 DietPi systemd[1]: Started Flush Journal to Persistent Storage.
...
May 12 15:27:03 DietPi kernel: usb usb1: New USB device found, idVendor=1d6b, idProduct=0001
...
May 12 15:27:05 DietPi kernel: sd 3:0:0:0: [sdb] Attached SCSI removable disk
May 12 15:27:07 DietPi systemd[1]: mnt-9EEE\x2dB256.automount: Got automount request for /mnt/9EEE-B256, triggered by 696 (mount)
May 12 15:27:07 DietPi systemd[1]: Mounting /mnt/9EEE-B256...
May 12 15:27:08 DietPi systemd[1]: Mounted /mnt/9EEE-B256.
```
- `systemd-journald` starts shortly after rootfs is mounted, flushing early boot messages to disk, if I understand right.
- USB ports/devices are recognized relatively long after this and final mount of the USB stick several seconds later.
- Not sure if it's easily possible to convince journalctl, rsyslog or any other logging system to start disk logging after all drives are mounted.
- Otherwise would need some complicated service to link/mount external logging location onto /var/log but merge existing entries from /var/log with the external ones before, so that nothing is lost. Especially for journalctl this is not easily possible via `cat`, perhaps:
```
systemctl stop systemd-journald
mount/link external logging drive
systemctl start systemd-journald
```
works, if logs are kept within RAM as well.

**Comment by FlybyKnights** [comment]
Simple workaround:

Grab the code from [here](https://unix.stackexchange.com/questions/228015/move-a-file-and-replace-it-by-a-symlink) (the one with the 'while' statement) and add it to` nano /bin/mvln` then make it executable `chmod +x  /bin/mvln`

That gives you the ability to move files and leave behind symbolic links using `mvln original_path target_path`

Now its just a matter of running `mvln /var/log/what_ever_file_you_want /usb_disk_path/.configs`

I've used it to move my configurations to the USB Drive. If my SD corrupts / blow up, i just re-install all the apps. Delete their folders and re-symlink them. No issues

**Comment by Fourdee** [comment]
I see no reason for this currently, as the majority of our users have RAMlog installed:
https://dietpi.com/survey/

I'll mark as closed, however, please reopen if required.
