### ISSUE TITLE
META | Dedicated DietPi-Software overview page

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1768]
> https://dietpi.com/dietpi-software.html

Think it would look great, started this last year and never got a chance to finish it.

**Comment by MichaIng** [comment]
@Fourdee 
Yey would be indeed beautiful and allow interested ones a closer look without going one step further into the forum. But quite some work as well 😅.

**Comment by Fourdee** [comment]
Notes:
- software_0.jpg = mini box, logo (320x200)
- software_1.jpg = Large box, actual (640x400)
- software_2.jpg = Full size image, new window when _1 is selected.

JPEG compression = 50% GIMP quality setting

--- 

To Do:
- vnc_1.jpg (all vnc servers)
- Add info.

**Comment by Fourdee** [comment]
Made a start: https://dietpi.com/dietpi-software.html
Really want this available to end users.

**Comment by Fourdee** [comment]
mmm, Might simplify this a little, instead of having the large box with info, simply link to forum info when box selected? Less duplicate info + maintenance.
Or, we could move everything off the forum, however, dead links, no direct links, scaling of main info would be inconsistent.

**Comment by Fourdee** [comment]
Ok, in regards to having all the usage info on the new page. Made the decision this will be based on how much info there is per item.

EG: All desktop info will be on the new site
EG: VNC info will still link to forum, as we cannot cleanly code sections, and, its too long.

To achieve full move from forum to the new page, i'll either need to spend weeks improving my HTML/CSS knowledge, or, someone is willing to help us improve the HTML/CSS backbone of template so we can make this possible.

**Comment by Fourdee** [comment]
Note to setf: Downloads completed: https://dietpi.com/dietpi-software.html

**Comment by DJCrashdummy** [comment]
as this site is/should be dedicated to end users beside the (already included :ballot_box_with_check: ) hint that some software may be disabled due to their hardware, IMHO it should be mentioned at the introduction, that this is only the little selection of highly optimized or/and pre-configured software but **still numerous other software can be installed** via apt, aptitude, synaptic, etc. like usual under debian (because dietpi is based on it).

btw: mentioning the base - at least as i did now - may also be reasonable there, since it is nowhere else mentioned at the homepage. it seems to me like after the transition from wheezy to jessie all easily recognizable references to debian vanished from the homepage.

**Comment by MichaIng** [comment]
@DJCrashdummy 
This is an important point, thanks for mentioning. The main advantage of DietPi, being based on Debian, is the flexibility of using APT and being able to use Debian (respectively Raspbian) related guides, as well as Ubuntu guides in most cases. This should be outlined at the places where DietPi-Software is promoted.

We could go further and add some information on a dedicated page, about where DietPi behaves different than standard Debian/Raspbian, what you have to take care about when adjusting the system, e.g.
- Software services being controlled by DietPi-Services, instead of SystemD => systemctl disabled means DietPi controlled
- Using DietPi-Software and DietPi-Config where possible, as manual installations/adjustments might break the behaviour of similar DietPi settings and installations.
- By default disabled kernel modules and removed packages, that you would expect on default Debian, as we provide a vastly reduced image in terms of RAM and disk usage:
   - no NTP since v6.9 => moved to systemd-timesyncd, but without systemd-time**date**d (`timedatectl`)
   - no dbus, as long as not desktop (or time sync daemon mode) is selected
   - ... and things like that.

@Fourdee 
I think for such things, also to make user contribution easier and sort github issues, a Wiki would be useful. Would you mind to add one to DietPi repo? I didn't find a way to do this myself. We could move DietPi-PREP information, image creation procedure and things like that as well, so they will not be forgotten at the last page of open issues 😛.
Also HowTos and user guides from the forum could be ported and the other way round. Of course by times. But at least to have the possibility, if one has some spare time 😄.

**Comment by Fourdee** [comment]
@MichaIng 

>  if one has some spare time

I've written 'spare time' on my xmas list to Santa 😉, although, i'll probably end up with Coal again 🥂 

🈯️ I'll enable the WiKi section now, but may be some time before I can even begin to make a start on it.

@DJCrashdummy 

Thanks for your feedback, we'll take it on-board 👍

**Comment by Fourdee** [comment]
Note to self: NextCloud completed: https://dietpi.com/dietpi-software.html

**Comment by DJCrashdummy** [comment]
@MichaIng exactly! mentioning the base is surly useful for every user (beside pointing out that there is more than the listed software for complete newbies), but the further information may just be interesting for more techy users and should only be linked.
good idea with the wiki! so the information can be collected collaboratively and extended any time, like a comparison to other distributions...
yes, in longterm this is also a better place for user-guides, how-tos, etc. :+1: 

---
> I've written 'spare time' on my xmas list to Santa :wink:, although, i'll probably end up with Coal again :clinking_glasses:

same here... :disappointed: every year!  but @Fourdee made my day! :stuck_out_tongue_winking_eye:

**Comment by Fourdee** [comment]
Pending additions: 
- https://github.com/Fourdee/DietPi/issues/1845#issuecomment-397447909 113
- 🈯️ https://github.com/Fourdee/DietPi/issues/1866 112
- https://github.com/Fourdee/DietPi/issues/1874 114

**Comment by Fourdee** [comment]
Note:
- From Pydio onwards:
-- _0.jpg
-- URL link + header name

**Comment by Fourdee** [comment]
To Do: https://dietpi.com/dietpi-software.html
- From OpenBazzar onwards: 
-- Go through all items, add/check 
-- pros/cons + info + pictures + our ratings
- 🈯️ Add pending additions https://github.com/Fourdee/DietPi/issues/1768#issuecomment-397526254
- Check for any removals since we started.

**Comment by Fourdee** [comment]
Considering scrapping the "Our rating" item. Leave the "Performance rating in". Its near impossible to gauge our thoughts for all software in a general rating, however, we can do performance based on how it runs, and, the sourcecode language used.

**Comment by Fourdee** [comment]
I've set this live. Its around 85% completed:
https://dietpi.com/dietpi-software.html

However, all software logos are now in, and links to their full info.

I'll finish off the rest, as/when I can.

![image](https://user-images.githubusercontent.com/7077026/43495341-7bf7b5b4-952f-11e8-801e-1e334e2f33ca.png)

**Comment by MichaIng** [comment]
This is now handled on the dedicated website repository: https://github.com/MichaIng/DietPi-Website/issues/13
Marking as closed here.
