### ISSUE TITLE
Nextcloud certificate end problem

### ISSUE THREAD

**Issue by ludji49** [MichaIng/DietPi#1796]
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version 6.8
- SBC Device (EG: RPi 3) RPi 3
- Power supply used EG: 5v 1A RAVpower
- SD card used  Sandisk ultra 32
- Distro Jessie

#### Additional Information (if applicable):
- Software title?certificate nextcloud 
- Can this issue be replicated on a fresh installation of DietPi :non

#### Expected behaviour:
 nextcloud certificate end problem
#### Actual behaviour:
non

#### Steps to reproduce:
non

#### Did you submit a ```dietpi-bugreport```? non
 non

#### Extra details:

![2018-05-26_073215](https://user-images.githubusercontent.com/10480101/40572856-27b0fe68-60b7-11e8-9ff4-e33eda5ac412.png)

**Comment by MichaIng** [comment]
@ludji49 
You have a `letsencrypt` certificate I assume and as far as I remember from your last issue? 3 months duration fits to this.

Seems like the automated renewal is not active.

Please try to run `dietpi-letsencrypt 1`.

**Comment by ludji49** [comment]
here is the result

![2018-05-27_204510](https://user-images.githubusercontent.com/10480101/40589522-ee77f064-61ee-11e8-897c-6177c95ffa82.png)

**Comment by MichaIng** [comment]
@ludji49 
Ah I remember we changed your webserver root last time to have Nextcloud available directly at domain, instead of at domain/nextcloud. Yes as mentioned already that time this causes some incompatibility with DietPi.

But this one is easy to fix. DietPi-LetsEncrypt tries to use /var/www as webroot where yours is at /var/www/nextcloud. Let's try to call certbot directly with this adjusted. On next certificate renewal, this setting is saved:
`certbot renew -a webroot -w /var/www/nextcloud`

**Comment by ludji49** [comment]
here is the result
It must be good.

![2018-05-28_062449](https://user-images.githubusercontent.com/10480101/40597157-ebc01a26-623f-11e8-84ac-ed167cf586a8.png)
![2018-05-28_063052](https://user-images.githubusercontent.com/10480101/40597272-b807a162-6240-11e8-9883-3b8e2943b708.png)

**Comment by MichaIng** [comment]
@Ludji49 
Jep looking good. As mentioned, end of Juli the certbot cron job will perform the certificate renewal automatically with the new settings, so nothing more to do about this. 
I will mark as closed.
