### ISSUE TITLE
DietPi NativePC BIOS 32 Bit Version

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#1854]
Hi, any change to make a Native PC BIOS x86 32 bit DietPi version for old computers?

Thanks

**Comment by MichaIng** [comment]
@symbios24 
Thanks for your request.

Please check:
- https://github.com/Fourdee/DietPi/issues/805
- https://github.com/Fourdee/DietPi/issues/1531, where Fourdee already answered your question 😉.

As this means that we need to rework and test the installation scripts of properly 100 software titles, our current priorities and man power do not allow us to start with this.

However, I have the plan to implement some polling feature about regularly updated current community and development questions into DietPi, to estimate the general interest for such with v6.10 into DietPi, properly supported by a poll within the forum (for users which do not use DietPi because of this missing feature/software/image).

**Comment by symbios24** [comment]
Thanks for the response.
But if already you tested the Native PC BIOS x64 that could mean that the software that includes  will work theoretically only the os need`s 32 bit architecture/conversion etc.

**Comment by symbios24** [comment]
Thanks for the response.
But if already you tested the Native PC BIOS x64 that could mean that the software that includes will work theoretically only the os need`s 32 bit architecture/conversion etc.

i can help by testing it if you want

**Comment by symbios24** [comment]
Thanks for the response. i tested the image today and thought it was both 32/64 bit because of the name etc x88 x64
But if already you tested the Native PC BIOS x64 that could mean that the software that includes will work theoretically only the os need`s 32 bit architecture/conversion etc.

i can help with the testing it if you want

**Comment by symbios24** [comment]
Thanks for the response. i tested the image today and thought it was both 32/64 bit because of the name etc x86 x64
But if already you tested the Native PC BIOS x64 that could mean that the software that includes will work theoretically only the os need`s 32 bit architecture/conversion etc.

i can help with the testing it if you want

**Comment by symbios24** [comment]
Thanks for the response. i tested the image today and thought it was both 32/64 bit because of the name etc x86 x64
But if already you tested the Native PC BIOS x64 that could mean that the software that includes will work theoretically only the os need`s 32 bit architecture/conversion etc.
i can help with the testing it if you want

For example you can start by putting the 10 most popular software eg:
Plex Server / Transmission / deluge / hotspot / Tor / amiberry / kodi etc
and in time putting more if tested and working you dont have to put everything at once
just a suggestion

**Comment by Fourdee** [comment]
#### I'll mark this as closed for the following reasons:
- 32bit x86 is being phased out, most PC's in the last 8+ years will have 64bit support.
- The sheer workload required to add support for 32bit x86, would take weeks/months of coding and testing. Time we could spend on better improving DietPi in more critical areas.

#### In short: We are not planning to provide a 32bit x86 Native PC image, or support at this time.
