### ISSUE TITLE
DietPi-Software | How to update UrBackup server via reinstall?

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#1871]
There is a new version of UrBackup server available (2.2.1.1). Download it [here](http://www.urbackup.org/download.html).

- DietPi Version 6.9
- SBC Device (EG: C2)

**Comment by Fourdee** [comment]
@LexiconCode 

Thanks, we'll update it for v6.10 👍

**Comment by MichaIng** [comment]
@LexiconCode @Fourdee 
Hmm, we actually updated `dietpi-software` to install the new version with v6.9: 
- https://github.com/Fourdee/DietPi/pull/1774
- https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L4246-L4259

But we usually do not upgrade software titles on `dietpi-update`, because the installation scripts often overwrite config files, also for UrBackup: https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L4282-L4285
So you could do `dietpi-software reinstall 111` to update to current version, but be sure to backup config files and data before.

**Comment by LexiconCode** [comment]
@MichaIng 
Whoops I miss that. I will back up the configuration.

This seems like a straightforward enhancement to dietpi. 
For the software that requires a reinstall to update could dietpi backup then restore configurations for `dietpi-software reinstall xxx`?

**Comment by Fourdee** [comment]
> For the software that requires a reinstall to update could dietpi backup then restore configurations for dietpi-software reinstall xxx?

Not a bad idea 👍 

I'll add a prompt to ```reinstall``` for a ```dietpi-backup 1```.

**Comment by Fourdee** [comment]
```G_BACKUP```
![image](https://user-images.githubusercontent.com/7077026/41981122-113f49dc-7a20-11e8-975b-919cc10a152d.png)

**Comment by Fourdee** [comment]
Completed.

**Comment by Fourdee** [comment]
Actually, we need to exclude this from patching reinstalls (mid patch backups not recommended), add the prompt prior to ```dietpi-update```
🈯️  https://github.com/Fourdee/DietPi/commit/c41a385c5d8d13ebe904c071fcba82a667adac28

**Comment by Fourdee** [comment]
Completed.

**Comment by LexiconCode** [comment]
Real quick is that a complete dietpi backup or just the configuration files specific to the software that are restored on top of the new reinstall?

**Comment by Fourdee** [comment]
@LexiconCode 

> Real quick is that a complete dietpi backup or just the configuration files specific to the software that are restored on top of the new reinstall?

Complete backup. Its the only sure way we can ensure all configuration files/settings, pre-reqs etc are backed up, in its current state.
