### ISSUE TITLE
DietPi-Software | LXQt desktop

### ISSUE THREAD

**Issue by FusionPlmH** [MichaIng/DietPi#1918]
It is possible to install Lxqt onboth device ？ Because seem lxqt modern then lxde more light weight and less resources use 。Please help if it possible to add in dietpi-software（sorry about my English）（A user from Hong Kong)

ADMIN EDIT: Vote for it on FeatHub: https://feathub.com/MichaIng/DietPi/+9

**Comment by MichaIng** [comment]
@LeeMenHin 
Thanks for your request.

Indeed LXQt seems to be interesting. Lubuntu 18.10 switches as well. Some complaints are that it is (still) a bid buggy.

I will do some test installation and see if it works well with our software offer. But there is much to do besides, so could take a time from my side 😉.

**Comment by FusionPlmH** [comment]
thx a lot bro always support you。 If here i can help

**Comment by Fourdee** [comment]
Qt a great library, however, it has a vast number of pre-reqs, could result in a bulkier (and possibly slower) installation than current.

**Comment by MichaIng** [comment]
Just tried it out on VM. Works fine so far. 

**About the package size:**
RPi (LAMP server + full featured Nextcloud installed):
- `apt install lxqt xserver-xorg xinit` => `479 MB of additional disk space will be used.`
- `apt install lxqt-core xserver-xorg xinit` => `366 MB of additional disk space will be used.`
- `apt install lxde xserver-xorg xinit` => `401 MB of additional disk space will be used.`
- `apt install lxde-core xserver-xorg xinit` => `363 MB of additional disk space will be used.`

But on VM (most clean image) the other way round:
- `apt install lxqt xserver-xorg xinit` => `288 MB of additional disk space will be used.`
- `apt install lxqt-core xserver-xorg xinit` => `281 MB of additional disk space will be used.`
- `apt install lxde xserver-xorg xinit` => `330 MB of additional disk space will be used.`
- `apt install lxde-core xserver-xorg xinit` => `300 MB of additional disk space will be used.`

Interesting, that it takes so much more space on RPi, even that more system/library packages should be already installed. But anyway these numbers don't say much. The difference is not that large, that you can speak of a total different concept. Both tend to be lightweight.

On VM, desktops are anyway a bid slow, so hard to compare, but the difference at least is not large.
I would not replace LXDE, but add LXQT to our Desktop offer. But it needs to be integrated and tested with our desktop software offer of course.

**Comment by Fourdee** [comment]
@MichaIng 

> LXDE, but add LXQT 

Yep agree 👍  Offer it as an additional selection.

**Comment by FusionPlmH** [comment]
Very nice to hear about working on . Stay and wait
~

**Comment by MichaIng** [comment]
Added to FeatHub, feel free to vote for it: https://feathub.com/MichaIng/DietPi/+9

**Comment by MichaIng** [comment]
Thanks to @Fourdee we will have LXQt available with v6.23: https://github.com/MichaIng/DietPi/commit/697e33217bc5850841373f6f59eafc1abbd42bf7
Many thanks for your great effort 😃. Perhaps we can take the chance and add a desktop preference similar to webserver preference?

Currently when a software is chosen that requires a desktop, but no desktop is or was chosen before, LXDE will be installed by default, which is the best, because most lightweight, default IMO. But would be great to give user the choice before?

**Comment by Fourdee** [comment]
:u6307: Available in DietPi v6.23:
<img width="960" alt="LXQT" src="https://user-images.githubusercontent.com/7077026/56425443-413e2700-62ac-11e9-8f1f-82ea1f8ec453.png">

**Comment by MichaIng** [comment]
@Fourdee 
Many thanks. Will directly try it out on notebook 😃. I reopen the issue to not forget adding this to beta testing phase to perhaps gain some feedback for fine tuning or something.

**Comment by Fourdee** [comment]
@MichaIng 


Testing passed for:
- :u6307: x86:64 native with auto start (Stretch)
- :u6307: RPi with TightVNC server (Stretch)
- :u5408: Taskbar issues with Buster. Needs a separate ```lxqt.7z``` config set.

Also running LXQt on my laptop daily driver with buster :smile: . Very nice.

**Comment by MichaIng** [comment]
@Fourdee 
Yeah, good point to test Buster now as well on a regular basis. Going through all software titles is still a task to do, but has the advantage that all web applications must stand PHP7.3, and that goes hand-in-hand with the decision to move Stretch systems to either PHP7.2 or PHP7.3. Nextcloud 16 is already on RC3 and will not support PHP7.0 anymore... Damn thing since for sure some users will run into the issue to have an incompatible version installed until we release v6.23 🙈.

**Comment by Fourdee** [comment]
Changes:
- LXQT theme for both Stretch and Buster
- Speedcrunch installed by default (QT based calculator)
- ```apt-mark auto``` for uninstall of non core desktop items (eg: additions ```firefox-esr```)

**Comment by MichaIng** [comment]
@Fourdee 
On Buster `G_CONFIG_INJECT 'use_trash=' 'use_trash=0' /etc/xdg/libfm/libfm.conf` fails since the file does not exist.

And:
LXQt install on Buster failed because `leafpad` package is missing: https://packages.debian.org/stretch/leafpad

That is actually not desired since at least the LXDE package depends on `leafpad` as well: https://packages.debian.org/buster/lxde

I guess/hope it is resolved quickly. But for now we should perhaps ship [mousepad](https://packages.debian.org/buster/mousepad) for now?
__________
🈯️ LXDE: `mousepad` is chosen automatically as alternative dependency. So it's an LXQt only issue. So we'll go with `mousepad` as well for now on Buster.
🈯️ On Raspbian Buster `leafpad` is available, so Debian Buster only issue.
___________
- [x] Leafpad on Buster issue fixed with: https://github.com/MichaIng/DietPi/commit/8bc33bdb58d0554d2498506ac46b4b1033db6284

**Comment by MichaIng** [comment]
About `libfm.conf`:
- On Buster [pcmanfm-qt](https://packages.debian.org/buster/pcmanfm-qt) does not depend on libfm-modules which depends on libfm-data recursively which ships the file:
```
root@VM-Stretch:~# dpkg -S /etc/xdg/libfm/libfm.conf
libfm-data: /etc/xdg/libfm/libfm.conf
```
- On Stretch this is the case: https://packages.debian.org/stretch/pcmanfm-qt
- So I guess on Buster the trashbin is implemented differently, so we skip this adjustment simply. We can find out in a future version how to turn off trash bin by default on Buster, if this is not yet the case.

**Comment by Fourdee** [comment]
@MichaIng 

Featherpad also alternative option, seems to replace leafpad?
- :u6307: Also runs on QT5 native, so less deps
![image](https://user-images.githubusercontent.com/7077026/57178580-99f3ef00-6e6a-11e9-8b34-487bb6043a51.png)
 
https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=featherpad

EDIT: Done the commit to change to featherpad for Buster+, can revert if needed?

**Comment by MichaIng** [comment]
@Fourdee 
<s>Featherpad is Qt only.

On LXDE mousepad is chosen automatically as replacement (alternative dependency), so to be consistent we should just apply/follow this on all desktops?</s>

Ah I see, mousepad ships GTK dependencies that are not native on Qt based desktops, right?
Yeah so then I agree to go with the one that integrates more natively 👍.
