### ISSUE TITLE
DietPi-Software | Shellinabox: Shell via browser

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1967]
- Install by default on Allo GUI images
- Install by default on all DietPi images?
```
Need to get 115 kB of archives.
After this operation, 506 kB of additional disk space will be used.
```
<img width="960" alt="1" src="https://user-images.githubusercontent.com/7077026/43350071-433ceacc-91fc-11e8-9b3f-49cd831e7a62.png">

![image](https://user-images.githubusercontent.com/7077026/43350072-45a256c6-91fc-11e8-85a1-c33216019389.png)

Vote for it on FeatHub: https://feathub.com/MichaIng/DietPi/+25

**Comment by Fourdee** [comment]
```
/etc/default/shellinabox
SHELLINABOX_ARGS="--no-beep --disable-ssl"
```

**Comment by MichaIng** [comment]
@Fourdee 
Nice, if one needs to access from many different clients and/or mobile, where not always SSH client is available. But for security reasons I would always prefer a real SSH client where possible. Also for this reason `--disable-ssl` should be never added? Standalone webserver included which needs SSL certificates? Perhaps we can add self-signed/snakeoil certs first and then handle it within `dietpi-letsencrypt` as well.

For Allo GUI images it could be interesting to add it and implement into the Allo GUI? But on other images I would not add it by default. So far no one asked for it (?) and due to above reasons I also would not use it. I access to my server from local network only.

**Comment by Fourdee** [comment]
@MichaIng 

> --disable-ssl should be never added? Standalone webserver included which needs SSL certificates? 

Yep.

> But on other images I would not add it by default.

Agree, lets make it a optional software title in ```dietpi-software```. Pre-installed for Allo GUI

**Comment by sparkysbc** [comment]
without adding  --disable-ssl  users can still access by https://192.168.0.100:4200   ,then need to add permission on advanced option
by adding --disable-ssl access by  192.168.0.100:4200 or http://192.168.0.100:4200

**Comment by MichaIng** [comment]
Added to FeatHub, feel free to vote for it: https://feathub.com/MichaIng/DietPi/+25

**Comment by MichaIng** [comment]
This functionality is basically covered by our new DietPi-Dashboard: #448
And installing Shellinabox, when wanted is as easy as: https://packages.debian.org/bullseye/shellinabox
```sh
apt install shellinabox
```
So a `dietpi-software` implementation would be overkill. I'll mark this hence as closed.
