### ISSUE TITLE
DietPi-Drive_Manager | Add support for hdparm idle spindown, as, a global option for all drives

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2001]
Ref: https://dietpi.com/phpbb/viewtopic.php?f=9&t=4382
Man: https://manpages.debian.org/stretch/hdparm/hdparm.8.en.html

- We just apply settings to `/dev/sda`. Maybe we should move this to drive manager, automatically applying/adding an entry for each /dev/sdX drive fount?
- Adding entries then as one-liner should be possible: `/dev/sda { spindown_time = 120; apm = 254 }` and with this enabling selective parsing and enables us by times to even add power management control to drive manager UI for each drive.

Not sure about the current settings. On my RPi anyway power management is controlled by the docking station, thus can't test it here.
- `apm = 254` =>` no spindown` according to man page
- `spindown_time = 120` => 10 minutes, does this even apply with the above set?

**Comment by MichaIng** [comment]
Indeed apm = 127 seems to solve it.

**Comment by Fourdee** [comment]
I finally got there with the title lol

**Comment by Fourdee** [comment]
Note to self:
- Write new file each time with database of drives?
```
root@DietPi:~# grep -v '^#' /etc/hdparm.conf

quiet

/dev/sda {
        #10 mins
        spindown_time = 120

        #
        apm = 254
}
```

Planned options, unique to each drive:
- APM setting
- Spindown time setting

NB: will be a lengthy while process to scrape the above file to obtain current values... Store them in .dietpi-drive_manager?

**Comment by Fourdee** [comment]
Cant use this, unless we scrape results, always returns 0:
```
root@DietPi:~# hdparm -M /dev/mmcblk0; echo $?

/dev/mmcblk0:
 HDIO_DRIVE_CMD(identify) failed: Invalid argument
0
```

**Comment by Fourdee** [comment]
```hdparm``` has a max duration of:
```
root@DietPi:~# hdparm -S 1024 /dev/sdb
  -S: bad/missing standby-interval value (0..255)
root@DietPi:~# hdparm -S 255 /dev/sdb

/dev/sdb:
 setting standby to 255 (21 minutes + 15 seconds)
root@DietPi:~# hdparm -S 1 /dev/sdb

```

---

APM

$NF and check valid int
```
root@DietPi:~#  hdparm -B /dev/sda

/dev/sda:
 APM_level      = 254
```

**Comment by Fourdee** [comment]
```hdparm``` always returns 0 exit code, even if the device does not support its feature. So we have no way of knowing if the value has been correctly applied ☹️ 

We could scrape check for ```not supported```, however, this then becomes an issue if the output changes due to software updates.
```
root@DietPi:~# G_RUN_CMD hdparm -M 254/dev/sda
[  OK  ] hdparm -M 254 /dev/sda
root@DietPi:~# hdparm -M 254 /dev/sda

/dev/sda:
 setting acoustic management to 254 
SG_IO: bad/missing sense data, sb[]:  f0 00 05 00 00 00 00 14 00 00 00 00 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SG_IO: bad/missing sense data, sb[]:  f0 00 05 00 00 00 00 14 00 00 00 00 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 acoustic      = not supported

```

---

> https://wiki.archlinux.org/index.php/hdparm
```-S```
The value of 0 disables spindown, the values from 1 to 240 specify multiples of 5 seconds and values from 241 to 251 specify multiples of 30 minutes.

---

🈴 My WD Blue 1TB is incompatible with ```hdparm```:
```
root@Fuzon:~# hdparm -M /dev/sdb

/dev/sdb:
 acoustic      = not supported
root@Fuzon:~# hdparm -B /dev/sdb

/dev/sdb:
 APM_level      = not supported
```

**Comment by Fourdee** [comment]
Change to a global option for all drives, to set a desired spindown duration. APM is hard coded to 127 to allow spin down.

Applied directly with ```hdparm``` and saved to config with ```/etc/hdparm.conf```

To be honest, this is the best I can do at the moment, considering the lack of standardization from HDD manufactures, USB<>SATA converter manufactures, and, compatibility/features/limitations of/with ```hdparm```. Nightmare.

**Comment by Fourdee** [comment]
### Testing:
- Find a drive that is compatible with ```hdparm``` to test
- 🈯️ Set spindown to 60 seconds, wait, verify
-- 🈯️ Working on SSD 🤣 
```
root@Fuzon:~# hdparm -C /dev/sdb; hdparm -C /dev/sda

/dev/sdb:
 drive state is:  active/idle

/dev/sda:
 drive state is:  active/idle
root@Fuzon:~# hdparm -C /dev/sdb; hdparm -C /dev/sda

/dev/sdb:
 drive state is:  active/idle

/dev/sda:
 drive state is:  standby
```
- 🈯️ Reboot, wait, verify

**Comment by Fourdee** [comment]
Completed. However, end user results will vary due to https://github.com/Fourdee/DietPi/issues/2001#issuecomment-418939193

**Comment by Fourdee** [comment]
[FAILED] DietPi-Drive_Manager | hdparm -B 127 /dev/mmcblk0
[FAILED] DietPi-Drive_Manager | hdparm -B 127 /dev/mmcblk0
[FAILED] DietPi-Drive_Manager | hdparm -B 127 /dev/mmcblk0


--------------------------------------------------------------------
- DietPi has encounted an error, and, is unable to continue        -
- Please create a ticket: https://github.com/Fourdee/DietPi/issues -
- Copy and paste the BLUE lines below, into the ticket             -
--------------------------------------------------------------------


#### Details:
- Date           | Thu  6 Sep 04:05:47 BST 2018
- Bug report     | N/A
- DietPi version | v6.15
- Img creator    | DietPi Core Team
- Pre-image      | Meveric
- SBC device     | Odroid C2 (aarch64) (index=12)
- Kernel version | #1 SMP PREEMPT Sun Aug 19 15:27:56 CEST 2018
- Distro         | stretch (index=4)
- Command        | hdparm -B 127 /dev/mmcblk0
- Exit code      | 22
- Software title | DietPi-Drive_Manager

#### Steps to reproduce:

1. ...
2. ...

#### Expected behaviour:

- ...

#### Actual behaviour:

- ...

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
 HDIO_DRIVE_CMD failed: Invalid argument
 HDIO_DRIVE_CMD(identify) failed: Invalid argument

/dev/mmcblk0:
 setting Advanced Power Management level to 0x7f (127)
```


--------------------------------------------------------------------

[FAILED] DietPi-Drive_Manager | Unable to continue, DietPi-Drive_Manager will now terminate.
