### ISSUE TITLE
Update VM/RPi/Sparky images

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#2010]
> https://twitter.com/xmijo/status/1029321254925488129

**Comment by MichaIng** [comment]
Makes sense, I will also update the pending VM image once v6.13 release.

**Comment by MichaIng** [comment]
🈯️ VirtualBox v6.13 image online for testing: https://dietpi.com/downloads/testing/DietPi_VirtualBox-x86_64-Stretch.7z
🈯️ VirtualBox v6.13 Buster experimental image: https://dietpi.com/downloads/testing/DietPi_VirtualBox-x86_64-Buster.7z
- Forgot to change `.version` string in `/boot/dietpi/.version`, thus first run shows v6.12 + update, but since it's a quick patch, no big problem 😉.

🈯️ VMware v6.13 image: https://dietpi.com/downloads/testing/DietPi_VMware-x86_64-Stretch.7z
🈯️ VMware v6.13 Buster experimental image: https://dietpi.com/downloads/testing/DietPi_VMware-x86_64-Buster.7z

@Fourdee 
Ready. Would be great if you could make quick tests by times also with the Buster images. I will then publish them as experimental/testing images for those who are interested in bleeding edge packages and want to help solving issues early with Buster, so we can offer official Buster images as fast as possible, after it is moved to stable branch. Should be around next summer, according to last major versions schedule.

**Comment by Fourdee** [comment]
NB: 🈯️ RPi image is already done, did it a few days ago.

**Comment by Fourdee** [comment]
@MichaIng 

Thanks Micha 👍 , i've set all images live.

Will test buster images when I can, hopefully over weekend.

**Comment by Fourdee** [comment]
🈯️ Sparky

**Comment by Fourdee** [comment]
@MichaIng 

Tested VMWare images, both working great 👍 

There is an issue with our survey uploads, fails connection test. It occurred after our host went offline yesterday. However, i'll take a look.

Will mark this as closed. Great work @MichaIng 👍
