### ISSUE TITLE
Dietpi instalation error at first run on Nanopi Neo

### ISSUE THREAD

**Issue by dornt2** [MichaIng/DietPi#2031]
The error returned at first run on Nanopi Neo, image 'DietPi_v6.2_NanoPiNEO-ARMv7-Stretch.img'

![diet_pi_nanopi_neo_](https://user-images.githubusercontent.com/42633858/44507755-672b1180-a6b4-11e8-891a-771cf867a21c.jpg)

**Comment by MichaIng** [comment]
@dornt2 
Thanks for your report.

`deb.debian.org` fails to get resolved. Either your systems resolver does not work, or there is (as often) some issue with the Debian mirrordirector.

Please check:
- Test local resolver: `ping dietpi.com`
- Check correct name server entry. You do not need to post the output here, just verify that it contains the IP or hostname of your network gateway respectively DHCP or DNS server: `cat /etc/resolv.conf`

If the above fails, indeed name server is not configured correctly, check that your interfaces are set up correctly:
- By default DHCP should be enabled (if not changed via dietpi.txt settings), thus you should have received a proper IP address within the local network address range. The DietPi login banner should show your current IP, otherwise check with: `ip a`
- The DHCP server should provide a name server as well, which should result in the proper resolv.conf entry above.
- If you set up a static IP, you can manually adjust the DNS server via dietpi-config network adapter settings or more manually via `/etc/network/interfaces`, the dns-nameserver entries. If the current does not work, try to use e.g. the public `8.8.8.8`

If actually DNS resolving works great, then try to change the Debian repo mirror. Open dietpi-config and go to network / misc > APT mirror and chose another there, e.g. the global ftp.debian.org/debian or a more local one, e.g. `ftp.uk.debian.org/debian` and related.

**Comment by dornt2** [comment]
> Check correct name server entry. You do not need to post the output here, just verify **that it contains the IP** or hostname of your network gateway respectively DHCP or DNS server: cat /etc/resolv.conf

Thanks

That was the problem. Initialy the `/etc/resolv.conf` has two rows:
```
nameserver 8.8.8.8
nameserver 114.114.114.114
```
after I added my gateway, which is also a DNS server

```
nameserver __my_IP_gateway_
nameserver 8.8.8.8
nameserver 114.114.114.114
```

Now, the instalation and upgrade, could be acomplished through dietpi-launcher ---> DietPi-Update.

Thanks!
