### ISSUE TITLE
dietpi-backup : progress indicator

### ISSUE THREAD

**Issue by adamotte** [MichaIng/DietPi#2044]
#### Is your feature request related to a problem? Please describe:

- Kind of... WIth dietpi-backup, we can sync our data to another drive but during the process, we have no clue about time pending, time passed or percentage of data already done.

#### Describe the solution you'd like:

- Something like an estimal pending time's or percentage progression's .

#### Describe alternatives you've considered:

- Take a :coffee: or :tea:

#### Additional context:

- Actual behavior : animated dots
![image](https://user-images.githubusercontent.com/1204733/44805942-cfeb2000-abc5-11e8-9c6d-7b9ce1dd06b9.png)

**Comment by adamotte** [comment]
I just found that we can add *pv* command to monitor progress of data sent via a pipe.

![image](https://user-images.githubusercontent.com/1204733/44806191-91a23080-abc6-11e8-879c-92ce49686136.png)

**Comment by Fourdee** [comment]
@adamotte 

Thanks for the request, ```pv``` could be helpful 👍 

The issue from our end is that our ```G_RUN_CMD``` does not support redirects or pipes. So this may actually be a bigger job than originally thought (if at all possible) :)

Leave it with us, we'll take a look when we can.

**Comment by Fourdee** [comment]
Rsync has progress option?
```
 -h, --human-readable        output numbers in a human-readable format
     --progress              show progress during transfer
 -P                          same as --partial --progress
```

REF: https://www.cyberciti.biz/faq/show-progress-during-file-transfer/

**Comment by MichaIng** [comment]
The problem with G_RUN_CMD is that it generally redirects all output (I guess including all progress bars etc.) into a file: `$G_ERROR_HANDLER_COMMAND &> /tmp/G_ERROR_HANDLER_COMMAND`

I guess we would need to call it without G_RUN_CMD and call G_ERROR_HANDLER just afterwards. <s>The only issue then is, that either we can hide debug (transfered file list) output, which can then also not be reviewed afterwards, or show it as well within terminal, which I really don't like, because it spams/fills the whole terminal history, removing output before the actual transfer. 

Not sure if there is a way via rsync option or pv piping to redirect just the transfered file list to a log file?</s>
€: Whoops, nope no issue, we collect output already via rsync option in log file. So call rsync without G_RUN_CMD and instead using progress bar option or pv should be it. Then calling G_ERROR_HANDLER manually afterwards (like we do with `cat`). The processing animation is anyway not needed anymore then 😉.

Btw: We could implement the same in `dietpi-sync`.

**Comment by Fourdee** [comment]
Ok, ```pv``` was messy for me, so lets stick with standard rsync output, it looks like this:
![image](https://user-images.githubusercontent.com/7077026/44934233-0c548280-ad64-11e8-849b-c3bdab38b6c2.png)

**Comment by Fourdee** [comment]
- 🈯️ DietPi-Backup
- 🈯️ DietPi-Sync

**Comment by Fourdee** [comment]
Completed.
