### ISSUE TITLE
Hyper-V images?

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#2060]
Hi any change we can get hyper-v images?

**Comment by MichaIng** [comment]
@ghosted17 
Please contribute to the existing topic: https://github.com/Fourdee/DietPi/issues/804

I am still not fully disinclined, but Microsoft does not make it easy to run different VM platforms on the same machine 😠. It's always a question, if it makes sense to go so many steps (+effort) towards a company/solution, whose goal is to be the only provider, obviously. Better focus and support the others, that make their concurrent implementation easy, are open source etc, from a developer point of view?

But yeah, since it is the last of three widely used VM platforms, perhaps we have to ignore Microsofts behaviour here for the benefit of our users?

Fourdee already remarked to be not very interested in Hyper-V images. I could create some, but to go the usual way it would need Fourdee to test them. Otherwise I could upload them as experimental/unofficial.

I will reconsider after v6.15 release and close this topic in favour of the linked one.
Until that you can relatively easily create your own via: https://github.com/Fourdee/DietPi/issues/1505
- Most of the steps are the same for Hyper-V, just the machine creation itself is different of course.

**Comment by ghost** [comment]
I also had some issues with hyper-v and couldn't run any other vm soft and had to find workarounds. But hey it's a type 1 VM so can't complain that much as all type 1 have there issues.

I'm sure there are plenty of Windows users that use Windows as there primary os / server os and use linux for exotic lightweight services. Rather then buying VMware or running Vbox. Hyper-V is free and build right into the OS especially for Win server services.

When ever/if you get a chance I'd love to test out an image, it should run great and better then running a full linux disto for some simple service.

**Comment by Fourdee** [comment]
@ghosted17 

VM workstation player is free:
https://my.vmware.com/en/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/14_0

Allows you to run multiple VM's on a windows system. Its basically the old Player + multiple VM's and improved control.

**Comment by ghost** [comment]
thanks for the info but I run Win server 16 with hyper v servers and they are rock solid. Don't know how reliable it would be to run vm players that are on 24/7 server and have them auto start / shutdown with Windows.

**Comment by MichaIng** [comment]
@ghosted17 
Not to forget VirtualBox, which allows quite useful VM snapshots and is the only open source solution of this three.

All of those solutions allow autostart with Windows and work reliable, there is no advantage of Hyper-V from that point of view. But I understand that you want to stay with the solutions you are used to and made no bad experience with.

**Comment by ghost** [comment]
I was also exploring alternatives when i had usb pass through issues but For me it's not worth redoing everything as the vms are second priority after Win. if i had to do it over i might go esxi but again for me there maybe a performance loss to windows which i don't want and then im sure esxi will have other issues that i will have to deal with like having to use vmfs for all drives. I hate that. there's hardly any goos recovery software for ntfs I'd imaging vmfs would be a nightmare to recover.

**Comment by MirisWisdom** [comment]
In #804, I occasionally post snapshots of Hyper-V images with the bare minimum modifications to get them flawlessly running on Hyper-V.. @ghosted17, I just posted a link to v6.15 over there, if you want to have a look.

I'm up for doing this on a much more regular basis. @MichaIng - perhaps I should make a more "official" issue where I'll regularly put Hyper-V images?

**Comment by ghost** [comment]
Thanks will definitely check it out. I think supporting the dominant OS in the desktop market would make sense since you guys already support all the others. But that's just my 2 cents, happy either way with a release whenever you guys have the time for it.

**Comment by MichaIng** [comment]
@yumiris 
Jep, feel free to open a new issue about this. I am still thinking to create them officially, based on: https://github.com/Fourdee/DietPi/issues/1505

Have a bid much other things to do (also opened tasks on DietPi) before I can recheck, trying to get Hyper-V running with VBox and VMware on the same machine. But we could also open a sticky thread in the forum to link your images for now? https://dietpi.com/phpbb/viewforum.php?f=5

**Comment by MirisWisdom** [comment]
@MichaIng - yup, all of my images derive from that set of instructions.

Just to confirm, you want me to get Diet running on Hyper-V & VirtualBox/VMware on the same host? 🤔

**Comment by MichaIng** [comment]
> yup, all of my images derive from that set of instructions.

Ah perfect.

> Just to confirm, you want me to get Diet running on Hyper-V & VirtualBox/VMware on the same host? 🤔

Hehe no 😄, as I am already creating VMware and VBox images regularly, I could create the Hyper-V images as well in one rush. But the problem is, that if Hyper-V is installed regularly, it blocks CPU virtualisieren usage for any other VM software, thus VMware and VBox cannot start any more 😠. But it seems to be a background service that does this block, that can be stopped/disabled. Perhaps, when one wants to create all three images on one machine, this Hyper-V service always need to be toggled accordingly. A bid annoying and shame on Microsoft for this unnecessary thing, but it would work at least.

**Comment by MirisWisdom** [comment]
Ah, my bad. Indeed, Hyper-V breaks other hypervisors (and even Vagrant :angry:). Hmm, maybe an alternative is to run a Windows guest in VMware/VirtualBox with Hyper-V installed on it?

**Comment by MichaIng** [comment]
@yumiris 
> Hmm, maybe an alternative is to run a Windows guest in VMware/VirtualBox with Hyper-V installed on it?

AFAIK, VM acceleration cannot be used from within a VM. Perhaps without VT-x/AMD-V enabled it would work, but should be very slow. Then perhaps toggling all Hyper-V Windows services is less hassle, not sure 😉.
