### ISSUE TITLE
/etc/network/if-pre-up.d/wireless-tools | requires net-tools

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#2074]
However, not listed as a APT dep:
https://github.com/Fourdee/DietPi/issues/2070#issuecomment-421088364

Appears only required, when all other methods fail, and, should not effect WiFi usage:
https://github.com/Fourdee/DietPi/issues/2070#issuecomment-421058572

**Comment by MichaIng** [comment]
> Appears only required, when all other methods fail, and, should not effect WiFi usage:

Indeed it appears, if any of the settings failed to be applied. All failed settings are not applied then, as `ifconfig` does not bring up the interface.
But the cases, where impotent settings cannot be applied without interface up, seem to be rare, as we never faced this issue since the quite long time net-tools are not pre-installed any more and got removed on update.

Bug report done: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908886

**Comment by MichaIng** [comment]
Bug solved on current version: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908886#10
- Download available on unstable/sid repo so far only: https://packages.debian.org/sid/amd64/wireless-tools/download
- Only change that I could bind is indeed the ifconfig line being replaced by: `/sbin/ip link set dev "$IFACE" up`, which we can do ourself on v6.16 patch:
`sed -i '\|^[[:blank:]]ifconfig "$IFACE" up$|c\\t/sbin/ip link set dev "$IFACE" up' /etc/network/if-pre-up.d/wireless-tools`

PR up: https://github.com/Fourdee/DietPi/pull/2076

**Comment by Fourdee** [comment]
@MichaIng 

> Bug solved on current version: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908886#10

Legend, great work 👍

**Comment by Fourdee** [comment]
@MichaIng 

Works a charm, no issues in testing 👍 . Marking as completed.
