### ISSUE TITLE
DietPi-Software | qBittorrent: Guide on compiling qBittorrent 4.x, implement into DietPi?

### ISSUE THREAD

**Issue by Millichrome** [MichaIng/DietPi#2085]
I wrote a guide on compiling qBittorrent 4.x on DietPi for ARM devices. DietPi ships with a really old version of qBittorrent from late 2016. I think users of qBittorrent could find this guide useful. I propose adding a link to the guide on the qBittorrent software entry page.  

**Compilation guide**
https://github.com/qbittorrent/qBittorrent/wiki/Compiling-qBittorrent-nox-4.x-on-DietPi-6.16-(Debian-9.0)-for-ARM-devices

**DietPi Entry for qBittorrent**
https://dietpi.com/phpbb/viewtopic.php?t=5&start=70#p2272

**Comment by MichaIng** [comment]
@Millichrome
Thanks for this. We'll have a look if we can implement this into our install script.
____________
Further info:
- Stretch version frozen at 3.3.7: https://packages.debian.org/stretch/qbittorrent-nox
- 4.0.3 available on Buster, 4.1.3 in pipeline on Sid: https://packages.debian.org/buster/qbittorrent-nox

Jep own build as always possible, but I am as always not too keen to implement this as default install to DietPi. Many dependencies to manually install, which can change. Many steps that can fail unexpectedly, needs much testing on all different devices and distro versions, basically all cases where different APT repos are included, leading to much maintenance for a single software title 🤔. Usually I like to stay with the APT versions where possible, even that they are "by design" outdated a while after Debian stable release.

But I will try out the guide, as fast I find time for it, let's see how it works.

**Comment by Millichrome** [comment]
Let me know if there is any way I can help with testing. I have a Raspberry Pi 3 B+ that I can test on and an ASUS tinker board as my "production" system. 

I don't have a lot of experience with linux, but I would be interested in trying to write a compilation script for qBittorrent 4.x.

**Comment by MichaIng** [comment]
@Millichrome 
Btw. many thanks for your guide.

However some remarks, to have this running better on DietPi:
- For security reasons, run qbottorrent service with it's own user and for cross-access reason with group "dietpi". This allows download managers, sonarr and such, as well as media libraries/players to access the downloads of qbittorrent.
Add user: `useradd -rm qbittorrent -G dietpi -s /usr/sbin/nologin`.
Adjust service:
```
[Service]
User=qbittorrent
Group=dietpi
```
- Since `dietpi-services` handles (known) service start/stop, they do not need to be enabled (systemd controlled), at best stay disabled.

Besides that, great work. Will try it out tomorrow.

**Comment by Millichrome** [comment]
I will try this out on my 3B+ and update the guide. 

I am still learning linux. :) It makes sense to have different accounts for different services.

**Comment by MichaIng** [comment]
I mark this as closed. We shift our images to Buster already.
However interested Stretch users can still follow this guide: https://github.com/qbittorrent/qBittorrent/wiki/Compiling-qBittorrent-nox-4.x-on-DietPi-or-Raspbian-(Debian-9.0)-for-ARM-devices

**Comment by crankynet** [comment]
What happened to the guide at
https://github.com/qbittorrent/qBittorrent/wiki/Compilation:-DietPi-and-Raspbian-(Debian-9.0) ?
