### ISSUE TITLE
RE: XU3/4 Autostart Network

### ISSUE THREAD

**Issue by DasClarky** [MichaIng/DietPi#2122]
#### Required Information:
- DietPi version	| 6.14
- Distro version	| `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
- Kernel version	| `uname -a`
- SBC device		| oDroid XU4
- Power supply used	| (EG: 5V 1A RAVpower)
- SDcard used		| (EG: SanDisk ultra)

#### Steps to reproduce:

1. ... Turn the device on after 6.15 
2. ... As above

#### Expected behaviour:

- ... Network should come up on boot as normal

#### Actual behaviour:

- ... Sod all

#### Extra details:

- ... I noticed this on the last version so restored 6.14 and waited for 6.16 as i could see a few people mentioned it, for some reason this was ignored in 6.16...

**Comment by DasClarky** [comment]
Made a script to restart it, working now on boot

**Comment by Fourdee** [comment]
Reopened for testing.

**Comment by MichaIng** [comment]
Should be related to: https://github.com/Fourdee/DietPi/issues/2075

However I am thinking if workaround should be better placed into boot script instead of pre-boot, in case some devices need other network tasks to be done?

Also I think this is be something to address to Debian Jessie package maintainer. There should be some possibility to start a systemd service before network without causing a dependency loop or the need to override default dependencies (sysinit.target/basic.target).

**Comment by MichaIng** [comment]
@Fourdee 
Whoopsie found an issue in how we applied the fix:
https://github.com/Fourdee/DietPi/blob/b2d16a6febf35da8be53dea17e5bfe3cff5555de/dietpi/preboot#L255-L257

This is inside: `Apply_DietPi_FirstRun_Settings()`
Of course it needs to be done on every boot.
- Also I will open PR to move this to boot instead of pre-boot, after all other possible network steps are finished.
- `killall -w dhclient &> /dev/null` should have no effect, since dhclient is started together with interfaces, but if it had, it would lead to dhclient not starting at all, since we do not handle it inside `dietpi-services`. @Fourdee do you remember the reason for this?

https://github.com/Fourdee/DietPi/blob/b2d16a6febf35da8be53dea17e5bfe3cff5555de/dietpi/preboot#L270-L279
Not sure if this is not needed any more when running after networking service start. But actually I remember that networking start did not always bring up networks, that are not applied via `auto` (instead of `allow-hotplug` in `/etc/network/interfaces`. Will check what ifup does, if the interface is already up, but might be a good failsafe after networking start.

€: Okay PR is up: https://github.com/Fourdee/DietPi/pull/2125
- Cleaned up all network bring up workarounds to be at the end of DietPi-Boot init. So PreBoot will now only check available hardware (create .network), edit /etc/network/interfaces and wpa_supplicant.conf according to dietpi.txt on first run setup.
- networking.service should run afterwards and before DietPi-Boot.
- As of dependency loop, on Jessie, networking.service will be started manually in DietPi-Boot.
- As failsafe, enabled interfaces are brought up again.
- `OPi Zero 2 / Neo Air` seem to require an `ifdown wlan[0-9]` as well, so I merged this workaround, but could be maybe retested.

**Comment by Fourdee** [comment]
Unable to replicate on Odroid XU4 with our v6.14 Stretch image, updated to v6.16.

Regardless the network up during boot check added by @MichaIng, will prevent this from occurring in v6.17 for both Jessie and Stretch.

Marking as completed.
