### ISSUE TITLE
Sickrage fresh install will not start

### ISSUE THREAD

**Issue by mdoary** [MichaIng/DietPi#2126]
#### Required Information:
- DietPi version	1.16
- Distro version	stretch or 9.4
- Kernel version	Linux DietPi 4.14.70-v7+ #1144
- SBC device		RPi 3 Model B (armv7l)
- Power supply used	5V 2.5A
- SDcard used		SanDisk ultra)

#### Additional Information (if applicable):
- Software title	Sickrage
- Was the software title installed freshly or updated/migrated? Have tested both.
- Can this issue be replicated on a fresh installation of DietPi? Yes
- `dietpi-bugreport` ID 49ed237b and 261c817f

#### Steps to reproduce:

1. install latest image 
2. select Sickrage from install software menu 

#### Expected behaviour:

- Should Start with dietpi-service start

#### Actual behaviour:

- Fails to start. 

#### Extra details:

- I am having the same problem on an older setup i was using and create a fresh setup to troubleshoot.

**Comment by MichaIng** [comment]
@mdoary 
Thanks for your report.

We will try to replicate.
_______________
🈴 Verified bug on Stretch VM:
```
[  OK  ] DietPi-Software | Unzipping archive
[  OK  ] DietPi-Software | Cleaning download directory
cp: cannot stat 'SickRage-*/*': No such file or directory
rm: cannot remove 'SickRage-*': No such file or directory
```
- Something about the downloaded archive must have changed.

`drwxr-xr-x 7 root root      520 Oct  9 03:45 SiCKRAGE-master`
- Capitalization of Sickrage repo changed: https://github.com/SiCKRAGE/SiCKRAGE
- Since cases are ignored on web domains/paths, the download does not fail, but the unzipped folder follows repo capitalization.
____________
Fixed for v6.17:
- https://github.com/Fourdee/DietPi/commit/6203b3c908d75497680bee11291dad0344d4abf7
- https://github.com/Fourdee/DietPi/commit/a3009444993f6cf63cbfe83929ede3e0a1293bbc

**Comment by Fourdee** [comment]
@MichaIng 

> Capitalization of Sickrage repo changed: https://github.com/SiCKRAGE/SiCKRAGE

👍 

Been thinking we should rename our repo to DiETPi? 😉 😉 🤣

**Comment by Fourdee** [comment]
Test:
```
 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Configuring SickRage: automatically download TV shows

[ INFO ] DietPi-Software | Configuring SickRage, please wait...
Job for sickrage.service failed because the control process exited with error code.
See "systemctl status sickrage.service" and "journalctl -xe" for details.
[ INFO ] DietPi-Software | Waiting for SickRage to finish 1st run prep, please wait...
...
...
[FAILED] DietPi-Software | Timed-out waiting for SickRage to generate config.ini
cp: cannot stat '/mnt/dietpi_userdata/sickrage/config.ini': No such file or directory
--2018-10-11 02:35:12--  https://dietpi.com/downloads/conf/sickrage_dietpi_config.ini
Resolving dietpi.com (dietpi.com)... 104.27.179.199, 104.27.178.199, 2606:4700:30::681b:b3c7, ...
Connecting to dietpi.com (dietpi.com)|104.27.179.199|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23917 (23K)
Saving to: ‘/mnt/dietpi_userdata/sickrage/config.ini’
```

```SiCKRAGE.py```

```
root@DietPi:~# python /mnt/dietpi_userdata/sickrage/SiCKRAGE.py --datadir=/mnt/dietpi_userdata/sickrage
Traceback (most recent call last):
  File "/mnt/ssd/dietpi_userdata/sickrage/sickrage/__init__.py", line 219, in main
    from sickrage.core import Core
  File "/mnt/ssd/dietpi_userdata/sickrage/sickrage/core/__init__.py", line 35, in <module>
    from apscheduler.schedulers.tornado import TornadoScheduler
ImportError: No module named apscheduler.schedulers.tornado
Failed to import required libs, please run 'pip install --user -U -r /mnt/ssd/dietpi_userdata/sickrage/requirements.txt' from console
```

**Comment by Fourdee** [comment]
Lots of changes needed in our install, due to ```pip install --user -U -r /mnt/ssd/dietpi_userdata/sickrage/requirements.txt```. Install also takes much longer (5min on NanoPC-T4).

Will send commit once testing passed.

And the reason it takes so long to build? Useless ```pip``` does not support multithreading in 2018:
![image](https://user-images.githubusercontent.com/7077026/46777182-8d5d4d00-cd06-11e8-8534-d07e433d193d.png)

---

Registration now required?
![image](https://user-images.githubusercontent.com/7077026/46778555-2478d380-cd0c-11e8-9140-fcc28cae9c39.png)

![image](https://user-images.githubusercontent.com/7077026/46778596-51c58180-cd0c-11e8-9d15-11dcbd24d173.png)

**Comment by Fourdee** [comment]
Re-test:
- Install + setup torrent client + online docs check
- 🈯️ ARMv8
- 🈯️ x86_64

Completed. Resolved for v6.17

**Comment by mdoary** [comment]
What is the workaround until 6.17?

**Comment by Fourdee** [comment]
@mdoary 

> What is the workaround until 6.17?

None currently, due to the vast changes required to install and configure this software. You'll need to wait for v6.17 beta release (ETA few days).

**Comment by ezekini** [comment]
Beware of the problems sickrage is having right now. It may or may not be worth it to maintain this software option in Dietpi.....
https://www.reddit.com/r/sickrage/comments/9ll427/echelon_attempting_hostile_takeover_again/

**Comment by Fourdee** [comment]
@ezekini 

> Beware of the problems sickrage is having right now. It may or may not be worth it to maintain this software option in Dietpi.....

Not our concern or agenda. The software stays and Sonarr is also a choice 😉 😉

**Comment by ezekini** [comment]
Ok... so I updated today to beta v6.17.5 which describes this as fixed in the changelog (great addition to see the changelogs from the terminal), but after trying to install Sickrage, I recieved this error. I don't know if it has to do with a bad previous uninstall (Sorry for the weird format, I couldn't find this error in the logs)

DietPi Error Handler:
 /mnt/dietpi_userdata/sickrage/requirements.txt (line 46)) (2.3.1)
 Requirement already satisfied: enum34; python_version < "3" in
 /usr/lib/python2.7/dist-packages (from
 cryptography>=2.2.1->pyopenssl>=0.12->service_identity==17.0.0->-r
 /mnt/dietpi_userdata/sickrage/requirements.txt (line 46)) (1.1.6)
 Requirement already satisfied: asn1crypto>=0.21.0 in
 /usr/local/lib/python2.7/dist-packages (from
 cryptography>=2.2.1->pyopenssl>=0.12->service_identity==17.0.0->-r
 /mnt/dietpi_userdata/sickrage/requirements.txt (line 46)) (0.24.0)
 pyasn1-modules 0.2.2 has requirement pyasn1<0.5.0,>=0.4.1, but you'll have pyasn1
 0.1.9 which is incompatible.
 Installing collected packages: simplejson, pyasn1-modules, attrs, service-identity,
 psutil
   Found existing installation: simplejson 3.10.0
 Cannot uninstall 'simplejson'. It is a distutils installed project and thus we cannot
 accurately determine which files belong to it which would lead to only a partial
 uninstall.
 You are using pip version 18.0, however version 18.1 is available.
 You should consider upgrading via the 'pip install --upgrade pip' command.

 Unable to continue, DietPi-Software will now terminate.

                Retry         : Re-run the last command that failed
                DietPi-Config : Edit network, APT/NTP mirror settings etc

                        <Ok>                            <Exit>

**Comment by MichaIng** [comment]
@ezekini 
Thanks for your report. Indeed with the repo renaming and a new fork, there is quite some switching going on with this: https://github.com/Fourdee/DietPi/pull/2143

```
Found existing installation: simplejson 3.10.0
Cannot uninstall 'simplejson'. It is a distutils installed project and thus we cannot
accurately determine which files belong to it which would lead to only a partial
uninstall.
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
- Hmm not sure what causes the error (exit code != 0) here. Does it need to uninstall `simplejson`? php upgrade to 18.1 sound more like a suggestion than a requirement. We need to investigate.

**Comment by Fourdee** [comment]
🈯️ Interesting, fresh install on ASUS TB S, working fine + web GUI:
```
root@DietPi:~# systemctl status sickrage.service -l
● sickrage.service - SickRage
   Loaded: loaded (/etc/systemd/system/sickrage.service; disabled; vendor preset
: enabled)
   Active: active (running) since Tue 2018-10-16 10:50:52 BST; 15s ag
o
  Process: 9481 ExecStart=/usr/bin/python /mnt/dietpi_userdata/sickrage/SiCKRAGE
.py -d --nolaunch --datadir=/mnt/dietpi_userdata/sickrage (code=exited, status=0
/SUCCESS)
   CGroup: /system.slice/sickrage.service
           └─9515 /usr/bin/python /mnt/dietpi_userdata/sickrage/SiCKRAGE.py -d -
-nolaunch --datadir=/mnt/dietpi_userdata/sickrage
```

**Comment by Fourdee** [comment]
@ezekini 

Which SBC device are you getting the error on?

> has to do with a bad previous uninstall 

Was this a manual uninstall you did yourself, or through ```dietpi-software```?

---

- 🈯️ Uninstall + reinstall test

**Comment by ezekini** [comment]
Hi @Fourdee. It's an _Odroid C2_. the uninstall/install process was always using `dietpi-software`

**Comment by Fourdee** [comment]
@ezekini 

Thanks, 

Try removing the offending packages:
```
pip uninstall simplejson pyasn1
#Say yes to both
```

Then reinstall SiCKRAGE via ```dietpi-software```, see if it passes.

---

🈯️ Confirmed fresh install on C2 is fine, must be limited to users current system.

**Comment by ezekini** [comment]
pyasn1 went ok, but the other on returned:  `Cannot uninstall 'simplejson'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

**Comment by Fourdee** [comment]
@ezekini 

Feeling the python love 😄 

Ok, will take a look tomorrow:

REF:
- https://github.com/pypa/pip/issues/5247#issuecomment-381550610

More to the point, why is SiCKRAGE (or pip) trying to remove following?
```
Cannot uninstall 'simplejson'. It is a distutils installed project and thus we cannot
accurately determine which files belong to it which would lead to only a partial
uninstall.
```

**Comment by Fourdee** [comment]
@ezekini 

Apologies for the delay. Is this still an issue on your system?

As this issue appears to be limited to your current system, and, i'am unable to replicate to assist our end:
My knowledge of Python is minimal at best, so, to avoid unnecessary time wasted at your end, does the issue still occur on a fresh installation of DietPi using our current Beta with the revised SiCKRAGE install?
https://github.com/Fourdee/DietPi/blob/dev/BRANCH_SYSTEM.md#steps-to-use-the-dietpi-beta-branch

**Comment by ezekini** [comment]
@Fourdee , I am a bit busy this week, but I will try a fresh installation whenever I have an hour or so. Will get to you with the results.

**Comment by Fourdee** [comment]
@ezekini 

Thanks 👍 

As the original issue in this ticket is resolved, i'll mark this as closed.

@ezekini 

When you come to do the test, if issues still reoccur, please open a new ticket on our github page.
