### ISSUE TITLE
Image | Kirkwood (armv5tel) devices

### ISSUE THREAD

**Issue by michelnas** [MichaIng/DietPi#2134]
Hi gents,
what a great Job already has been done by all contributers.
DietPi works excellent on my RasPi 2 device.

I wonder, why it is not possible to install it on my old Zyxel NSA310 NAS (CPU Kirkwood armv5tel).
I already installed Debian 9 (Stretch) successfully following the guide from Bodhi in the  [Doozan-Forum](https://forum.doozan.com/read.php?2,12096).

When I then tried to install DietPi with your installer script, I got the message that DietPi can not be installed on armv5tel devices.

I'm pretty sure that many of these old Kirkwood devices could have a chance of a second life if a DietPi installation would be possible.

Please investigate whether an installation might be possible somehow.

Cheers
Michael

**Comment by MichaIng** [comment]
@michelnas 
Thanks for your request.

The issue is a bid similar to x32 (VM/Native PC) or EFI32 images. The answer given there, generally applies to ARMv5 as well: https://github.com/Fourdee/DietPi/issues/1854#issuecomment-401457209

- Jep, especially for older devices, e.g. x32 or ARMv5, DietPi would be great with it's aim to reduce resource usage.
- But sadly, adding support for a new architecture means much work, especially on `dietpi-software`, as we need to find, check and integrate armv5 download/install candidates for ~170 software titles.
- In case of ARM/SBCs, as well custom kernel/bootloader/firmware is needed, although your linked guide seems to cover this very well.
- So even that we understand the benefit this would be, the amount of users with such legacy devices vs. the development effort turned out loose during our past considerations.
- In case of your special board an additional issue is that we need to be able to create images ourself, so we can guarantee they work and can replicate issues on the same device. For this we would need such a board ourself.
__________________
But I am still thinking, if we could roughly add x32 and armv5 (or simply any arch) support, at least do the minimal changes to our preparation and architecture estimation scripts, but clearly warn users that it is experimental and might not work.
We would at first disable all software installs (we already have the possibility to easily enable/disable installs for certain architectures) and carefully re-enable them step by step, when we can find the right install candidates. Especially for software, where we just use the Debian repo, this is not too hard, since we can easily check the [online database](https://packages.debian.org/de/stretch/) for related packages.

But this would be clearly low priority, since we generally need to concentrate on issues that affect more users 😉.

**Comment by michelnas** [comment]
Hi MichaIng, 
many thanks for your very fast feedback on that topic.
I can completely understand it in terms of supporting "outdated" hardware.
I posted a request of assist at the [Doozan Forum](https://forum.doozan.com/read.php?2,69754).
As I'm just a user (noob) I hope somebody of them can support.

I think that the Kirkwood hardware is strong enough to support most of the DietPi capabilities/opprtunities.

As per my understanding the aim of DietPi is to bring low ressourced hardware working with up-to-date software solutions.
Why not bringing these teams together?

Cheers
Michael

**Comment by MichaIng** [comment]
I mark this issue as closed. ToDo list grows faster then we're currently able to solve/implement with current devices/architecture list. Adding a completely new architecture is hence way out of scope. If someone wants to work with it, I'll assist on pull requests and information, but I'm not gonna start working with this myself :wink:.
