### ISSUE TITLE
Error installing cryptsetup in rock64

### ISSUE THREAD

**Issue by lupa18** [MichaIng/DietPi#2139]
#### Required Information:
- DietPi version	| 6.16
- Distro version	| stretch
- Kernel version	| Linux DietPi 4.4.77-rockchip-ayufan-136 #1 SMP Thu Oct 12 09:14:48 UTC 2017 aarch64 GNU/Linux
- SBC device		| 5V 3A
- Power supply used	| (EG: 5V 1A RAVpower)
- SDcard used		| Class 10 micro SD

#### Additional Information (if applicable):
- Software title	| apt / dpkg
- Can this issue be replicated on a fresh installation of DietPi? yes
- `dietpi-bugreport` f08067cc-5550-4254-968d-09db2bbf6111

#### Steps to reproduce:

1. Try to install cryptsetudp by running: sudo apt install cryptsetup

#### Expected behaviour:

- It should run installation without problems

#### Actual behaviour:

- It throws an error: https://pastebin.com/z5Qc8jcd

**Comment by MichaIng** [comment]
@lupa18 
Thanks for your report.

> E: busybox or busybox-static, version 1:1.22.0-17~ or later, is required but not installed

_( Error does not appear on Jessie or Buster. )_

To fix the issue:
```
apt install busybox
apt install --reinstall cryptsetup
```
🈯️ 
```
root@Test:~# apt-get install --reinstall cryptsetup
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/174 kB of archives.
After this operation, 0 B of additional disk space will be used.
Preconfiguring packages ...
(Reading database ... 16431 files and directories currently installed.)
Preparing to unpack .../cryptsetup_2%3a1.7.3-4_amd64.deb ...
Unpacking cryptsetup (2:1.7.3-4) over (2:1.7.3-4) ...
Setting up cryptsetup (2:1.7.3-4) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for systemd (232-25+deb9u4) ...
Processing triggers for initramfs-tools (0.130) ...
update-initramfs: Generating /boot/initrd.img-4.9.0-8-amd64
```
___________________
Strange that `busybox | busybox-static` is not simply added as package dependency...

On Buster this is the case:
- `cryptsetup` => `cryptsetup-initramfs`: https://packages.debian.org/buster/cryptsetup
- `cryptsetup-initramfs` => `busybox | busybox-static`: https://packages.debian.org/buster/cryptsetup-initramfs

On Stretch it's just a recommendation: https://packages.debian.org/stretch/cryptsetup
- Seems due to `initramfs-tools` being also just a recommendation. Hmm somehow makes sense, but then the APT install script should only attempt to configure `initramfs-tools`, if busybox is available, otherwise throw a warning instead of an error.

On Jessie is seems to be the case: https://packages.debian.org/jessie/cryptsetup
- Also `initramfs-tools` + busybox just recommendations, but APT install does not throw an error.

**Comment by Fourdee** [comment]
@lupa18 

Marking as closed with workaround provided by @MichaIng above.

If issues still persist, please reopen.
