### ISSUE TITLE
MotionEye on Tinkerboard

### ISSUE THREAD

**Issue by ibnbd** [MichaIng/DietPi#2229]
I am not entirely sure why MotionEye doesn't support Tinkerboard. Tinkerboard is a good piece of hardware, can you make official support for MotionEye on it?

Thank You

**Comment by MichaIng** [comment]
@ibnbd 
Thanks for your request.

On official releases there are only x86 and RPi releases available: https://github.com/Motion-Project/motion/releases

At least we can enable for amd64 then. Needs testing if we can get the RPi release work on other ARM devices or can be manually build there.

**Comment by ibnbd** [comment]
@MichaIng thanks for adding to the request.

**Comment by MichaIng** [comment]
Ah on Debian repo it is available for all architectures: https://packages.debian.org/stable/video/motion
On Jessie as well, but the version is outdated.

So generally enable for all devices, only on Jessie for RPi+amd64 user GitHub repo releases, otherwise rely on Debian repo. But needs testing thought all our supported devices and then enabled step by step at best, if succeeding. But yeah we can start with Tinkerboard.

Also when we use Debian repo, no build tools or other dependencies need to be installed manually. So we can decrease install effort.

Currently 245 installs reported (RPi support only currently), so quite something where we could put some effort.

@Fourdee 
What do you think?

**Comment by Fourdee** [comment]
@MichaIng 

Yep 👍  we can enable for all under stretch>, but disable for Jessie.

**Comment by ibnbd** [comment]
@MichaIng @Fourdee that will be amazing, since `TinkerOS v2.0.7` is Debian stretch based. Hopefully this will be available soon. Thank you

**Comment by Fourdee** [comment]
https://github.com/Fourdee/DietPi/commit/5e5410cb25451da14557b4a1f57d2faae73d8df4

Test:
- 🈯️ ARMv7
- 🈯️ ARMv8

Completed. Available for all devices in v6.18.
