### ISSUE TITLE
wordpress not works on fresh install

### ISSUE THREAD

**Issue by msongz** [MichaIng/DietPi#2242]
#### Required Information:
- DietPi version	| `G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=17
G_DIETPI_VERSION_RC=12
G_GITBRANCH=master
G_GITOWNER=Fourdee`
- Distro version	| `stretch` or `9.4`
- Kernel version	| `Linux pi2 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux`
- SBC device		| `RPi 2 Model B (armv7l)`
- Power supply used	| 5V 1A RAVpower
- SDcard used		| SanDisk ultra

#### Additional Information (if applicable):
- Software title	| `wordpress`
- Was the software title installed freshly or updated/migrated? | `freshly`
- Can this issue be replicated on a fresh installation of DietPi? | `yes`
- `dietpi-bugreport` ID

#### Steps to reproduce:

1. install dietpi
2. and install wp from soft-center

#### Expected behaviour:

- ...

#### Actual behaviour:

- "Your PHP installation appears to be missing the MySQL extension which is required by WordPress."

#### Extra details:

- ...

**Comment by msongz** [comment]
`apt-get install php-mysql`
will fix

**Comment by Fourdee** [comment]
@msongz 

Many thanks for the report 👍 

---

Notes:
I was unable to replicate issue with current dev branch. ```php-mysql``` is installed as a pre-req.

**Comment by MichaIng** [comment]
I guess it was due to: https://github.com/Fourdee/DietPi/issues/2217#issuecomment-435599804, fixed with: https://github.com/Fourdee/DietPi/pull/2214/files#diff-d92a6ee04e02fd2a2dc23d5bec3e6a98R3422
- But that occurred only, if PHP was already installed previously with another database (e.g. SQLite) and then MySQL on a separate install run.
- So should not have appeared on a fresh install with selecting Wordpress (+others) all together.

**Comment by msongz** [comment]
Yeah, I installed gitea binary with sqlite set up, not sure it is the reason

**Comment by MichaIng** [comment]
@msongz 
Okay jep that makes sense then. Thanks for feedback, then indeed the issue is solved already.
