### ISSUE TITLE
Dietpi-software is very slow.

### ISSUE THREAD

**Issue by qq24021438** [MichaIng/DietPi#2264]
I find that dietpi-software installs software very slowly, and has been WGet all the time. How to modify the WGet link of the software? Let it be installed faster?

**Comment by MichaIng** [comment]
@qq24021438 
You mean the downloads take long to finish?
Whether it's fast or slow of course depends on the download source and your network speed. DietPi has no influence on this, since it's using the GNU/Linux default methods anyway.

Which software title you mean in particular, any example hat took very long/downloaded very slow?
If you find a faster download mirror in a special case, you could theoretically replace it directly within `/DietPi/dietpi/dietpi-software` (e.g. using nano search function to find the current link).

But note that we usually use the official download sources or GitHub for reason. And in most cases that I touched, I am not aware of a (faster) mirror. It is of course important that the exact same software and version is downloaded and that the source is trustful. I am not keen to add unofficial 3rd party download sources that might in some cases or might not be a bid faster. Especially since we download (wget) and download/install APT pre-reqs in parallel already, there should not be much benefits.

If it's about APT, of course it is another topic and you should search and add a mirror near your location. On the other hand, the default deb.debian.org is a mirror director already that should find a close (fast) mirror automatically in most cases. For more information about Debian APT mirrors: https://www.debian.org/mirror/list

Check as well https://github.com/Fourdee/DietPi/issues/1987 as a theoretical method to speed up APT downloads, but during our tests it was not faster, but significantly **slower** 🤔.

**Comment by MichaIng** [comment]
I will mark this issue as closed. Feel free to reopen or ask further questions, if required.

On case of a certain software title, where a better download link is available, we will check and change in case.
