### ISSUE TITLE
DietPi-Software | Inform users, if we update existing conf.d/dietpi-*.conf files

### ISSUE THREAD

**Issue by studioai** [MichaIng/DietPi#2325]
## Creating a bug report/issue:
I just updated DietPi to 6.19.5 from previous version, then Nginx Reverse proxy stopped working.
other .conf in etc/nginx/seites-deitpi which is not using Reverse proxy works well.

Here's one of my reverse proxy .conf

`location /git/
{
        proxy_pass    http://localhost:3000/;
        proxy_set_header    Host    $host;
        proxy_set_header    X-Real-IP    $remote_addr;
        proxy_set_header    X-Forwarded-Host       $host;
        proxy_set_header    X-Forwarded-Server    $host;
        proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
}
`

Restoring my dietpi backup makes reverse proxy work again, I really wonder what is changed and causing the issue in newest version. 

P.S: @Fourdee I really appreciate for your works!

#### Required Information:
- DietPi version	| 
G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=19
G_DIETPI_VERSION_RC=5
G_GITBRANCH=master
G_GITOWNER=Fourdee

- Distro version	| stretch
- Kernel version	| Linux DietPi 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
- SBC device		| Native PC (x86_64)
- Power supply used	| (EG: 5V 1A RAVpower)
- SDcard used		| (EG: SanDisk ultra)

#### Additional Information (if applicable):
- Software title	| Nginx
- Was the software title installed freshly or updated/migrated?
- Can this issue be replicated on a fresh installation of DietPi?
- `dietpi-bugreport` ID

#### Steps to reproduce:

1. ...
2. ...

#### Expected behaviour:

- ...

#### Actual behaviour:

- ...

#### Extra details:

- ...

**Comment by MichaIng** [comment]
@studioai 
I just checked what we patched with the update. Although we changed some config file names, we did not patch content or something and nothing should affect proxy handling. Only thing I can imagine is that nginx APT package update changed something about the syntax? Do you remember if the nginx package was updated during dietpi-update as well? You can check `cat /var/tmp/dietpi/dietpi-update.log` for this.

But I recognized another issue, perhaps even related to your issue:
- On Nginx we changed our custom sites/config file names inside /etc/nginx/sites-dietpi/ from *.config to *.conf endings, for consistency. But due to back and forth about where these files are placed, I missed to add changing the include directive in `/etc/nginx/sites-available/default` accordingly.
The line at the end need to be `include /etc/nginx/sites-dietpi/*.conf` now instead of `*.config`
- So the configurations from there are not loaded anymore after the patch. Is yours placed there as well?

To fix:
`grep -q 'include /etc/nginx/sites-dietpi/\*\.config;' /etc/nginx/sites-available/default && G_CONFIG_INJECT 'include /etc/nginx/sites-dietpi/\*\.config;' 'include /etc/nginx/sites-dietpi/*.conf;' /etc/nginx/sites-available/default`

@Fourdee 
Damn mistake, my fault. Should have shifted the internal config naming to v6.20 with full beta phase and such, since this was not required for changing the names of those files in `.conf/dps_*`.

Not sure how to handle this best now. Pydio, Nextcloud, ownCloud, rutorrent and some other should be broken (or missing settings/features) on Nginx after v6.19 patch 🤔.
**€: Perhaps doing just a RC version rise (to v6.18.6) on master:**
- This will trigger `dietpi-update` to show update available.
- Then we check, if current version is `v6.18` during pre-patch, apply the Nginx fix and kill the whole update script afterwards from within pre-patch.
- So pre-v6.18 systems will a regular update with patch_file addition as above, only existing v6.18 installs with skip all other update parts. Good that pre-patch is really done before all other steps.
Also included need to be:
  - `echo 0 > /DietPi/dietpi/.update_stage`
  - `sed -i '/G_DIETPI_VERSION_RC=/c\G_DIETPI_VERSION_RC=6' /DietPi/dietpi/.version`

**Comment by studioai** [comment]
@MichaIng 
Thanks for your reply.
I remember there was no nginx update during Dierpi update process for sure.

There's a conflict on config files for pydio because I have redirection config for pydio already and 6.19.5 adds a config for pydio automatically.  So, I just delete my old one. and It works again.

**Comment by MichaIng** [comment]
@studioai 
Thanks for feedback.

Ah jep, we solved all web UI warnings and rewrites (for client access) with last update and triggered reinstall to push those changes to live configs.

It is actually a good point, that if we do such the user should be informed to check if custom configs and our additions conflict or things are doubled/obsolete and such. We already improved the way main config files are handled on reinstall (e.g. backup is done), so they are not simply overwritten together with custom user settings. But our dedicated snippet conf.d/ files are meant to be updated to implement features, resolve bugs, enhance security and such. But of course custom webserver config changes/snippets are done by many users and should be possible without issues 🤔.
Simpelst solution I think is to prompt a user information, if an existing conf.d/ snipped file is updated.
_______
I will reopen and turn this issue into a feature request. Should be no big deal to add the above.

**Comment by Fourdee** [comment]
@MichaIng 

We could try linking the below in changelog:
https://github.com/Fourdee/DietPi/tree/master/.conf

Then users can check version/modified date to see if any files have been replaced/updated.

---

Another option is to add tweak ```Download_Install``` a bit.

**Comment by Fourdee** [comment]
Went with ```G_WHIP_MSG```, if it becomes too "annoying" for end users, we can change to ```G_DIETPI-NOTIFY 2```.

**Comment by Fourdee** [comment]
Yep working fine:
![image](https://user-images.githubusercontent.com/7077026/51080277-5bc29c00-16d0-11e9-8ef9-461fcd201a73.png)


Completed.
