### ISSUE TITLE
Wifi/Tor hotspot/Cuberite install error

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#2340]
Hi, Im using latest dietpi 6.19 on a raspberry pi 3B

I tried to install wifi hotspot and tor hotpot and i get an error saying that some addresses are not trusted 

also i tried to install the Cuberite software and i got the same error about trusted etc.

**Comment by symbios24** [comment]
anyway too many errors i managed to complete the install with the systemctl start systemd-timesyncd 
but after i got another dhcp error and when it was finish the installation the hotspot was not available you need to replicate the install to see the errors

Thanks

**Comment by MichaIng** [comment]
@symbios24 
Thanks for your report and sorry for the late reply.

Since you say there are errors about trusted addresses and starting timesyncd fixed it, I guess it was indeed due to system clock out of sync. Then SSL certificates may be "too new" (not yet valid from system view) to accept.

In this case `dietpi-software` should exit when APT package install (or wget download) returns error, so the install is not finished.

The only thing that make me wonder is, that actually DietPi-Software should actually start time sync forcefully when starting, otherwise will prompt about this failing. I will try to replicate on x86_64 notebook with manually setting old system time.

**Comment by MichaIng** [comment]
I close this due to missing user reply. However feel free to reopen if issue persists.

**Comment by actraiser30** [comment]
hello upon trying to install cuberite on latest dietpi for raspberry pi 4 i noticed that its not in the software section,is Cuberite removed ?

**Comment by Joulinar** [comment]
Hi,

many thanks for your report. It's still there. Software ID 52

```
root@DietPi4:~# dietpi-software list|grep cuberite
id 52 | =0 | cuberite: minecraft server with web interface (c++) | | https://dietpi.com/phpbb/viewtopic.php?p=2068#p2068
root@DietPi4:~#
```

**Comment by actraiser30** [comment]
Strange i dont see it

Στις Κυρ, 19 Απρ 2020, 14:01 ο χρήστης Joulinar <notifications@github.com>
έγραψε:

**Comment by Joulinar** [comment]
Can you post output of following 

`dietpi-software list|grep cuberite`

**Comment by actraiser30** [comment]
It only happens in Rpi4 in Rpi 2-3 its visible in 4 its not

Στις Κυρ, 19 Απρ 2020, 16:34 ο χρήστης Joulinar <notifications@github.com>
έγραψε:

**Comment by Joulinar** [comment]
pls post output of the following to this GitHub post

`dietpi-software list|grep cuberite`
