### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by pmwals09** [MichaIng/DietPi#2354]
#### Details:
- Date           | Fri 14 Dec 22:11:07 GMT 2018
- Bug report     | N/A
- DietPi version | v6.16
- Img creator    | n/a
- Pre-image      | n/a
- SBC device     | RPi 3 Model B (armv7l) (index=3)
- Kernel version | #1159 SMP Sun Nov 4 17:50:20 GMT 2018
- Distro         | stretch (index=4)
- Command        | G_AGUG
- Exit code      | 100
- Software title | DietPi-Update

#### Steps to reproduce:

1. Attempt to run sudo dietpi-update

#### Expected behaviour:

- The update happens

#### Actual behaviour:

- I am instructed to run sudo dpkg --configure -a
- dpkg --configure -a hangs up at:
Setting up mono-roslyn (5.16.0.220-0xamarin4+raspbian9b1) ...
Mono precompiling /usr/lib/mono/4.5/csc.exe for arm...
Mono precompiling /usr/lib/mono/4.5/vbc.exe for arm...
Mono precompiling /usr/lib/mono/4.5/VBCSCompiler.exe for arm...
Mono precompiling /usr/lib/mono/4.5/Microsoft.CodeAnalysis.CSharp.dll for arm...

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
```

**Comment by Fourdee** [comment]
@pmwals09 

Hi,

Could be hardware related issue, however, please try reinstalling mono:
```
G_AGP mono-roslyn mono-complete mono-devel mono-runtime libmono-cil-dev
G_AGA
dietpi-software reinstall 150
```

**Comment by Methroix** [comment]
I'm facing the same issue.
To add to that, I was unable to reinstall mono since it wasn't installed in the first place.
When trying to install it using dietpi-software, I got pretty much the same result as when trying to run dietpi-update.

#### Details:
- Date           | Thu  3 Jan 10:19:12 CET 2019
- Bug report     | N/A
- DietPi version | v6.18.14 (Fourdee/master)
- Img creator    | n/a
- Pre-image      | n/a
- SBC device     | Sparky SBC (armv7l) (index=70)
- Kernel version | #22 SMP PREEMPT Fri Dec 22 10:45:41 IST 2017
- Distro         | stretch (index=4)
- Command        | G_AGUG
- Exit code      | 100
- Software title | DietPi-Software

#### Steps to reproduce:

1. Install the Mono libraries, either by running `dietpi-software install 150` or through the dietpi-software GUI.

#### Expected behaviour:

- Mono libraries should be installed.

#### Actual behaviour:

- dietpi throws an error, telling me that dpkg was interrupted.

#### Extra details:

- Running `dpkg --configure -a`, as instructed, from SSH results in a session timeout at the following point:
```Setting up mono-roslyn (5.16.0.220-0xamarin4+raspbian9b1) ...
Mono precompiling /usr/lib/mono/4.5/csc.exe for arm...
Mono precompiling /usr/lib/mono/4.5/vbc.exe for arm...
Mono precompiling /usr/lib/mono/4.5/VBCSCompiler.exe for arm...
Mono precompiling /usr/lib/mono/4.5/Microsoft.CodeAnalysis.CSharp.dll for arm...
```
- Running `dpkg --configure -a` directly in the console causes the unit to reboot. After the reboot the problem still persists. This may indicate that a reboot may be the reason behind the SSH disconnect as well.

#### Additional logs:
```
Log file contents:
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
```

**Comment by Methroix** [comment]
@pmwals09 
Possible solution or at least workaround (requires root privileges):
1. (Optional) Remove any files in `/var/lib/dpkg/updates`.
This is where I started, but I don't know if it is required and I take no responsibility for any issues this may cause.
Use the command `rm` followed by the file name(s).
2. Run `apt-get update`.
3. Run `apt-get upgrade`.
This may take a long time to complete and a reboot may be required.
4. Run `dietpi-update`.
It should now be able to complete without issues.

**Comment by Fourdee** [comment]
@Methroix 


Thanks for the report, might be an issue due to lack of memory. Whats the swapfile size set to?
```
/DietPi/dietpi/func/dietpi-set_dphys-swapfile
```

**Comment by MichaIng** [comment]
Will mark as closed due to missing reply and as general cleanup. Feel free to reopen if issue persists.
