### ISSUE TITLE
DietPi-Software | WiFi Connect

### ISSUE THREAD

**Issue by tillcash** [MichaIng/DietPi#2370]
Creating a software request:

Give us some formal software information:
- Software title | WiFi Connect
- Short description | Easy WiFi setup for Linux devices from your mobile phone or laptop
- GitHub URL (if available) | https://github.com/balena-io/wifi-connect
- (Official) install documentation | https://github.com/balena-io/wifi-connect#installation

**Comment by MichaIng** [comment]
@tillcash 
Thanks for your request.

This might not be too easy to implement, since it most likely breaks DietPi's own WiFi setup/settings scheme. So it would need as well implementation and handling within DietPi-Config/WiFiDB.

But we'll have a look, perhaps we can also learn from their WiFi integration.
