### ISSUE TITLE
DietPi-Software | Testing Kodi 18 (Leia)

### ISSUE THREAD

**Issue by Oeil2L** [MichaIng/DietPi#2371]
Hello

I use Dietpi with Jdownloader (Manual install), Pihole, Plex and Kodi (V17) and everything works perfectly.

If someone can help to install kodi Leia release (V18), i appreciate.

I'm not sure package exist: 
https://tracker.debian.org/pkg/kodi

**Comment by MichaIng** [comment]
@Oeil2L 
It should be available in Debian Buster (testing) repo soon, but I don't believe it is backported to Stretch.

If you really want to go with Leia (still in RC), you need to build it manually: https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md

Note that you **don't** need to install/use "`git` (--clone)" at all to get the code. You can simply download the latest archive manually and extract it:
- https://github.com/xbmc/xbmc/releases
- `Git` just makes it easier to update the source code, switch between branches, update you install via fresh build and such. Perhaps, if you want to stay with Leia and keep it up-to-date, this is the better solution then. As a first try, if `Git` is not yet installed, I would go with downloading the archive manually.

Note that, if you already installed Kodi via `DietPi-Software` or APT before, you might end up with two instances:
- APT packages (which is what DietPi-Software uses as well) install software usually to e.g. `/usr/lib/kodi` and `/usr/bin/kodi`
- If you install from a manual build, it is usually installed to e.g. `/usr/local/lib/kodi` and `/usr/local/bin/kodi`
- The latter overrides the first, if present. The good thing about it is, that you can easily revert to use the APT version, if Leia causes issues. And you will notice, if the APT version get updates, too.

**Comment by Oeil2L** [comment]
Hello MichaIng

Thx for your support. I tryied but compile for me was too complex (a lot of error message)

I applied this method:
https://www.raspberrypi.org/forums/viewtopic.php?f=35&t=222954
But kodi V18 is RC1 only version and i can't find a way to work with the Netflix Addon.

Continuing digging.

**Comment by MichaIng** [comment]
@Oeil2L 
Great link, having an up-to-date testing repo is of course easier.

I just checked what we do on Kodi install:
- Install `libnfs8` and `libcec4` for NFS and CEC support
- Apply some udev rules: [/etc/udev/rules.d/99-dietpi-kodi.rules](https://github.com/Fourdee/DietPi/blob/dev/.conf/dps_31/99-dietpi-kodi.rules), although this should not even be required, if we run it as root (below)
- Make Kodi run as root: `sed -i '/USER=/c\USER=root' /etc/default/kodi`

~But since the (only?) issue you currently face is the Netflix addon, I guess it is expected that not all 3rd party addons have support for new versions before they are officially released. Perhaps you check some release notes or discussions about Leia support of the Netflix addon.~
_______________
> Kodi is now on the way to beta 3 version 18, so the final/stable release should not take much longer. Despite the interface (Estuary skin) didn't change much, there are many improvements in video playback (h265, support for 10bit videos, etc), **support for Netflix** and Amazon Prime, better joystick/gamepad support, and the new RetroPlayer, which will allow you to play games inside Kodi. Everything now also seems a little bit faster. 
- Hmm already Beta3 should support Netflix? 🤔 
- Okay reading comments, seems it was broken in between and fixed again.
_______________
Hmm the repo actually seems not up-to-date: http://pipplware.pplware.pt/pipplware/dists/unstable/main/binary/Packages
- Kodi package is on Beta3 from `2018-09-17` ?? How did you update to RC1? Is there an internal updater or such?

**Comment by Oeil2L** [comment]
@MichaIng

I know but before I post, I reinstall my backup to be sure and apply only the commands indicated in https://www.raspberrypi.org/forums/viewtopic.php?f=35&t=222954 
and the Dietpi Kodi version was updated to RC1 git N°xxxx, but the Add-on:InputStream Adaptive was not present.

(In my initial tests, I try a lot of tuto and this last link, but the install of kodi was dirty (same RC1 but AddOn inputStream Adaptative was present and Netflix not working)

**Comment by MichaIng** [comment]
@Oeil2L 
Note sure how RC1 is installed then, perhaps some internal mechanism, however since DietPi does no related changes to the default APT install, I guess the Netflix app issue is outside of DietPi, but part of the custom repo package, which is not up-to-date (as RC3 is upstream). And users already commented in the link about issues and changes with Netflix API.

However one thing you could check is:
```
find / -name *.ucf*
find / -name *.dpkg*
```
- Check if there are Kodi related `.ucf-dist` or `.dpkg-new` suffixed files, since on DietPi new configuration files are silently ignored to preserve custom settings.
- Since Kodi v18 is a new major version, it might be possible that settings/systemd unit scheme has changed, so that the old one might cause issue.

**Comment by MichaIng** [comment]
@Oeil2L 
Another question: Does Kodi v18 play H.265 natively, could you test this?

**Comment by Oeil2L** [comment]
For sure the Netflix issue is outside of Dietpi (for the moment;) ), i'll see with a more recent version RC3/RC4 or V18.0 later on DietPi.

Netflix work perfectly on libreelec/Kodi RC3.

Kodi support H265 without problem only some limites can appear on Raspberry because the bitrat or Profiles compression:
https://kodi.wiki/view/Features_and_supported_formats

I use Kodi on Mecool M8S (android box tv) for high bitrate.

**Comment by Fourdee** [comment]
Will mark this as closed:
- Kodi 18 will be available in Debian Buster

**Comment by msdos** [comment]
Following https://dietpi.com/phpbb/viewtopic.php?f=9&t=5632, in my RPi 3 with Raspbian GNU/Linux 9 was indeed shown a new option for Kodi 18. I followed the instructions in https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux to upgrade:

```bash
sudo apt-get update
sudo apt-get upgrade
```

And it worked without major problems. Kodi itself migrated the database from 17->18 after restarting.

After the update, I could execute H265 files.

**Comment by MichaIng** [comment]
@msdos 
Thanks for testing, that is great news.

**Comment by msdos** [comment]
Can I run some command to be *exactly sure* that everything is fine about this?  I have decode_MPG2 and decode_WVC1 licenses. I don't wat to give false flags.

**Comment by MichaIng** [comment]
@msdos 
Finally we never know exactly if all features run well on all devices (and distro versions) with the new Kodi but if it is working for you at least our startup wrappers are still valid.

Since our install script does otherwise not contain any magic configuration steps, I think we can skip throughout testing and instead fix found issues on demand (or forward to the Kodi devs).
Also Kodi 18 release will still not be shipped with Debian Stretch, currently not even with Debian Buster.

What might be a later plan is to install Kodi 18 on non-RPi devices from 3rd party source or own compilation. Then of course a larger testing session would be required.
