### ISSUE TITLE
RPi-Monitor as optional remote monitoring tool

### ISSUE THREAD

**Issue by WolfganP** [MichaIng/DietPi#238]
Based on this article http://www.cnx-software.com/2016/03/17/rpi-monitor-is-a-web-based-remote-monitor-for-arm-development-boards-such-as-raspberry-pi-and-orange-pi/ , I found this project (https://github.com/XavierBerger/RPi-Monitor) may be interesting for integration to DietPi (as Raspcontrol was removed due to lack of project maintenance)

**Comment by Fourdee** [comment]
@WolfganP 
Great find on this :+1: . Slick UI and great stats, love it.

Available in next release (v113) as a DietPi optimized installation for RPi (Jessie):
![untitled](https://cloud.githubusercontent.com/assets/7077026/13884662/e3964aae-ed26-11e5-9e80-696d2211e055.png)

**Comment by WolfganP** [comment]
Glad to help improving the distribution. Thanks for the quick integration!

**Comment by k-plan** [comment]
@Fourdee 

> Available in next release (v113) as a DietPi optimized installation for RPi (Jessie):

Used it for long time on my RPis, it's a great piece of software. Can also run on oDroid C1 / C2 with some modifications in `/etc/rpimonitor/template/` :

_(edit: 2nd new picture)_
![160320-0007](https://cloud.githubusercontent.com/assets/17237601/13905774/ad66d8fa-eec9-11e5-8c24-841634ef4ade.gif)

:) Like it. And the Debian packaging is handy.

It's a pity, but XavierBerger is not working on it at the moment.  (https://github.com/XavierBerger/RPi-Monitor/issues/143#issuecomment-177316826) 
http://rpi-experiences.blogspot.fr/

_edit:_
~~_If RPi only is in fokus, https://pi-control.de/ can also be a option. But he also come not to terms with his Version 2.0 (current: [Pi Control 1.3.3](http://willy-tech.de/pi-control-1-3-3/))_~~
_It's work on oDroid C1 / C2 too, but interface is only German (at the moment)_
![160319-0001](https://cloud.githubusercontent.com/assets/17237601/13900776/7d0e8c04-ee0e-11e5-933d-b565db921e97.gif)

**Comment by k-plan** [comment]
@Fourdee 
notice, that you will  integrate it in v.113. Verry nice.
https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L1826

Is there a reason, why you use `rpimonitor_2.9.1-1_all.deb` and not current [rpimonitor_2.10-1_all.deb](https://github.com/XavierBerger/RPi-Monitor-deb/blob/master/packages/rpimonitor_2.10-1_all.deb) ?

https://github.com/XavierBerger/RPi-Monitor-deb/blob/master/debian/changelog
http://rpi-experiences.blogspot.fr/2015/01/rpi-monitor-version-210-is-available.html

**Comment by Fourdee** [comment]
@k-plan 
Yep, I didnt see the 2.10 in the middle lol: https://github.com/XavierBerger/RPi-Monitor-deb/tree/master/packages

I'll update the install to 2.10. :+1:  good spot.

**Comment by k-plan** [comment]
@Fourdee 
have playing around (quick and very dirty) with some lines in  `/etc/rpimonitor/template/...` and it is really amazing on Odroid C1/C2. Not only on RPis as the name implies. 
Have updated the picture in posting above. We would be pleased to receive "_DietPi-Monitor-for-oDroid_" :smiley:

**Comment by Fourdee** [comment]
@k-plan 

> have playing around (quick and very dirty) with some lines in /etc/rpimonitor/template/... and it is really amazing on Odroid C1/C2. Not only on RPis as the name implies. 

Very nice, love the DietPi version number in there :+1:  :)

**Comment by Fourdee** [comment]
Note to self: Add usage details to dietpi.com/software

**Comment by Fourdee** [comment]
http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=5&start=50#p1503

Available in v113

**Comment by k-plan** [comment]
@Fourdee 

> Available in v113

For now, it is only for all the RPi?
Is it possible, you missed to integrated  RPi-Monitor in `dietpi-software`  for Odroid C1/C2?
Can`t find it after update to v113 on C1/ C2 .... :weary:

BTW: 

```
root@Odroid-C2:~# cat /DietPi/dietpi.txt
...
AUTO_DietpiSoftware_Install_RASPCONTROL=0
....
```

:flushed: ... but no big deal.

**Comment by Fourdee** [comment]
@k-plan 
Only available for RPi at the moment on DietPi.

I know you modified the code for Odroid c2, but did it work before your changes? If so I can test all devices with RPi monitor and enable them for next release.

If your modified code is required for non-rpi devices, we would need to apply your modified code to those installations and test the following devices:

```
XU4
C1
C2
OrangePi
VM x64
```

> AUTO_DietpiSoftware_Install_RASPCONTROL=0

Yep, its in there for the RPi Wheezy image. Users are still downloading/install it.

Completely off-topic:
I found this emote and couldn't resist :gb: :)

**Comment by k-plan** [comment]
@Fourdee 

> ... but did it work before your changes?

Yes run "out-of-the-box" on my C1+/C2

```
root@Odroid-C2:~#  wget https://github.com/XavierBerger/RPi-Monitor-deb/raw/master/packages/rpimonitor_2.10-1_all.deb

root@Odroid-C2:~#   dpkg -i rpimonitor_2.10-1_all.deb

root@Odroid-C2:~#  apt-get -f  install
```

et voilà - not perfect (_Voltage, Firmware, only cpu0 in focus_) but fundamental content:

![160321-0002](https://cloud.githubusercontent.com/assets/17237601/13908403/28941690-ef02-11e5-94d2-8c472e6cb6de.gif)

With a little fine tuning in templates it can be handsome.

> XU4
> ~~C1~~
> ~~C2~~
> OrangePi
> VM x64

Sorry, only own a old iMac (late 2007), a few RPi and a [CubieTruck](http://cubieboard.org/tag/cubietruck/).
Don't  believe, it's a great help.
But I can send you the dirty hacked templates for C2, don't know, it's okay for XavierBerger,

> > AUTO_DietpiSoftware_Install_RASPCONTROL=0
> 
> Yep, its in there for the RPi Wheezy image. Users are still downloading/install it.

Yes, add up :+1:  Wheezy is not on my focus for some time ...
:de: :)

**Comment by k-plan** [comment]
Hi,
RPi-Monitor: Version 2.11 Beta is ready for test: [please read this before](http://rpi-experiences.blogspot.de/2015/06/rpi-monitor-version-211-beta-is-ready.html#more)

```
root@Odroid-C1:~#  wget https://github.com/XavierBerger/RPi-Monitor-deb/blob/devel/repo/rpimonitor_2.11-beta7_all.deb
```

My Test result:
![rpi-mon-beta](https://cloud.githubusercontent.com/assets/17237601/14117987/a03c499c-f5e7-11e5-917e-5cdb58506b0e.gif)

Same new and really cool features and nice layout.

**Comment by Fourdee** [comment]
@k-plan 
Looks great :+1: , does this version support the Odroid straight off the bat? Or did you modify the code for this?

**Comment by WolfganP** [comment]
It would be wonderful if anyone with knowledge of RPi-Monitor plugins can add one for proper RasPi shutdown (so headless systems can be completely controlled via web browsers), and add it to DietPi packages.

**Comment by k-plan** [comment]
@Fourdee 

> does this version support the Odroid straight off the bat? Or did you modify the code for this?

Yes, like before. Run out-of-the-box. No code modding, only copy my old Odroid templates, to get some more supported infos and 4 CPUs. But it's easy, otherwise I was not able to do it.
You will doubtless do this better, as I ever will can.

@WolfganP 

> It would be wonderful if anyone with knowledge of RPi-Monitor plugins can add one for proper RasPi shutdown (so headless systems can be completely controlled via web browsers),

Hmm, it's a problem with privilege of web services. There are no "plugins" in the broadest sense. But RPi Monitor will be able to start other programs, like [Shell In A Box](http://www.tecmint.com/shell-in-a-box-a-web-based-ssh-terminal-to-access-remote-linux-servers/). So you will be able, to execute `reboot` or `poweroff` and more in your browser.

![160330-0001](https://cloud.githubusercontent.com/assets/17237601/14137280/7ae73c58-f667-11e5-8871-c3b823f70e26.gif)

![siab](https://cloud.githubusercontent.com/assets/17237601/14153430/0d69b8c6-f6b8-11e5-842e-6f97abb01d15.gif)

---

Oder, wenn du ein wenig :de:  lesen kannst, wäre das oben angeführte [Pi Control](https://willy-tech.de/pi-control/) die einfachere (u. sichere) Alternative. OpenSSH u. einen Webserver mit PHP über `dietpi-software` installieren, dann den Rest wie auf der Seite erklärt. Installation ist sehr einfach:

![pic-install](https://cloud.githubusercontent.com/assets/17237601/14151540/a77982ac-f6ae-11e5-86e9-41672a987fbc.gif)

![pic-install2](https://cloud.githubusercontent.com/assets/17237601/14151554/c2b49e4e-f6ae-11e5-96de-fdcb15533136.gif)

Fehlt etwas, wird danach gefragt und erklärt, was man tuen soll: 
![pic-install3](https://cloud.githubusercontent.com/assets/17237601/14151547/b88f1c5a-f6ae-11e5-80a2-f6c3c1ecb59a.gif)

Bei der Installation muss man seinen root Account mit Passwort angeben:

![pic-install4](https://cloud.githubusercontent.com/assets/17237601/14151566/e0d09edc-f6ae-11e5-9f6c-e0bd5a4e93c0.gif)

 Dann ist es auch möglich, Systemeinstellungen über das Webinterface zu ändern, das System zu rebooten oder auszuschalten. Ebenfalls mit der verfügbaren Android App. 

![pic](https://cloud.githubusercontent.com/assets/17237601/14151595/05b8ad84-f6af-11e5-9d09-955aa260d4b4.gif)

Statistiken und Plugins gibt es auch:

![pic-stat](https://cloud.githubusercontent.com/assets/17237601/14151623/1be2a75e-f6af-11e5-9f6b-f2545282d568.gif)

:gb:
_edit: Reboot and Poweroff tested on both possible solutions. It works!_

 Support the Odroid straight off the bat (out-of-theBox!). Without any modding. :smile: 

![pic-](https://cloud.githubusercontent.com/assets/17237601/14151959/ebc12d64-f6b0-11e5-88c7-de9751ecd757.gif)

**Comment by WolfganP** [comment]
FYI, RPI_Monitor releases v2.11 into production https://github.com/XavierBerger/RPi-Monitor/releases/tag/v2.11

**Comment by Fourdee** [comment]
@WolfganP 
Thanks for letting us know.

DietPi v130 will install 2.11, although, it appears to break Rich's USB drive additions: https://github.com/Fourdee/DietPi/issues/410

![image](https://cloud.githubusercontent.com/assets/7077026/17863621/3736f6c2-6892-11e6-93c8-36b0f7307e05.png)
