### ISSUE TITLE
DietPi-Software | Nextcloud: Install broken with Apache webserver

### ISSUE THREAD

**Issue by Stefan3v** [MichaIng/DietPi#2383]
#### Details:
- Date           | Mon 31 Dec 21:50:48 GMT 2018
- Bug report     | N/A
- DietPi version | v6.19.7 (Fourdee/master)
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 3 Model B (armv7l) (index=3)
- Kernel version | #1159 SMP Sun Nov 4 17:50:20 GMT 2018
- Distro         | stretch (index=4)
- Command        | cp -f /DietPi/dietpi/conf/apache.nextcloud.conf /etc/apache2/sites-available/dietpi-nextcloud.conf
- Exit code      | 1
- Software title | DietPi-Software

#### Steps to reproduce:
1. Install LAMP from diet-software - ok
2. Install phpmyadmin from diet-software - ok
3. Try install NextCloud from diet-software - nok

#### Expected behaviour:

- I want to install Nextcloud

#### Actual behaviour:

- [FAILED] DietPi-Software | Unable to continue, DietPi-Software will now terminate.

Log file contents:
cp: cannot stat '/DietPi/dietpi/conf/apache.nextcloud.conf': No such file or directory
```

**Comment by MichaIng** [comment]
@Stefan3v 
Many thanks for your report.

Jep we forgot to apply our new config download system to this very single case: Nextcloud Apache config.

Fixed with: https://github.com/Fourdee/DietPi/commit/d61ec6cf4ad06ec529dff7a2180e305fbd7fc65a

To fix this in your case, run the following command:
`sed -i 's|G_RUN_CMD cp -f /DietPi/dietpi/conf/apache.nextcloud.conf|dps_index=$software_id Download_Install "apache.nextcloud.conf"|' /DietPi/dietpi/dietpi-software`

Changelog entry: https://github.com/Fourdee/DietPi/commit/f326547dd662f234736a2e63bd9cb59b5c960b25

**Comment by MichaIng** [comment]
@Stefan3v 
If you followed followed the above command to fix Nextcloud install, there was one thing I forgot - The downloaded Apache config needs to be enabled as well:
```
a2ensite dietpi-nextcloud
systemctl reload apache2
```
