### ISSUE TITLE
DietPi-Autostart | Auto login prompts for password

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#2404]
> https://github.com/Fourdee/DietPi/issues/2352#issuecomment-452883078

Something has changed in SystemD?

**Comment by MichaIng** [comment]
@Fourdee 
~Perhaps due to changed boot script order?~

Ah wait, nope above should be not related, but I just recognized, if not mistaken, that we do not enable lightdm service on choice: https://github.com/Fourdee/DietPi/blob/dev/dietpi/dietpi-autostart
But this is already for longer 🤔.
_________
~**EDIT: Hmm or might it be an issue, if postboot runs after autostart executes? In case of auto login this should be possible and more likely, due to new systemd unit order. Perhaps DietPi-Autostart needs to wait for postboot to finish if not console login (ID 0) chosen?**~
_____
**EDITEDIT: Ah lol the systemd unit order changes are not yet live in v6.19, so there is even a tiny chance, that it resolves the issue.**

**Comment by MichaIng** [comment]
Should be retested now with v6.20, as we did some systemd reorder which might have resolved the issue.

**Comment by arrudagates** [comment]
same problem here, but on custom.sh

**Comment by MichaIng** [comment]
@arrudagates 
<s>Verify that you actually don't need to login and only the prompt shows up. You should be able to run commands etc.

I will provide some command step later to hide those login prompt in auto login case, until we found a nice solution with v6.22.</s>

Ah sorry, you use custom.sh, then login prompt is expected and login to console required.

So what is your actual issue with it?

**Comment by MichaIng** [comment]
- Login prompt will only be shown, if no autologin mode has been selected: https://github.com/MichaIng/DietPi/commit/98ffdf96ba1f8059d101b0f8f580d73a444086f0#diff-93b9c3871f032c905ec8b4505d408ca9
- An issue where custom.sh caused a dependency/order loop with postboot and/or other idle and/or multi-user.target has been fixed.

I mark this as closed.
