### ISSUE TITLE
DietPi-Software | Nextcloud: Error during Install

### ISSUE THREAD

**Issue by Gill-Bates** [MichaIng/DietPi#2433]
Setup of Nextcloud stuck during Installation:
![unbenannt](https://user-images.githubusercontent.com/25774289/51496994-0b2efb00-1dc2-11e9-8811-7f0ec56f2e0d.PNG)
   
 │ DietPi-Software: cp -f /DietPi/dietpi/conf/apache.nextcloud.conf
             │ /etc/apache2/sites-available/dietpi-nextcloud.conf
             │  - Exit code: 1
             │  - DietPi version: v6.19.7 (Fourdee/master) | HW_MODEL:3 | HW_ARCH:2 | DISTRO:4
             │  - Image creator: DietPi Core Team
             │  - Pre-image: Raspbian Lite
             │
             │ Log file contents:
             │ cp: cannot stat '/DietPi/dietpi/conf/apache.nextcloud.conf': No such file or directory
             │
             │
             │
             │ Unable to continue, DietPi-Software will now terminate.
             │                                                                                        ▒
             │                Retry         : Re-run the last command that failed                     ↓
             │                DietPi-Config : Edit network, APT/NTP mirror settings etc

**Comment by MichaIng** [comment]
@WTFMaster 
Thanks for your report.

Jep it is a known issue with v6.19 and resolved with v6.20 (Beta).

Please see how to apply the fix now: https://github.com/Fourdee/DietPi/issues/2383#issuecomment-450968409

**Comment by Gill-Bates** [comment]
Awesome!

I would really appreachiate, when the php.ini will be optimized by the Installer regarding to the recommended settings of Nextcloud

opcache.enable=1
opcache.enable_cli=1
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.memory_consumption=128
opcache.save_comments=1
opcache.revalidate_freq=1

memory_limit = 512M

**Comment by MichaIng** [comment]
@WTFMaster 
This is (should be) already the case. We add the settings to `/etc/php/7.0/mods-available/opcache.ini`, which is a bid more elegant than in `php.ini` directly, since the settings are switched on/off together with the OPcache module. By this the php.ini can be updated to new defaults via APT automatically e.g. so drop-in configs should be generally preferred on Linux.

`opcache.memory_consumption` is not added there, mainly as a concern that on 256M devices, PHP could eat up too much memory, although only theoretically. It is added instead via the Nextcloud Apache config (that failed to copy on install 😉), applied to /var/www/nextcloud only, to at least not allow other web applications to eat that much.

The `memory_limit` is indeed not touched, so at 128M default value on fresh install. However this is for a single script only, and there is really no chance that any Nextcloud script eats that much, if not you are doing something seriously wrong 😉.
_____________
Final question:
- Does your admin panel show any warning about OPcache or something else?

**Comment by Gill-Bates** [comment]
![unbenannt](https://user-images.githubusercontent.com/25774289/51563095-bce62e80-1e8b-11e9-9151-c7e6d39203eb.PNG)
Since I have increased the RAM in php.ini from 128M (default) to the required 512 M, one error message disappeared

**Comment by MichaIng** [comment]
@WTFMaster 
Will try to replicate.
____________
The `imagick` warning should be ignored. This is not required, just enables the create previews for some very rare image formats, used by the Theming app and disappears, if you disable theming.
There is even some discussion about that on Nextcloud forum, that imagick is an outdated app that implies some security holes, so should be really not enabled, as long as you don't explicitly require an implied feature.
______________
PHP7.0 warning is known, we are thinking about how to solve this on Debian Stretch, which natively ships PHP7.0 only: https://github.com/Fourdee/DietPi/issues/2367
__________
The `memory_limit` value is actually served by Nextclouds own `.htaccess` file...
___________


Ahh, I know what went wrong, respectively I forgot:
```
a2ensite dietpi-nextcloud
systemctl reload apache2
```

**Comment by MichaIng** [comment]
@WTFMaster 
Are the OPcache warnings resolved with the two commands above?

**Comment by MichaIng** [comment]
Mark as closed, since initial error is solved and second only replicable with Lighttpd + HTTPS enabled: https://github.com/Fourdee/DietPi/issues/2489
