### ISSUE TITLE
DietPi-Software | Updated Redis server to use latest version (from source)

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#244]
Apt-get install is out of date. Also required for EmonPi: https://github.com/Fourdee/DietPi/issues/210#issuecomment-198791478

**Comment by Fourdee** [comment]
Was not required for our current EmonPi installation. 
Will look at this in the future when work starts on:
https://github.com/Fourdee/DietPi/issues/257
https://github.com/Fourdee/DietPi/issues/256

**Comment by MichaIng** [comment]
As I was going through the old opened issues:

Did there still appear cases where an update of redis-server (and/or php(5)-redis) is necessary? Otherwise could be closed, especially since stretch will be hopefully soon released with new redis repo version.

In case, I don't like installation from source, since dependencies and updating need to be done manually/maintained by dietpi updates. So someone would need to regularly have an eye on possible updates of this software. Only advantage ist that possible bugs/incompatibilities can be securely tested before shipping the new version via dietpi-update.

As an alternative, if necessary/desired we could use backports from the official debian repo: https://packages.debian.org/de/stretch-backports/redis-server
As far as I tested with raspbian jessie that day, it worked quite stable for several things and of course the first used backport should be tested carefully on all systems.

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
