### ISSUE TITLE
DietPi-Software | Netdata: Now available in Debian Buster and Stretch backports repo

### ISSUE THREAD

**Issue by cmonty14** [MichaIng/DietPi#2446]
Hi,
according to this issue #1494 the netdata binary matches the APT install in Stretch Backport, and the latest release there is: Paket: netdata (1.11.1+dfsg-2~bpo9+1)

Could you please update your binary version accordingly?

THX

**Comment by MichaIng** [comment]
@74cmonty 
Thanks for the info. Nice to finally have netdata in Debian Buster and even Stretch backports.

Our binaries/packages are own source builds and v1.11.1 as well. Having the same version now in Stretch backports indeed allows us to switch to APT repo, if no downsides found. But I think we will stay with our packages, as long as we support Jessie, as they allow v1.11.1 on Jessie as well, so use them on all distro versions for simplicity.

**Comment by MichaIng** [comment]
Had another look on this:
- I was not looking too carefully at first. So the Debian packages were available already a longer time.

@Fourdee 
Was there a special reason to go with own binaries? Okay Jessie support is definitely one!

Also:
- The Stretch backports version installs Python3: https://packages.debian.org/stretch-backports/netdata
Our install does not do/require that, instead installs Node.js, which is only a recommendation on Stretch backports.
- On Buster this has changed: https://packages.debian.org/buster/netdata
Python3 requirement has moved into an own package as recommendation.
- Not sure what they are used for. The web frontend obviously does not require any of them, which is what I first thought Node.js is required for.

What might be indeed enhanced is that the internal updater is presented but does not work, as we don't install Git (reduces requirements).
I guess during compilation this can be disabled via option, since most likely the Debian repo version does not show the updater, since it as well does not install Git and should be updated via APT instead.

So either we go with APT packages, or we install Git as well, allowing internal updates, or disable the updater on compile time, which then requires `dietpi-software reinstall` to update netdata.

#### EDIT
What Python and Node.js is required for: https://docs.netdata.cloud/packaging/installer/#install-netdata-on-linux-manually
Indeed optional and external plugins only. We could even drop Node.js install in our case, leave this up to end user, if required, info via online docs.

**Comment by MichaIng** [comment]
Had another look. Now on Debian stretch-backports v1.12 is available.

On Stretch systems, since we do not hold the package, APT offers and applies the update anyway. It places the default netdata.conf which blocks access to web UI from other than localhost/loopback. This is not bad as default, but should be documented in our online docs.

Furthermore to not mess with custom binaries, and since the APT package works very well on dietpi.com server, we should now only install our custom binaries on RPi Stretch and all Jessie systems, since Raspbian does not have a backports repo.

Btw. indeed the internal updater is not available through the web UI when installing from APT repo, which makes sense as this is/should be done via package upgrades then.

#### PR up: https://github.com/MichaIng/DietPi/pull/2621
