### ISSUE TITLE
DietPi-Software | Grafana: Switch to new official APT repo

### ISSUE THREAD

**Issue by jvteleco** [MichaIng/DietPi#2449]
#### Required Information:
- Date           | Sun 27 Jan 10:21:56 GMT 2019
- DietPi version | v6.19.7 (Fourdee/master)
- Img creator    | DietPi Core Team
- Pre-image      | FriendlyARM
- SBC device     | NanoPi NEO 2 (aarch64) (index=65)
- Kernel version | #82 SMP Fri Dec 8 14:33:14 CST 2017
- Distro         | stretch (index=4)
- Command        | G_AGUP
- Exit code      | 100
- Software title | DietPi-Software

#### Additional Information (if applicable):
- 77: Grafana
- Freshly installed.

#### Steps to reproduce:
Selected to be installed on dietpi-software

#### Expected behaviour:
Grafana should install.

#### Actual behaviour:
Does not install.
Installation verbose shows error on checking url
Err:6 https://bintray.com/fg2it/deb-arm64/grafana-on-raspberry stretch InRelease

Manually checking it on a browser, that url does not exist.

Checking the github web: https://github.com/fg2it/grafana-on-raspberry
"grafana-on-raspberry (and arm64) Release Build Status
Warning Notice: End of Life
Starting from v5.2.0-beta1 Grafana introduced official support for armv7 and arm64 linux platforms. Many thanks to them for that."
Latest version: https://grafana.com/grafana/download?platform=arm

#### Extra details:

 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Installing Grafana: platform for analytics and monitoring

[  OK  ] DietPi-Software | Connection test: https://bintray.com/user/downloadSubjectPublicKey?username=bintray

OK
[  OK  ] DietPi-Software | APT update, please wait...
Hit:1 https://repos.influxdata.com/debian stretch InRelease
Ign:2 https://cdn-aws.deb.debian.org/debian stretch InRelease
Hit:3 https://cdn-aws.deb.debian.org/debian stretch-updates InRelease
Hit:4 https://cdn-aws.deb.debian.org/debian-security stretch/updates InRelease
Err:6 https://bintray.com/fg2it/deb-arm64/grafana-on-raspberry stretch InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:5 https://cdn-aws.deb.debian.org/debian stretch-backports InRelease
Hit:7 https://cdn-aws.deb.debian.org/debian stretch Release
Fetched 17.6 kB in 2s (6,137 B/s)
Reading package lists...
E: Failed to fetch https://bintray.com/fg2it/deb-arm64/grafana-on-raspberry/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Some index files failed to download. They have been ignored, or old ones used instead.

[FAILED] DietPi-Software | G_AGUP

Thanks 👍

**Comment by MichaIng** [comment]
@jvteleco 
Many thanks for your report.

The error is strange. Here I can access the URL without issues.
I recognized on ARMv8 we use `grafana-on-raspberry` sub dir to point to the repo, on ARMv6/7 not 🤔. This is a bid strange, since all all arch sub dirs on the repo are structured the same: https://bintray.com/fg2it
So it should be either without or with subdir on all archs, actually with subdir, to have the usual APT repo structure.
However our solution follows the official instructions, and of course we tested them on all archs: https://github.com/fg2it/grafana-on-raspberry/wiki#with-apt-from-bintray-debian-repository

But now indeed the repo maintenance faded out already a while ago. Latest there is 5.1.4 while latest upstream version is 5.4.3: https://grafana.com/grafana/download/5.4.3?platform=arm

They have an own repo as well: http://docs.grafana.org/installation/debian/#apt-repository
I will open PR to implement this: https://github.com/Fourdee/DietPi/pull/2450
