### ISSUE TITLE
DietPi-Update | Update to v6.20.5 fails

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#2458]
#### Details:
- Date           | Mon 28 Jan 23:16:07 CET 2019
- Bug report     | N/A
- DietPi version | v6.19.7 (Fourdee/master)
- Img creator    | DietPi Core Team
- Pre-image      | FriendlyARM
- SBC device     | NanoPi NEO 2 (aarch64) (index=65)
- Kernel version | #82 SMP Fri Dec 8 14:33:14 CST 2017
- Distro         | stretch (index=4)
- Command        | chmod -R +x /DietPi /var/lib/dietpi/services /etc/cron.daily/dietpi /etc/cron.hourly/dietpi /etc/profile.d/dietpi-*.sh /etc/bashrc.d/dietpi-bash_completion.sh /etc/bashrc.d/dietpi-login.sh /etc/bashrc.d/dietpi-posix-set-locale.sh /etc/bashrc.d/dietpi-ps1_kill_animation.sh /etc/bashrc.d/dietpi-unsupported_terminal.sh
- Exit code      | 1
- Software title | DietPi-Update

#### Steps to reproduce:

1. dietpi-update
2. 

#### Expected behaviour:

- update to v6.20.5

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
chmod: cannot access '/etc/profile.d/dietpi-*.sh': No such file or directory
```

**Comment by Gravesy83** [comment]
I just got pretty much the same error, but on a Raspberry Pi 2 :

#### Details:
- Date           | Mon 28 Jan 23:37:55 CET 2019
- Bug report     | N/A
- DietPi version | v6.19.7 (Fourdee/master)
- Img creator    | n/a
- Pre-image      | n/a
- SBC device     | RPi 2 Model B (armv7l) (index=2)
- Kernel version | #1159 SMP Sun Nov 4 17:50:20 GMT 2018
- Distro         | stretch (index=4)
- Command        | chmod -R +x /DietPi /var/lib/dietpi/services /etc/cron.daily/dietpi /etc/cron.hourly/dietpi /etc/profile.d/dietpi-*.sh /etc/bashrc.d/dietpi-bash_completion.sh /etc/bashrc.d/dietpi-login.sh /etc/bashrc.d/dietpi-posix-set-locale.sh /etc/bashrc.d/dietpi-ps1_kill_animation.sh /etc/bashrc.d/dietpi-unsupported_terminal.sh
- Exit code      | 1
- Software title | DietPi-Update

#### Steps to reproduce:

1. run dietpi-update
2. ...

#### Expected behaviour:

- ... update to next version

#### Actual behaviour:

- ... update fails

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
chmod: cannot access '/etc/profile.d/dietpi-*.sh': No such file or directory
```

**Comment by MichaIng** [comment]
@maartenlangeveld @Gravesy83 
Thanks for reporting.

Hmm from which initial version did you update?

pre-v6.20 images should actually have `/etc/profile.d/dietpi-unsupported_terminal.sh` which fits the pattern. This is removed (moved to `/etc/**bashrc.d**/dietpi-unsupported_terminal.sh`) with patch v6.20, but after the `chown` command.

Did you manually removed `/etc/profile.d/dietpi-unsupported_terminal.sh`?

However, to fix, please place a fake script to match the pattern, at best exactly the expected one, so it will be removed on patch automatically:
`> /etc/profile.d/dietpi-unsupported_terminal.sh`

**Comment by maartenlangeveld** [comment]
I installed DietPi on my NanoPi NEO2 (headless) using DietPi_v6.14_NanoPiNEO2-ARMv8-Stretch.img (downloaded) then updated to v6.19.7. This night after a reboot I did an upgrade to v6.20.5 using dietpi-update command.

**Comment by maartenlangeveld** [comment]
Hi Micha,

I updated from v6.19.7. I did not manually remove anything. Maybe I have re-run the update when it seemed to be stuck half way.

Thanks for your help, using fake script helped to run update.


Maarten

**Comment by maartenlangeveld** [comment]
On another devire (rpi zero w with dietpi 6.19.7) update hangs at:

[ INFO ] DietPi-Update | Patching 6.19.7 to 6.20

Or can this take much time (>30 mins) ?

Maarten

**Comment by MichaIng** [comment]
Strange, cant fine the issue currently:
- When updating to v6.19.7 (or earlier), `/etc/profile.d/dietpi-unsupported_terminal.sh` will be placed: https://github.com/Fourdee/DietPi/commits/e7a42f9f21eed4505f14459902365a3938cb76bd/rootfs/etc/profile.d/dietpi-unsupported_terminal.sh
- When updating to v6.20, the v6.19.7 (or earlier) `dietpi-update` version will download and place new code and do the above `chown` command as expected, BEFORE running incremental patch: https://github.com/Fourdee/DietPi/blob/8c629fa34e0d47f427c67066c0a1098543c5203e/dietpi/dietpi-update#L324
- Incremental patch will even apply the new install stage versioning and start the new v6.20 `dietpi-update` version that has already been downloaded and placed: https://github.com/Fourdee/DietPi/blob/master/dietpi/patch_file#L76-L98
- The new v6.20 `dietpi-update` will not chown this obsolete location anymore: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-update#L349
- Incremental patches will then remove the obsolete script when patching v6.19 => v6.20: https://github.com/Fourdee/DietPi/blob/master/dietpi/patch_file#L1537
- Parent update install will exit: https://github.com/Fourdee/DietPi/blob/master/dietpi/patch_file#L49-L50

Can't see the reason for your errors currently, especially since I successfully updated my own RPi just yesterday to nearly identical Beta and lots of virtual machines during development time.
However please apply the mentioned fix by creating the fake file.

@Fourdee 
Do you have any clue? Perhaps an async issue?
We could remove error handling from `chmod` or find something similar to `rm -f` option to ignore missing files, but actually it is good to know, if those files are either missing or write access/chmod fails, since this is indeed an important error otherwise. In this case somehow just the earlier update script somehow attempts to chmod a file that either was never created as expected or removed earlier than expected, or, the wrong script version was run. But I have no idea currently how any of those could have happened, besides due to async, the new code was not yet fully synced to disk.

Perhaps we should place another `sync` after code has been placed and before incremental patching. Although if this really was an issue, we should have faced much more error reports like this 🤔. And I can't believe that `async` really works bad as this, overwriting a bunch of files and not having the new files when reading back...

**Comment by MichaIng** [comment]
@maartenlangeveld 
It can take a while due to reinstalls, depending on which additional software titles you have installed.
But it should print something to the terminal, prefixed with `DietPi-Patchfile`.
You can check which script it is currently running via second SSH session (or second terminal) running: `htop`
______________
Report on forum: https://dietpi.com/phpbb/viewtopic.php?f=11&t=5469
- Seems to occur device-independently, but according to update counts (and our own tests) not in every case.
______________
Following survey page v6.20 counts to guess how many users are affected: https://dietpi.com/survey/

23:20:19 UTC | DietPi v6.20 | 108
------------ | ------------ | ---
23:35:25 UTC | DietPi v6.20 | 107
23:51:01 UTC | DietPi v6.20 | 110
00:06:14 UTC | DietPi v6.20 | 113
00:20:17 UTC | DietPi v6.20 | 118
00:35:50 UTC | DietPi v6.20 | 119
01:50:32 UTC | DietPi v6.20 | 136
02:20:58 UTC | DietPi v6.20 | 138
02:35:20 UTC | DietPi v6.20 | 141
12:06:05 UTC | DietPi v6.20 | 236

**Comment by MichaIng** [comment]
I will now recover the file as empty on update branch to prevent the issue. We can then remove it with v6.21 where the new update script is in place/synced definitely.

**EDIT: Okay merged: https://github.com/Fourdee/DietPi/commit/0cc30eb6e41cb7ca6ec65852c58c013fcd57e24b**
- Whatever causes this issue, the above commit should resolve it + includes some fail safe `sync` just in case it is due to disk async, which could otherwise imply other issues as well.
- The fake file is empty, thus has no effect and will be removed during last incremental patch stage. So the final update result is not affected at all.
- We just need to remember to remove it again for v6.21 release. I will leave it in place now, until everything else is verified to work well and we do the first new `dev` commits.

**Comment by MichaIng** [comment]
@maartenlangeveld @Gravesy83 
Okay this has been solved. Thanks again for reporting. Feel free to reopen the issue, if required.

**Comment by MichaIng** [comment]
Okay, issue is related to: https://github.com/Fourdee/DietPi/issues/2466
- `DietPi-RAMdisk` stops too late, after `/boot` being already unmounted.
- So new code is not saved to disk.
- On reboot, old code from disk is loaded, where update still expects the removed file.

Only question: Why actually reboot is done DURING update? Should only be the case on first run updates. However we leave the fake file in place AND revert the RAMdisk+RAMlog changes to assure both are stopped before local-fs.target and as failsafe DietPi.mount var-log.mount/boot.mount and -.mount (root).

**Comment by MichaIng** [comment]
Hotfix via v6.20.6 merged. Should resolved all related issues.
