### ISSUE TITLE
DietPi-Software | Pi-hole: "Unknown" state on Tinkerboard S

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#2579]
When installing PiHole on the latest diet pi. PiHole is installed shows It's running status as UNKNOWN, and nothing is saved when changing settings in the PiHole gui. This is all on a ASUS Tinkerboard S

**Comment by MichaIng** [comment]
@xxirs 
Thanks for your report.

Will test the current Pi-hole installer.
#### EDIT: Working fine here on VM Stretch with Lighttpd webserver. Status on Pi-hole admin panel shows `active`.
Meanwhile, did you get any error messages during the `dietpi-software` run?

And since this caused an issue when updating, please try to following to update your Pi-hole:
```
cd /var/www/html/admin
git reset --hard HEAD
pihole -up
```

#### EDIT
Another question: Which webserver did you choose?

**Comment by MichaIng** [comment]
I mark this as closed due to missing user reply. Please feel free to reopen if issue persists after you have done the update as above.
