### ISSUE TITLE
DietPi-Update | chmod cannot access '/etc/profile.d/dietpi-*.sh'

### ISSUE THREAD

**Issue by RynFlutsch** [MichaIng/DietPi#2616]
Tried to upgrade vie dietpi-update
![update-error-chmod](https://user-images.githubusercontent.com/29811876/53764554-f4ee8180-3ecd-11e9-914c-a39a88dd6844.png)

**Comment by RynFlutsch** [comment]
I retried, with success. Update finished..
?

**Comment by MichaIng** [comment]
@RynFlutsch 
Jep known issue if an earlier update attempt to v6.20 failed. Indeed rerunning the script works, since the new version has already been downloaded when the error prompts.

Just as there were some other related issue:
`cat /DietPi/dietpi/.install_stage`
should be `2`, otherwise set it:
`echo 2 > /DietPi/dietpi/.install_stage`

But if you already rebooted and did not run into a repeated first run setup, then this is already correct for sure 😉.

**Comment by MichaIng** [comment]
I mark as closed since solved. Please feel free to reopen if required.
