### ISSUE TITLE
DietPi-Config | USB boot: Do not set boot bit on RPi 3+

### ISSUE THREAD

**Issue by Gill-Bates** [MichaIng/DietPi#2659]
Hello,

I still haven't managed to boot the Raspberry Pi without an SD card, exclusively with a USB hard disk (SSD 2.5"). I write the image (Dietpi/Raspian) on the disk, connect it to the Raspberry Pi and boot the system. But it doesn't start.

Of course I set the boot bit. Moving the filesystem to the external disc works curiously. However, the SD card must always remain in the device.

Am I trying to do something here that isn't officially supported? I would like to do without the SD card completely.

**Comment by MichaIng** [comment]
@Gill-Bates
Indeed it is a missing feature of the RPi itself, AFAIK. The boot partition itself needs to stay on the SDcard while the root partition can be moved by changing the cmdline.txt entry accordingly. This is what we do when moving the root partition via dietpi-drive_manager.

Not sure currently but I read something about USB boot support. Will investigate. Perhaps we can offer an USB image then.

Reading: https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md
- RPi3+ seems to support it out of the box
- RPi3 needs to be programmed in a way that cannot be undone.
- Looks like the other RPi models do not support it, since they are not mentioned at all.

Which RPi model do you use?

**Comment by MichaIng** [comment]
Ah lol we already have the feature added to `dietpi-config`: https://github.com/MichaIng/DietPi/blob/dev/dietpi/dietpi-config#L1317-L1325
- However since RPi3+ does not require the boot bit to be set, we can enhance this slightly.
- Also since above the warn somehow that this cannot be undone, would be interesting if SDcard boot is still possible with this enabled, because otherwise a second warning prompt would be good.

So yeah, definitely not possible on RPi1/2.

**Comment by MichaIng** [comment]
Already implemented and just fixed, as this option was shown on RPi 3+ instead of RPi 3 non-plus only: https://github.com/MichaIng/DietPi/commit/b21976e58880b262f11b1c596b2d24d481397155

**Comment by netwrkx** [comment]
@MichaIng I can't get my RP3b+ to boot from usb hdd, whenever I boot from sdcard, my RP3B+ can detect my hdd and access it.
Without sdcard, my rp3b+ does not boot

Any idea why?

                                                                          ```
DietPi-Update
─────────────────────────────────────────────────────
 Mode: Checking for DietPi updates

[ INFO ] DietPi-Update | Checking mirror: https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi/server_version-6
[  OK  ] DietPi-Update | Using update server: https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi/server_version-6
[  OK  ] DietPi-Update | No update required, your DietPi installation is already up to date:
[ INFO ] DietPi-Update | Current version : v6.26.3                       [ INFO ] DietPi-Update | Latest version  : v6.26.3
```

**Comment by MichaIng** [comment]
Ref: #3223
