### ISSUE TITLE
DietPi-Globals | Wrong "sudo" info for dietpi-* aliases: Was fixed with v6.23

### ISSUE THREAD

**Issue by Sopor** [MichaIng/DietPi#2810]
#### Required Information
- G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=22
G_DIETPI_VERSION_RC=3
G_GITBRANCH=master
G_GITOWNER=MichaIng

- Distro version | 9.9
- Kernel version | Linux dietpi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
- SBC device | RPi 3 Model B+ (armv7l)
- Power supply used | 5V 2.4A
- SDcard used | None
- USB | Kingston A400 SSD with external power

#### Steps to reproduce

I noticed a message today about updating DietPi `dietpi-update   : Run now to update DietPi from v6.22.3 to v6.24.0.` so i ran first `dietpi-update` but then i got a message that i should use `sudo -s dietpi-update` so i did that too.

#### Expected behaviour

I assume it should start to update DietPi?

#### Actual behaviour

Instead i got this message
```
xxxxx@dietpi:~ $ dietpi-update
[FAILED] DietPi-Update | Root privileges required. Please run the command with "G_SUDO", or, "sudo -s".
xxxxx@dietpi:~ $ sudo -s dietpi-update
[sudo] password for xxxxx:
/bin/bash: dietpi-update: command not found
xxxxx@dietpi:~ $
```

**Comment by UNiXMIT** [comment]
Try running the script with the full path:

`sudo /DietPi/dietpi/dietpi-update`

**Comment by Sopor** [comment]
If full path is needed the help text should includes that information instead of only showing this text:
```
[FAILED] DietPi-Update | Root privileges required. Please run the command with "G_SUDO", or, "sudo -s".
```

**Comment by UNiXMIT** [comment]
Did it help though? It's not usually needed.
I've just tried it and yes sudo -s dietpi-update returns that error. Try it without the -s and it should work fine.

**Comment by Sopor** [comment]
But the instructions say `sudo -s` so i did use what it tells me to do. The `-s` (runs a shell with root privileges) is added for some reasons or else it could be left out.

**Comment by MichaIng** [comment]
@Sopor @UNiXMIT 
Jep the "-s" is not correct here. The info was changed with v6.23.

Please simply do: `sudo dietpi-update`

**Comment by UNiXMIT** [comment]
Ah yes it has changed in 6.23. Great.

**Comment by MichaIng** [comment]
Ref: https://github.com/MichaIng/DietPi/blob/master/dietpi/func/dietpi-globals#L456
> Root privileges required. Please run the command with "sudo" or "G_SUDO".

Sidenote:
- `sudo` alone works for "aliases", which includes the dietpi-* commands.
- `G_SUDO` is required for global functions (the G_* commands, e.g. `G_CHECK_URL https://dietpi.com`, `G_AGUP`, ...). It assures that the `dietpi-globals` script (which defines the functions, as above link) is fully loaded before the G_* command is attempted to run. Usually the script is loaded with `sudo -s`, but since it requires a little while to load, in most cases the G_* command is attempted to run before it has been loaded. So we load it actively and run the function afterwards.
