### ISSUE TITLE
FQDN/hostname : mismatch between DietPi-banner output and hostname command (domain name lacking)

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#2829]
DietPi-Banner states
(WAN IP deliberately changed: not my real IP)
 ```
─────────────────────────────────────────────────────
 DietPi v6.24.1 : 14:45 - Sun 19/05/19
 ─────────────────────────────────────────────────────
 - Device model : RPi Zero W (armv6l)
 - Uptime : up 1 day, 11 hours, 56 minutes
 - CPU temp : 34'C : 93'F (Cool runnings)
 - FQDN/hostname : DietPi
 - NIS domainname : hostname: Local domain name not set
 - LAN IP : 192.168.168.10 (wlan0)
 - WAN IP : 145.133.001.002
 - Freespace (RootFS) : 7.5G
 - Freespace (music folder) : 236G
 ─────────────────────────────────────────────────────
```
while hostsname gives:

```
root@DietPi:~# hostname --fqdn
DietPi.local
root@DietPi:~# hostname --short
DietPi
root@DietPi:~# hostname --domain
local
```
and

```
root@DietPi:~# hostname
DietPi.local
root@DietPi:~# hostname --fqdn
DietPi.local
root@DietPi:~# hostname --short
DietPi
root@DietPi:~# domainname
(none)
root@DietPi:~# dnsdomainname
local
root@DietPi:~# nisdomainname
nisdomainname: Local domain name not set
```

So FQDN/hostname does not match (domain is lacking in DietPi-banner output).

Curious why there's a mismatch. 

added info:

My RPi DietPi gets its IP address (192.168.168.10), domain name (local) and DNS address(es) assigned by  DHCP server in my network.

/etc/hosts/
> 127.0.0.1       localhost
> 127.0.1.1       DietPi
> ::1             localhost       ip6-localhost   ip6-loopback
> ff02::1         ip6-allnodes
> ff02::2         ip6-allrouters

/etc/hostname
> DietPi

**Comment by MichaIng** [comment]
@maartenlangeveld 
Thanks for your report.

I wonder is why `hostname --fqdn` shows `DietPi.local` while the banner shows `DietPi` only. It uses `hostname -f` which is only an alias for `hostname --fqdn`, so they should show both the long version.

The reason is that FQDN already contains the full name, including the domain. It would have been unnecessary overhead to separate those info into two fields. You always require the full FQDN anyway to access.

For "NIS domainname" it uses `hostname -y` (== `--yp`/`--nis`), which is not the same as `hostname --domain/-d`. Read about it here: https://en.wikipedia.org/wiki/Network_Information_Service

NIS/YP needs separate implementation, which is why it says in your case: "Local domain name not set"
Actually NIS/YP is an outdated and insecure nameserver + user authentication solution. Nowadays the purpose is mostly solved differently, e.g. via LDAP.

**Comment by maartenlangeveld** [comment]
@MichaIng 
Thanks, not an important issue though. I now understand there are different domain names (DNS vs NIS). 
Will check another time why there's a difference between the outputs.

**Comment by maartenlangeveld** [comment]
@MichaIng 

Cannot reproduce. Now both outputs are consistent (no domain name).
It surprises me since I have set domain :  local in DCHP server, so I would expect my RPI gets 'local' as domain name assigned. Apparently not.

**Comment by MichaIng** [comment]
@maartenlangeveld 
Not sure if the `hostname` respects any externally assigned info at all. Usually `/etc/hostname` should simply contain the full FQDN. The hostname command handles this correctly, producing long/short/domain outputs.
______
I am also a bid confused about the default of the commands and why NIS/YP has such a central position. E.g. `domainname` shows the NIS/YP domainname, while DNS domain requires a separate command: `dnsdomainname`
This gives the impression that NIS is somehow the standard and important or something, but it is actually nothing but a proprietary outdated insecure obsolete solution...

**Comment by maartenlangeveld** [comment]
@MichaIng 
Ok thanks, learning a lot. I shall close since not an issue at all. Thanks for your patience.
