### ISSUE TITLE
pivpn output missaligned

### ISSUE THREAD

**Issue by m4rtini2** [MichaIng/DietPi#2872]
#### Required Information
- DietPi version | 6.24.1
- Distro version | 9.9
- Kernel version |  4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
- SBC device | RPi 2 Model B (armv7l)

#### Additional Information (if applicable)
- Software title | pivpn
- accessing dietpi shell over ssh from external machine 

#### Steps to reproduce
in the shell execute 'pivpn clients'

#### Expected behaviour
list of clients in a correctly formated table
```
client_89a              127.0.0.0 ...
client7                 123.533.111.111 ...
client_8                10.10.10.10 ...
12345                   123.533.111.112 ...
```
#### Actual behaviour
When the name of the client is shorter than 8 characters the output of the first column (Remote IP) starts 8 characters to early which makes the list difficult to read. It looks like a missing tab in a table. Something like this:
```
client_89a              127.0.0.0 ...
client7         123.533.111.111 ...
client_8                10.10.10.10 ...
12345           123.533.111.112 ...
```

#### Extra details
link to forum https://dietpi.com/phpbb/viewtopic.php?f=11&t=6015

**Comment by MichaIng** [comment]
@m4rtini2 
Many thanks for your report.

Since this is about the `pivpn` binary/script, it is out of our control. Please reopen this issue at the PiVPN GitHub site: https://github.com/pivpn/pivpn/issues

I mark this issue as closed, feel free to reopen if you experience any issue with PiVPN install or setup on DietPi.
