### ISSUE TITLE
Jackett keeps breaking and doesn't work

### ISSUE THREAD

**Issue by athousanddetails** [MichaIng/DietPi#3057]
### Creating a bug report/issue

I'm on the latest version, everything updated on my DietPi Asus Thinker Board, and Jackett keeps breaking down all the time. If I unninstall and install again it will work for 1 day and then off again he goes. 

I don't know how to reproduce the bug, but this is annoying as well specially with Sonarr and Radarr. Any idea what is going on or how to fix this?

#### Required Information
- SBC device | Asus Thinker Board

**Comment by MichaIng** [comment]
@athousanddetails 
Many thanks for your report.

Most likely it's this known issue with the internal Jackett updater: https://github.com/MichaIng/DietPi/issues/2593

A slightly simpler solution to repair the broken Jackett instance is given in the linked issue as well: `reinstall` instead of uninstall + install

Sad to see that this quite important bug has still not yet been fixed. It is sadly outside our possibilities to ship some workaround with DietPi, besides probably disable the updater right within our install script. I was just hoping for a soon upstream fix 😞.
_________
Ref: https://github.com/MichaIng/DietPi/issues/3058
Just the same bug reports the same time 😉.

**Comment by VasilevAndrei** [comment]
Hi, I had the same problem. The following solution worked for me - after reinstalling jackett, check the box for "Disable auto update". My current Jackett Version 0.11.589.0, works on DietPi x86.

**Comment by MichaIng** [comment]
I mark this issue as closed in favour of the linked initial one.
