### ISSUE TITLE
Restarting php7.3-fpm using dietpi-services gives an error

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#3059]
Restarting php7.3-fpm using dietpi-services gives an error:
> root@DietPi:/# dietpi-services restart php7.3-fpm

```
[  OK  ] DietPi-Services | Root access verified.

 DietPi-Services
─────────────────────────────────────────────────────
 Mode: restart php7.3-fpm

/DietPi/dietpi/dietpi-services: line 408: php7.3-fpm: syntax error: invalid arithmetic operator (error token is ".3-fpm")
```

However
> root@DietPi:/# service php7.3-fpm restart

works fine

**Comment by MichaIng** [comment]
@maartenlangeveld 
Many thanks for your report. Which DietPi version is this?
And please paste: `sed -n 408p /DietPi/dietpi/dietpi-services`

I am a bid confused since there is no arithmetic check on this line, neither in current master code nor before last change on v6.23 (empty line there) 🤔.

**Comment by maartenlangeveld** [comment]
@MichaIng 
DietPi v6.25.3

> root@DietPi:~# sed -n 408p /DietPi/dietpi/dietpi-services
```
                        [[ ${aSERVICE_MODE[$i]} == 'masked' ]] && { G_DIETPI-NOTIFY 2 "skip : ${aSERVICE_NAME[$i]} (due to mask)"; continue; }
```

**Comment by MichaIng** [comment]
@maartenlangeveld 
Found the issue, indeed a coding bug.
Resolved with: https://github.com/MichaIng/DietPi/commit/b4cb3512b02e516af02620add81503523242b39a
Changelog: https://github.com/MichaIng/DietPi/commit/52bb2a659928f8aec0e9e2058fb84e7132f5de3e

To apply fix now:
```
sed -i 's/Apply_Service_State $INPUT_CMD $INPUT_SERVICE/Apply_Service_State $INPUT_CMD ${INPUT_SERVICE+0}/' /DietPi/dietpi/dietpi-services
```

This passed testing since when you add any non-integer value as array index, (`echo ${array[test]}`) it will be converted/interpreted as `0`, which is correct when dietpi-services is called with single service input. But with certain character types, like dots (in your case), this does not work and the error is thrown instead:
```
root@VM-Stretch:~# aTEST[0]=success
root@VM-Stretch:~# echo ${aTEST[0]}
success
root@VM-Stretch:~# echo ${aTEST[test]}
success
root@VM-Stretch:~# echo ${aTEST[test.oops]}
-bash: test.oops: syntax error: invalid arithmetic operator (error token is ".oops")
```

**Comment by maartenlangeveld** [comment]
@MichaIng 
Thanks, but unfortunately the fix did not help.... actually made things worse.

**Comment by MichaIng** [comment]
@maartenlangeveld 
Ay jep, I've overseen something. Fixed with: https://github.com/MichaIng/DietPi/commit/2738685269c4e33b55dfb0af2da569a89fbfe30b
