### ISSUE TITLE
DietPi-Banner | WAN-IP check backup 

### ISSUE THREAD

**Issue by svh1985** [MichaIng/DietPi#3060]
#### Is your feature request related to a problem? Please describe:

- ATM the dietpi.com site is down, this means that the check ip also fails with all kinds of errors

#### Describe the solution you'd like:

- Have a secondary IP check as a backup
- Ignore HTML errors like example below, probably better to show UNKNOWN, not the entire HTML

#### Describe alternatives you've considered:

- We can also include the DYN Check IP in the check: http://checkip.dyn.com/

#### Error example
![RockPi_local](https://user-images.githubusercontent.com/5213210/63214015-6c7a3b00-c113-11e9-8464-296e97ad3f0b.png)

**Comment by MichaIng** [comment]
@svh1985 
Many thanks for your report.

Indeed we had a server downtime: https://github.com/MichaIng/DietPi/issues/3061
It is now up again, but you're right, we need to to avoid this output for WAN IP and as well if the weather data download fails: https://github.com/MichaIng/DietPi/blob/dev/dietpi/func/dietpi-banner#L199

I thing since we use Cloudflare, the problem is that curl does not report an error when dietpi.com is down, but instead one is redirected to this Cloudflare page, showing that the final host is down, and one can try to load a cached version of the static website. Easiest solution would be IMO to only print the first output line (`head -1`), as WAN IP and weather data should never require more.

**Comment by MichaIng** [comment]
Okay I changed the way we handle curl error outputs in the banner: https://github.com/MichaIng/DietPi/commit/db47a9466ff452bf20c48bf0bd474aa85f3fd6e4

To compare on a non-existing document:
```
root@VM-Stretch:~# curl -sLm 2 https://dietpi.com/myip.phpa 2>&1
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /myip.phpa was not found on this server.</p>
</body></html>
root@VM-Stretch:~# curl -sSfLm 2 https://dietpi.com/myip.phpa 2>&1
curl: (22) The requested URL returned error: 404
```
To be true, it requires testing for Cloudflare served websites, but it looks like the HTTP status code in your case was 521, a Cloudflare special for webserver downs: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Cloudflare
If this response code is sent to clients, curl should omit the error page HTML code and instead print the informational one-line error only.

Perhaps we can find some Cloudflare served server that is down, for testing?
________
However there is still things we can improve, also to speed up the banner:
- Estimate network-based info via cron job (or systemd timer): https://github.com/MichaIng/DietPi/issues/2832
- By this we can also allow longer connections times for slow network systems. Currently it allows max 2 seconds to not delay the banner print too much.
- In case of any error, we could keep the last stored info. Probably allow this for 1 day, if until then error is not resolved, print it, so users can report/we can investigate.

Also your alternative sounds good. It is also faster, although it seems only because its unencrypted:
```
root@VM-Stretch:~# time for i in {1..10}; do curl -s https://dietpi.com/myip.php &> /dev/null; done

real    0m1.828s
user    0m0.760s
sys     0m0.088s
root@VM-Stretch:~# time for i in {1..10}; do curl -s https://dietpi.com/myip.php &> /dev/null; done

real    0m1.737s
user    0m0.772s
sys     0m0.088s
root@VM-Stretch:~# time for i in {1..10}; do curl -s http://checkip.dyn.com/ &> /dev/null; done

real    0m1.283s
user    0m0.224s
sys     0m0.124s
root@VM-Stretch:~# time for i in {1..10}; do curl -s http://checkip.dyn.com/ &> /dev/null; done

real    0m1.270s
user    0m0.256s
sys     0m0.108s
root@VM-Stretch:~# time for i in {1..10}; do curl -s https://ifconfig.me/ &> /dev/null; done

real    0m2.498s
user    0m0.720s
sys     0m0.100s
root@VM-Stretch:~# time for i in {1..10}; do curl -s https://ifconfig.me/ &> /dev/null; done

real    0m2.486s
user    0m0.716s
sys     0m0.108s
root@VM-Stretch:~# time for i in {1..10}; do curl -s http://ifconfig.me/ &> /dev/null; done

real    0m1.691s
user    0m0.240s
sys     0m0.096s
root@VM-Stretch:~# time for i in {1..10}; do curl -s http://ifconfig.me/ &> /dev/null; done

real    0m2.092s
user    0m0.276s
sys     0m0.108s
```
But is requires some string manipulation:
```
root@VM-Stretch:~# curl -s http://checkip.dyn.com/
<html><head><title>Current IP Check</title></head><body>Current IP Address: 46.59.133.131</body></html>
```
Actually from HTTPS sources, ours is fastest 😋.
