### ISSUE TITLE
Use another text color when updating

### ISSUE THREAD

**Issue by Sopor** [MichaIng/DietPi#3074]
Could you use another color for the text? It is even harder to see it real on the monitor than in the screenshot below. 

![image](https://user-images.githubusercontent.com/5789283/63604370-d2f7d100-c5cb-11e9-87b2-b44b589c2591.png)

**Comment by Sopor** [comment]
Same at the login banner

![image](https://user-images.githubusercontent.com/5789283/63604890-27e81700-c5cd-11e9-8ed1-ec98df8b2027.png)

And again, it is much easier to see it here on a screenshot than it is on the monitor.

**Comment by MichaIng** [comment]
@Sopor 
Many thanks for your request. The plan is to make all those colour customisable, since it depends on the terminal and screen, how they look like and how well they are readable. The idea generally was to separate important outputs from less important ones, e.g. informational mess vs results and such.

See here: https://github.com/MichaIng/DietPi/issues/2651

This can be expanded for all DietPi outputs generally. Not too much work since we used shared functions from `dietpi-globals` mostly.

**Comment by MichaIng** [comment]
I close this issue on favour of the existing, however cross-linked it here: https://github.com/MichaIng/DietPi/issues/2651
A general colour code customisation makes sense, as mentioned, to tune colours for the local terminal/screen.
Moreover actually, to make it 100% effective, it should be separate sets for local terminal, serial console and SSH. This is not too hard, since we can get the attached tty via `tty` command. SSH use `/dev/pts/[0-9]`, local console `/dev/tty[1-9]` and serial console would be everything else, usually `/dev/ttyS[0-9]` (software-based), `/dev/ttyAMA[0-9]` (ARM hardware serial device), `/dev/ttySAC[0-9]` (hardware serial device on some Odroids AFAIK), but `/dev/ttyFIQ[0-9]` or something like that is also seen 😄.
