### ISSUE TITLE
Dietpi-Banner | Show Nord VPN connection state

### ISSUE THREAD

**Issue by svh1985** [MichaIng/DietPi#3079]
#### Is your feature request related to a problem? Please describe:

- Not really, would be a nice improvement tho

#### Describe the solution you'd like:

- To make the NordVPN implementation complete, it would be nice to show the connection state in the Dietpi-Banner
- Have the ability to add it to the list of items printed when loggin into dietpi

#### Additional context

- I think we can reuse some code from the dietpi-nordvpn script itself

**Comment by MichaIng** [comment]
@svh1985 
Great idea. Here is the part of the scripts that estimates the in-menu state info: https://github.com/MichaIng/DietPi/blob/dev/dietpi/misc/dietpi-nordvpn#L160-L187

Since WAN IP is a separate entry, `connected: <server>`/`disconnected: <server>`/`not configured: <subscription URL>` + probably RX/TX traffic in a separate line could be shown?

You might want to play around with the custom banner entry for now, e.g. create a script that creates the output line/lines. We can add a function/input mode to `dietpi-nordvpn` script as well, which only prints the current status instead of starting "G"UI.

**Comment by MichaIng** [comment]
Ref: https://github.com/MichaIng/DietPi/pull/3084
