### ISSUE TITLE
DietPi-Software | myMPD: Update install steps to avoid deprecations

### ISSUE THREAD

**Issue by jcorporation** [MichaIng/DietPi#3097]
Hi,
I am the developer of myMPD and I plan to release a new myMPD release which will break your source build in the future. 

1)
The mkrelease.sh script is deprecated in my devel branch.
Please consider replacing ``./mkrelease.sh`` with ``./build.sh releaseinstall``. For now I added a ``./mkrelease.sh`` wrapper in devel and a ``./build.sh`` wrapper in master to prevent breakage of your source build.

2)
I see also, that you change the group of the mympd user to dietpi in your systemd service. Why is this needed and is it not better to change the primary usergroup to dietpi? Changing ``usermod -a -G dietpi mympd`` to ``usermod -g dietpi mympd`` should have the same effect?
In the new version myMPD creates the directory /var/lib/mympd ans it subdirs on startup with a umask of 0007.

3)
The symlink to music/libary is no more needed. myMPD handles this internally.

Best regards and many thanks for this great software.

4)
In the new version the configuration file is now /etc/mympd.conf no more /etc/mympd/mympd.conf. The syscmds directory is replaced with a section within mympd.conf.

**Comment by MichaIng** [comment]
@jcorporation 
Many thanks for your info! Since it is still compatible, I will apply the changes with v6.27. We need to get v6.26 released soon.

About user/group:
- Are you aware of any downsides when applying dietpi group via systemd unit only? It is a failsafe method, that avoids to touch additional groups, the user was added to, so e.g. on reinstall, if the "user" changed permissions or group memberships for some reason, those are not overwritten. Also we can do this as a general method for all software installs, where required, without needing to check and perserve explicitely existing memberships.
- Btw we use dietpi group with all software titles, that write files to media or download dirs, so other media and download software can access those files without any additional configuration needed, and this with all downloaders/sonarr/radarr/../media players etc we offer. But actually myMPD does not write media files, does it? It should be sufficient to add dietpi group as additional group only (so it has read access to media files), but it can still run as mympd group?
- I will have a look at config directories and symlinks. When do you expect release where these changes need to be done?

**Comment by jcorporation** [comment]
myMPD don't write files to media or download dirs. It writes only internal states to /var/lib/mympd. So  it should be sufficient to add dietpi group as additional group only.

The revised install script now detects old installations and run following actions:
- removes the /usr/share/mympd directory entirely (assets are now embedded in the binary)
- moves /etc/mympd/mympd.conf to /etc/mympd.conf
- removes /etc/mympd directory
- removes /var/lib/mympd/tmp directory
- moves the systemd unit from /usr/lib/systemd/system to /lib/systemd/system (right place according to lintian)

I hope this changes enables a smooth change for the dietpi users. Feel free to propose changes to the installation / upgrade workflow for myMPD.

The new version of myMPD should be released in this month.

**Comment by MichaIng** [comment]
Great, I will implement the change to not run myMPD as dietpi group. Probably we can manage it to align DietPi release with myMPD ones so that there will be no installer incompatibilities, otherwise adjust it for this version to support both based on upstream version string.

**Comment by jcorporation** [comment]
myMPD 5.6.0 is now released. It should not break your source build.

**Comment by MichaIng** [comment]
@jcorporation 
Okay I updated our installer as well: https://github.com/MichaIng/DietPi/pull/3110

Btw I saw: https://github.com/jcorporation/myMPD/blob/master/build.sh#L184-L188
[rmdir](https://linux.die.net/man/1/rmdir) has the option `--ignore-fail-on-non-empty` which allows it to omit and succeed on non-empty dirs silently.

**Comment by jcorporation** [comment]
thanks for the hint with rmdir
