### ISSUE TITLE
Realtime Kernel Howto ?

### ISSUE THREAD

**Issue by seniorgod** [MichaIng/DietPi#3129]
Dear all,

this is more a question than a software request...

I want to install a realtime kernel for my sparky/usbridge running dietpi.
I' found some issues regarding realtime kernel here. But to be honest, because i deal only rarely with kernel i'm confused. As far as i understand dietpi is using the standard Debian kernel now? Right?
Until now i understand there are special "drivers" or firmware for sparky/usbridge . Is that not compiled into the kernel? (I have no deep know how on how a kernel/image for rpi /sparky is composed) or are the kernel modules delivered in binary format? 
In May you sent my a hint for the new drivers from all for sparky: 

>Has been a while. Sparky provides updated USB audio driver files, which could be tested. They also provide native DSD to a large number of additional USB DACs.
wget https://raw.githubusercontent.com/sparky-sbc/sparky-test/master/dsd-marantz/snd-usb-audio.ko -O /lib/modules/3.10.38/kernel/sound/usb/snd-usb-audio.ko
wget https://raw.githubusercontent.com/sparky-sbc/sparky-test/master/dsd-marantz/snd-usbmidi-lib.ko -O /lib/modules/3.10.38/kernel/sound/usb/snd-usbmidi-lib.ko
sync
Then reboot to have the active. Perhaps it helps with your kernel errors as well, otherwise it should not hurt.

That looks like the sparky modules are delivered as binary modules....

Is it possible to download and install a kernel like:
Paket linux-image-rt-armmp
stretch-backports (kernel): Linux for ARMv7 multiplatform compatible SoCs (meta-package), PREEMPT_RT  4.19+105+deb10u1~bpo9+1: armhf
What with the drivers in that case? 

Can i download a RT kernel from Debian stretch repositors and afterwards copy these "drivers" ? On the other side during writing i see that the modules have a /3.10.38/ in the path......

How do i get a realtime kernel?

**Comment by MichaIng** [comment]
@seniorgod 
To be true, this goes beyond my knowledge, but what I know is that you will have very limited hardware support or fully fail to load the linked "generic" ARM kernel on any SBC.

Note that all SBCs have very customised kernel builds that enable and ship drivers for the specific hardware. This is the reason we cannot simply build a current 4.X or 5.X kernel for Sparky SBC, since most of its audio and hardware capabilities will simply not work anymore. Kernel development is a very time consuming and hard work on SBCs, which is as well the reason why manufacturers mostly ship the device with an initial kernel version, which is then never upgraded (only patched). Using any generic kernel package will, assuming a lot of manual tinkering, probably lead to a bootable system, but with many hardware features not working or with a lot of issues.

On x86 systems however, where generic kernel and firmware packages work well, it can be tested.
_________
Actually here is a support overview of this Debian armhf multi-platform kernel packages: https://wiki.debian.org/DebianKernel/ARMMP
It also states that those platforms, including all hardware/peripherals, are not necessarily fully supported and in many cases a bootloader needs to be configured manually to run with it.
And AFAIK Sparky SBC has a custom SoC, so non of the ones in the compatibility list.
