### ISSUE TITLE
Radarr logs are not moved to ram on fresh dietpi install.

### ISSUE THREAD

**Issue by Dr0bac** [MichaIng/DietPi#3133]
On Dietpi v6.18 Fourdee moved log files to ram, and i saw that on my system, now when i reinstalled Dietpi (clean install) logs are not linked anymore.

```- DietPi-Software | Radarr/Sonarr/Lidarr: logs (both .txt and .db*) have been moved to DietPi-RAMlog: https://github.com/MichaIng/DietPi/issues/2223```

```root@DietPi:/mnt/dietpi_userdata/radarr# ls -l
total 1852
-rw-r--r-- 1 radarr dietpi     466 Oct  2 00:40 config.xml
drwxr-xr-x 2 radarr dietpi    4096 Oct  1 11:08 logs
-rw-r--r-- 1 radarr dietpi  135168 Oct  2 11:23 logs.db
drwxr-xr-x 2 radarr dietpi    4096 Oct  2 11:23 MediaCover
lrwxrwxrwx 1 radarr root        31 Oct  2 00:39 nzbdrone.db -> /tmp/radarr_db_link/nzbdrone.db
-rw-r--r-- 1 radarr dietpi  581632 Oct  2 00:53 nzbdrone.db.bak
lrwxrwxrwx 1 radarr root        35 Oct  2 00:39 nzbdrone.db-shm -> /tmp/radarr_db_link/nzbdrone.db-shm
-rw-r--r-- 1 radarr dietpi   32768 Oct  2 00:53 nzbdrone.db-shm.bak
lrwxrwxrwx 1 radarr root        35 Oct  2 00:39 nzbdrone.db-wal -> /tmp/radarr_db_link/nzbdrone.db-wal
-rw-r--r-- 1 radarr dietpi 1124792 Oct  2 01:33 nzbdrone.db-wal.bak
-rw-r--r-- 1 radarr dietpi       3 Oct  2 00:40 nzbdrone.pid
```

Database files are linked with `dietpi-arr_to_RAM enable`

**Comment by MichaIng** [comment]
@Dr0bac 
Many thanks for your report.

Linking logs to RAM is still done: https://github.com/MichaIng/DietPi/blob/master/dietpi/dietpi-software#L11836-L11842
However now that you are reporting this, I remember that I found on Jessie systems that shm and wal files are removed and recreated due to a cron job, removing the symlinks as well: https://github.com/MichaIng/DietPi/issues/2689#issuecomment-487307295

However this did not affect the logs dir and db files and was only present on Jessie, not Stretch or Buster. But probably this changed a bid.

Please try to recreate the symlinks manually and check back once directly after Radarr start, once after some time (cron job) and once after reboot if those are still in place:
```
systemctl stop radarr
rm -Rf $G_FP_DIETPI_USERDATA/radarr/logs*
mkdir -p /var/log/radarr
ln -s /var/log/radarr $G_FP_DIETPI_USERDATA/radarr/logs
ln -s /var/log/radarr/logs.db $G_FP_DIETPI_USERDATA/radarr/logs.db
ln -s /var/log/radarr/logs.db-shm $G_FP_DIETPI_USERDATA/radarr/logs.db-shm
ln -s /var/log/radarr/logs.db-wal $G_FP_DIETPI_USERDATA/radarr/logs.db-wal
systemctl start radarr
```
I hope I find some time later as well to test it.

**Comment by MichaIng** [comment]
@Dr0bac 
Ah lol just saw the it's you as well like on the other issue. So I rechecked and retested up and down and symlink are always created here and stay. I mark this as closed, however feel free to reopen if required, or we discuss this in the new issue: #3347
