### ISSUE TITLE
using mender convert DietPi 

### ISSUE THREAD

**Issue by minusplusminus** [MichaIng/DietPi#3140]
Hi,

I'm investigating on how to reduce the size mender of updates for raspberry pi, so i can do OTA updates on my devices. I had the idea that DietPi is like a stripped version of Debian OS, like raspbian lite.

#### Required Information
- DietPi version DietPi_RPi-ARMv6-Buster

#### Steps to reproduce

installed [mender-convert](https://github.com/mendersoftware/mender-convert)
According to Mender, it should be possible. 
executed the following commands
```
DEVICE_TYPE="raspberrypi3"
RAW_DISK_IMAGE="input/DietPi_v6.25_RPi-ARMv6-Buster.img"

ARTIFACT_NAME="mender-DietPi_v6.25_RPi-ARMv6-Buster"
MENDER_DISK_IMAGE="mender-DietPi_v6.25_RPi-ARMv6-Buster"

./docker-mender-convert raw-disk-image-shrink-rootfs \
            --raw-disk-image ${RAW_DISK_IMAGE}


./docker-mender-convert from-raw-disk-image                       \
--storage-total-size-mb 10000             						  \
--raw-disk-image $RAW_DISK_IMAGE                                  \
--mender-disk-image $MENDER_DISK_IMAGE                            \
--device-type $DEVICE_TYPE                                        \
--artifact-name $ARTIFACT_NAME                                    \
--bootloader-toolchain arm-buildroot-linux-gnueabihf              \
--server-cert $(pwd)/server.crt 								  \
--server-url "server url"  
```
#### Expected behaviour
OS running on raspberry pi

#### Actual behaviour

It looks like a kernel panic:
![IMG_2402](https://user-images.githubusercontent.com/1842262/66236834-cc449980-e6f3-11e9-9d9c-1315ac5ee8a6.jpg)

It's difficult to understand whats happening if your not dedicated to DietPi, bacause it is so custom.

Thanks in advance

**Comment by MichaIng** [comment]
@minusplusminus 
Many thanks for your report.

Did you ever tested this with a regular Raspbian Lite image? To be true I have not much idea what "mender" does, but `--bootloader-toolchain arm-buildroot-linux-gnueabihf` sounds wrong in case of Raspbian (thus DietPi RPi images as well), since this most likely uses the wrong Debian `armhf` architecture instead of the `armv6hf` used by Raspbian.

And if its about the image size: We ship our images with already reduced root partition size until the possible minimum, so any further size reduction may lead to boot failure due to insufficient free space.

And it looks like mender adds some custom boot scripts or things anyway? From the last part I can read "`config/init_resize.sh`" which looks like the `raspi-config` partition and file system resize script: https://github.com/RPi-Distro/raspi-config/blob/master/init_resize.sh
That is not installed on DietPi images and should conflict with our own partition resize script: https://github.com/MichaIng/DietPi/blob/dev/rootfs/var/lib/dietpi/services/fs_partition_resize.sh
Not sure where this came from, just checked our current RPi image and it is definitely not there, as raspi-config is not installed.

And if its about DietPi updates:
- You don't need to download and flash a new image every time.
- `dietpi-update` downloads our GitHub archive, which is currently 2.5 GiB in size: https://github.com/MichaIng/DietPi/archive/master.zip
- The largest traffic comes from the APT package upgrades, so if you want to reduce download traffic you should think about a local APT repository which serves the required packages for other devices within your local network.

**Comment by MichaIng** [comment]
I mark this as closed. Feel free to reopen if required.
