### ISSUE TITLE
esp01215e LCD Driver support for N2

### ISSUE THREAD

**Issue by moatazsalemVF** [MichaIng/DietPi#3149]
#### Is your feature request related to a problem? Please describe:

- i would be happy to get my esp01215e elecrow 7 inch touch display working with Odroid n2

#### Describe the solution you'd like:

- add the option is display settings
#### Describe alternatives you've considered:

- normal PC screen
#### Additional context

- ...

**Comment by MichaIng** [comment]
@moatazsalemVF 
Many thanks for your request. Gathering any information/guides about how to do that would be helpful as I also need to start from scratch by doing some web searches 😉.

**Comment by MichaIng** [comment]
@moatazsalemVF 
Is it [this](https://www.elecrow.com/7-inch-1024-600-hdmi-lcd-display-with-touch-screen.html) LCD?
It says all drivers are included with the DVD, but it also lists a small number of supported SBCs, not including Odroid N2 🤔.

Since it is a HDMI LCD, EDID auto-detection may apply correct resolution automatically, at last on RPi only the resolution needs to be set: https://www.elecrow.com/wiki/index.php?title=7_Inch_1024*600_HDMI_LCD_Display_with_Touch_Screen

But instructions about how to get touch input running is entirely missing. Probably the DVD shipped with the display provides info about that?

**Comment by MichaIng** [comment]
Marking it as closed until another ping or request states that it doesn't work it your new mainline kernel image either.
