### ISSUE TITLE
can be closed

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#3176]
**Edited: correction**

Can be closed. I did not read the release notes carefully... Haveged was only installed on RPi by DietPi. Probably I have installed haveged on my NanoPi NEO2 manually. My apologies.

~~NanoPi NEO2~~
~~Upgraded from v6.25.3 (stretch) to 6.26.3~~

~~Despite what v6.26.3 release notes state that Haveged has been replaced by rngd it is not the case after I updated tow DietPi systems to v6.26.3 on my NanoPi NEO2.~~

~~Note: on my RPi-zero-w haveged has been replaced !~~

> service --status-all
```
...
[ + ]  haveged
...
```

> apt list --installed
```
...
haveged/oldstable,now 1.9.1-5+deb9u1 arm64 [installed]
...
```

~~N.B. rng-tools seem not to be installed...~~

**Comment by MichaIng** [comment]
@maartenlangeveld 
haveged and rng-tools are two entropy daemons. The first runs on all devices, thus was previously installed on all DietPi systems. rng-tools runs only on devices with proper CPU support but consumes less RAM. Since it is proven to run on RPi (and is default on Raspbian as well), we switched RPis over.
