### ISSUE TITLE
Orange Pi Lite 2

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#3215]
#### Formal device information
- Device name | Orange Pi Lite2
- Official product URL | http://www.orangepi.org/Orange%20Pi%20Lite%202/
- GitHub resource URL (if available) | 
- Image download URL | http://www.orangepi.org/downloadresources/

#### Is the SBC officially supported by the Debian installer?
- Yes

#### If not, is a reliable 3rd party Debian image available for this SBC?
- i recommend armbian

#### If not, are there install instructions for Debian available?

- ...

**Comment by MichaIng** [comment]
@Heblushabus 
Many thanks for your request. The Orange Pi devices are currently out of scope for us to provide own images for. They simply ship too many devices in short time ranges with low build quality* (just what I heard/read, I never tested one myself), compared to others, where we offer images for. This makes keeping up with this manufacturer and dealing with device-related issues too effort intensive.

However, creating our own Orange Pi DietPi system should be quite easy. You already mentioned Armbian as good base image (current mainline kernel, fine bootloader+firmware setup, though not sure about things like GPU/VPU features...).
```
bash -c "$(curl -s https://raw.githubusercontent.com/MichaIng/DietPi/dev/PREP_SYSTEM_FOR_DIETPI.sh)"
```
- Follow onscreen instructions, choose model: `'22' ': Generic device (unknown to DietPi)'`
- Either reboot to boot into DietPi directly, or shutdown and create an image first:
```
bash -c "$(curl -s https://raw.githubusercontent.com/MichaIng/DietPi/dev/.meta/dietpi-imager)"
```
- Follow onscreen instructions again. Choose to create an SDcard image, when ask, since Clonezilla only works on x86_64.

I mark this issue as closed. If someone wants to shares his/her images, I am willing to provide them as community image(s) with credits from our server and download page.
