### ISSUE TITLE
RPi4 | Implement EEPROM firmware update

### ISSUE THREAD

**Issue by trueaspects** [MichaIng/DietPi#3217]
#### Is your feature request related to a problem? Please describe:

- I could not use rpi-eeprom-update to update firmware on Rpi4.

I was able to install eeprom, but when I run rpi-eeprom-update I get the following:

/usr/bin/rpi-eeprom-update: 221: /usr/bin/rpi-eeprom-update: strings: not found
/usr/bin/rpi-eeprom-update: 425: [: Illegal number:
/usr/bin/rpi-eeprom-update: 502: [: Illegal number:
BOOTLOADER: up-to-date
CURRENT: Fri 10 May 2019 06:40:36 PM UTC (1557513636)
date: invalid date ‘@’
 LATEST:  ()
VL805: up-to-date
CURRENT: 000137ab
 LATEST: 000137ab
 
#### Describe the solution you'd like:

- To be able to update the firmware on Rpi4.

#### Describe alternatives you've considered:

- Only alternative is to install raspbian, install rpi-eeprom-update, update, and then switch back. 

#### Additional context

- Rpi4 now updates firmware differently from prior Rpi as it is now directly on the Rpi rather than on the SD card. It would be great to be able to update firmware from dietpi. 

https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md

**Comment by MichaIng** [comment]
@trueaspects 
Many thanks for providing this info. I was not aware of the EEPROM on RPi4 yet, of course we should have the `rpi-eeprom` package installed on RPi4 then by default.

I am not yet sure how to handle this in regards to lower RPi models:
- `rpi-eeprom` installs a service that runs on every boot and checks for EEPROM updates. This of course, as well as the whole package, is an unnecessary overhead on all other RPi models.
- We could keep the package installed but mask the service and run the updates from within our own boot scripts.
- We could check the RPi model and purge `rpi-eeprom` on all non-RPi4 models, but this breaks the possibility to switch the SDcard without loosing full features. But probably it is enough to check and install the package again when choosing the "Update firmware" option from dietpi-config on RPi4?
- A strong reason to not have it installed by default, but targeted when RPi4 is detected, is the `python` dependency... This installs outdated EOL Python 2, rarely required for anything else, taking unnecessary disk space and package upgrade effort...

Another larger dependency, the `strings` call that failed in your case is due to missing [binutils](https://packages.debian.org/buster/binutils), which has been forgotten to add as dependency.

This as well causes your error, please run `apt install binutils` to be able to run the EEPROM update successfully. We need to report this to RPi devs/maintainers to add this to the packages dependency list, if there is no way to avoid using the `strings` command.

> Rpi4 now updates firmware differently from prior Rpi as it is now directly on the Rpi rather than on the SD card. It would be great to be able to update firmware from dietpi.

Note that this is only about the bootloader, all other firmware, kernel, device tree, overlays, VC drivers/libs/binaries are still installed the same way.

**Comment by trueaspects** [comment]
@MichaIng 
Perhaps the compromise should be that so long as we can install rpi-eeprom and run it on our own, it doesn't need to be pre-installed since all other RPi models do not need it, and it uses outdated dependencies.  

However, I have a feeling that many, if not all, future RPi models may be using rpi-eeprom.

**Comment by MichaIng** [comment]
@trueaspects 
> However, I have a feeling that many, if not all, future RPi models may be using rpi-eeprom.

Jep, I am pretty sure about that.

> Perhaps the compromise should be that so long as we can install rpi-eeprom and run it on our own, it doesn't need to be pre-installed since all other RPi models do not need it, and it uses outdated dependencies.

I will open an issue on RPi repo to add `binutils` as package dependency, so installing `rpi-eeprom` and running the update will then work without the need to manually install `binutils` as well.
**EDIT done: https://github.com/RPi-Distro/repo/issues/156**

I think its okay to install it on firstrun setup, if done on an RPi4, as well as when running firmware update from dietpi-config manu. For RPi4 it is important enough IMO.

**Comment by MichaIng** [comment]
PR up: #3222

**Comment by MichaIng** [comment]
@trueaspects 
Do you know if the `rpi-eeprom` package is pre-installed and automatic update service on boot is enabled by default on fresh Raspbian?

I am trying to evaluate how save this flash/update process can be considered. If this is done on boot by default on RPi4, then it can be considered as very safe and we can apply it as well non-interactively. However if it is not, then I am thinking if we should never do this non-interactively but instead give RPi4 users a hint how to run EEPROM updates but to read into the topic first to know how to do emergency recovery etc.

**Comment by trueaspects** [comment]
@MichaIng 

If I recall correctly, I installed/used raspbian lite and rpi-eeprom was already installed.  However, I do not recall whether the update service on boot was enabled by default, but I would guess yes, because all the guides tell you how to disable it and then re-enable it, rather than how to enable it.

**Comment by MichaIng** [comment]
@trueaspects 
Just rechecked the Raspbian image and indeed this exists:
`/etc/systemd/system/multi-user.target.wants/rpi-eeprom-update.service` => `/lib/systemd/system/rpi-eeprom-update.service`

So the service is enabled by default and we can assume this being safe to run non-interactively. Hence I will add it to firstrun installs and next dietpi-update patch to be installed automatically on RPi4. Especially the VL805 USB drivers are subject ob certain energy/speed balance/rework which hence affects heat emissions as well, so nothing that I am keen to have users run outdated versions.
