### ISSUE TITLE
 [  OK  ] DietPi-PREP | Completed, disk can now be saved to .img for later use,

### ISSUE THREAD

**Issue by chips023** [MichaIng/DietPi#3229]
[  OK  ] DietPi-PREP | Completed, disk can now be saved to .img for later use, or, reboot system to start first run of DietPi.

How can I save img firmware in this step? Can someone give me a document step? Thank you

**Comment by MichaIng** [comment]
@hifitime 
Generally you can clone the drive which holds the DietPi OS with any method from any external system. However to create an img file with minimal size (instead of size that matches the whole drive), it makes sense to shrink file system + partition(s) to a minimum first.

We created a script for that. If you have another DietPi system, plug the drive/SDcard there and run:
```
bash -c "$(curl -sSL https://raw.githubusercontent.com/MichaIng/DietPi/dev/.meta/dietpi-imager)"
```
- Select the drive which holds the fresh DietPi
- Choose whether to create a Clonezilla-based installer image (experimental) or a ready-to-run img file, i.e. to flash to SDcard and go (recommended currently, as proven to work well)
- Select the root partition (usually the last one)
- Give it a reasonable name, note that it is currently mainly for internal use, hence for creating our official images.

The script will shrink the root file system and partition to the minimum size, then uses `dd` to clone all to an img file and wraps it as 7zip archive with hashes and our readme.

**Comment by chips023** [comment]
OK, I'll try. Thank you for your help

**Comment by chips023** [comment]
![无标题](https://user-images.githubusercontent.com/37332924/69011361-9c500d80-09a4-11ea-91a7-b0c2f058f296.jpg)
![无标题3](https://user-images.githubusercontent.com/37332924/69011364-9fe39480-09a4-11ea-92e7-b906bc25f83c.jpg)


**How can I choose this step? What does this mean? I don't quite understand. Please clarify it for me. Thank you very much**

**Comment by MichaIng** [comment]
@hifitime 
You have to select "Drive" as source and "dd" as creation method. And note that you need to run this from an external DietPi system. You cannot create an image of a running system.

**Comment by chips023** [comment]
![1730684289](https://user-images.githubusercontent.com/37332924/69356092-dcbdcd00-0cbd-11ea-83fd-d912d061e1ee.jpg)

	
I plugged in the SD card that installed the dietpi system in another system running dietpi, but how do I choose when I get to this step? thank you.

**Comment by chips023** [comment]
Oh, I got it. This script is really good.

**Comment by MichaIng** [comment]
@hifitime 
Ok great, In the first place "Drive" needs to be selected to select the SDcard then.

The GUI for sure requires some fine tuning. It is still under heavy development 😅. When we find some time we'll add some main overview page from where source and target type etc can be selected and changed and all info filled, then when everything is as desired, hitting "Run" will do the rest. So if anything was selected wrong accidentally of because not 100% clear explained, one will not need to rerun from start 😉.
