### ISSUE TITLE
Asus Tinker Board | Fresh image fails to boot

### ISSUE THREAD

**Issue by rpecb** [MichaIng/DietPi#3236]
Can't start fresh installation of dietpi on TB. I tried full format of sdcard (`dd if=/dev/zero of=/dev/<sd card>`) it didn't help. Other systems (TinkerOS, Armbian) start up successfully.
Image checksums match.

#### Required Information
- DietPi version | 6.25
- SBC device | Asus TinkerBoard (non-S)
- SDcard used | SanDisk Ultra microSDHC 32GB 10 Class UHS-I [SDSQUNS-032G-GN3MN]

#### Steps to reproduce
1. Flash image to sd card with balena etcher (on Mac OS Catalina)
2. Power on device

#### Expected behaviour
- Success boot

#### Actual behaviour
- No any output on HDMI, just blinking leds, after a while they stop blinking

**Comment by MichaIng** [comment]
@rpecb 
Many thanks for your report.

Are you able to SSH into the machine?

**Comment by rpecb** [comment]
> @rpecb
> Many thanks for your report.
> 
> Are you able to SSH into the machine?

no, device does not appear on the network.
behaviour looks like TB tries to start a couple of times, then it turns off

**Comment by MichaIng** [comment]
Strange, since in other cases it boots fine :thinking:.

There was another similar case, although on older image (Stretch-based): #2533

The new Buster-based image is some months old and reported ATB installs raised meanwhile, which I take as a general prove of function: https://github.com/MichaIng/DietPi/issues/2977#issuecomment-518005651

Did you try another flash method then Ether? I remember another case where this had some issue lately...
E.g. `dd if=/path/to/DietPi_v6.25_ASUSTB-ARMv7-Buster.img of=/dev/<sd card>`

**Comment by MichaIng** [comment]
I mark this issue as closed, since it has been a while. A new image will be created the next days.
