### ISSUE TITLE
Image | PINE H64

### ISSUE THREAD

**Issue by unixino** [MichaIng/DietPi#3286]
PINE H64 Ver. B
https://www.pine64.org/pine-h64-ver-b/
https://wiki.pine64.org/index.php/PINE_H64

**Comment by MichaIng** [comment]
@unixino 
Many thanks for your request. I'll see if I can create an initial image with new device definition, during my current image update/creation race: #2979

**Comment by MichaIng** [comment]
@unixino 
New image for Pine H64, based on Armbian Buster, ready for testing: https://dietpi.com/downloads/testing/DietPi_PineH64-ARMv8-Buster.7z
Note that this is not explicitly for Model B but should work there as well due to vastly same hardware. WiFi must be taken an eye on since Model A has no fixed onboard WiFi.
