### ISSUE TITLE
default smb.conf :  create mask = 0775 --> create mask = 0664

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#3580]
When installing samba through dietpi-software `/etc/samba/smb.conf` config file is created.
It contains `create mask = 0775` where I guess `create mask = 0664` fit better.

current smb.conf mask entries
```
        create mask = 0775
        directory mask = 0775
```

preferred smb.conf mask entries
```
        create mask = 0664
        directory mask = 0775
```

**Comment by MichaIng** [comment]
Generally I agree. However there is the little chance that users have executables there and this would break execute permissions, what do you think?

**Comment by maartenlangeveld** [comment]
It only applies to new files created on the client... but since I have change the smb.conf config file myself it''s not a big deal to change the default values.

**Comment by MichaIng** [comment]
Ah yes I was not thinking through. Since this is only about the server-side permissions, when required one can add execute permissions manually per-file anyway. Only for the client-side it is an argument to keep execute permissions by default since one cannot change per-file permissions on a samba mount. So your suggestion makes sense 👍.

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi/commit/d9daf32ccb479755e23596098b661f1dca2a277a
Changelog: https://github.com/MichaIng/DietPi/commit/7c4284b5a285000112c86f4a7577b17cca7e80a4

**Comment by maartenlangeveld** [comment]
Thanks !
