### ISSUE TITLE
Dietpi-benchmark - Syntax error

### ISSUE THREAD

**Issue by dbambus** [MichaIng/DietPi#3672]
Hey, 

I got an error with dietpi-benchmark tool on an freshly formated ext4 SSD drive connected via USB3.0 with an external power supply, but also on other drives. The console output is attached to the issue.

#### Required Information
- DietPi version 6.31.2 Official
- Distro version 10.4
- Kernel version cat /etc/debian_version
- SBC model Rpi4 4GB
- Power supply used Custom 5V/6A
- SDcard used SanDisk Extreme A2 64GB

#### Additional Information (if applicable)
- Software title Dietepi-Benchmark

#### Steps to reproduce
1. Mount Drive via dietpi-drive_manager
2. Start R/W Benchmark with default values on the mounted Drive

#### Expected behaviour
- Run Benchmark successfully

#### Actual behaviour
```
root@DietPi:~# dietpi-drive_manager
[ INFO ] DietPi-Drive_Manager | Detecting drives, please wait...
[ INFO ] DietPi-Drive_Manager |  - Detected mounted drive: /dev/mmcblk0p2 > /
[ INFO ] DietPi-Drive_Manager |  - Detected mounted drive: /dev/mmcblk0p1 > /boot
[ INFO ] DietPi-Drive_Manager |  - Detected mounted drive: /dev/sdb1 > /mnt/5TB
[ INFO ] DietPi-Drive_Manager |  - Detected unmounted drive: /dev/sda1
[  OK  ] DietPi-Drive_Manager | mkdir -p /mnt/SSD128
[  OK  ] DietPi-Drive_Manager | mount /dev/sda1 /mnt/SSD128
[ INFO ] DietPi-Drive_Manager | Detecting drives, please wait...
[ INFO ] DietPi-Drive_Manager |  - Detected mounted drive: /dev/mmcblk0p2 > /
[ INFO ] DietPi-Drive_Manager |  - Detected mounted drive: /dev/mmcblk0p1 > /boot
[ INFO ] DietPi-Drive_Manager |  - Detected mounted drive: /dev/sdb1 > /mnt/5TB
[ INFO ] DietPi-Drive_Manager |  - Detected mounted drive: /dev/sda1 > /mnt/SSD
dumpe2fs 1.44.5 (15-Dec-2018)
[ SUB1 ] DietPi-Services > stop 
[  OK  ] DietPi-Services | ncc maintenance:mode --on
[  OK  ] DietPi-Services | stop : cron
[  OK  ] DietPi-Services | stop : noip2
1932 (process ID) old priority 0, new priority -19
[ SUB2 ] DietPi-Services > stop 
[  OK  ] DietPi-Services | stop : cron
[  OK  ] DietPi-Services | stop : noip2
[  OK  ] DietPi-Services | stop : home-assistant
[ INFO ] DietPi-Benchmark | Performing Read/Write benchmark on /mnt/SSD/benchmark.file, please wait...
[ INFO ] DietPi-Benchmark | Testing Seq Write Speed (10 MiB)
/boot/dietpi/func/dietpi-benchmark: line 226: 10485760 / 0.17989 / 1024 / 1024 : syntax error: invalid arithmetic operator (error token is ".17989 / 1024 / 1024 ")
dumpe2fs 1.44.5 (15-Dec-2018)

```

**Comment by MichaIng** [comment]
Many thanks for your report!
#### Fixed with: https://github.com/MichaIng/DietPi/commit/44f941caf78bd850a7abcc0260af0b71b272b182
#### Changelog: https://github.com/MichaIng/DietPi/blob/dev/CHANGELOG.txt
#### Quick fix (as well added as MOTD hack):
```
[[ $G_DIETPI_VERSION_SUB == 31 && -w '/boot/dietpi/func/dietpi-benchmark' ]] && grep -q '$temp_bytes_result / $temp_time_result' /boot/dietpi/func/dietpi-benchmark && sed -i 's|$temp_bytes_result / $temp_time_result|$temp_bytes_result * 100000 / $(printf '%.0f' "${temp_time_result}e5")|' /boot/dietpi/func/dietpi-benchmark
```
- `dd` always returns the time with the same precision so we can eliminate the decimal point (convert it to int) by multiplying with 100,000.
- This needs to be compensated of course. To prevent rounding errors in final result, multiplication always needs to be done before division and sadly it cannot be merged since there are no shared multiples between powers of 10 and powers of 2. Not beautiful, but still much faster compared to using an external calculator like `bc`.

... Hmm now I see since we use `mawk` anyway, we should just do everything in one step with it. The values/variables are not used on anywhere else.
___________
Further simplification since awk/mawk can do everything in one step: https://github.com/MichaIng/DietPi/commit/a1a31baebb5c964a36faf916866fa2acdc261710
Bonus is correct integer rounding (nearest even) compared to bash arithmetic which always rounds down, cutting away division remainder.
