### ISSUE TITLE
Prevent Predictable Interface Names

### ISSUE THREAD

**Issue by theAkito** [MichaIng/DietPi#3674]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
v6.30.0 (before my fix)
v6.31.2 (after my fix)
- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
Debian Bullseye
- Kernel version | `uname -a`
Linux hostname 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
Raspberry Pi 3 B
- Power supply used | (EG: 5V 1A RAVpower)
Custom
- SDcard used | (EG: SanDisk ultra)
Transcend 32GB

#### Steps to reproduce

1. Replace repository sources with newer ones.
1. `full-upgrade` from Buster to Bullseye.

#### Expected behaviour

1. Ethernet's interface name should remain `eth0`.

#### Actual behaviour

1. See that `ln -s /dev/null /etc/systemd/network/99-default.link` is already set.
1. `eth0` is still renamed to `enxMAC_ADDRESS` without user's consent.

#### Extra details

* I fixed it by appending `net.ifnames=0` to `/boot/cmdline.txt`.
* I've already done the upgrade from Buster to Bullseye many times. Never had this issue before. Don't know why it happened now.

**Comment by MichaIng** [comment]
Many thanks for your report.

Yes I recognised it as well and new images since DietPi v6.27 contain all related configs to assure predictable names: https://github.com/MichaIng/DietPi/commit/017aa0bff8aa984152f6a72ba7dbf83d32104c8c

With this `/etc/systemd/network/99-default.link` might not be required anymore when the cmdline option and/or the udev rule are set, but AFAIK it as well assures that systemd-networkd is not configuring anything if enabled/started by accident or some software package, which would collide with ifupdown.
