### ISSUE TITLE
Wifi not working on a Pi 4

### ISSUE THREAD

**Issue by CactiChameleon9** [MichaIng/DietPi#3685]
#### Required Information
- DietPi version | CORE=6 SUB=31 RC=2 master MichaIng
- Distro version | buster
- Kernel version | Linux DietPi 5.4.51-v71+ #1326 SPM Fri Jul 17 10:51:17 BST 2020 arm71 GNU/Linux
- SBC model | RPi4
- Power supply used | A random USB port that provides enough current for the pi 4 not to shut down under load
- SDcard used | SanDisk ultra 64GB

#### Steps to reproduce
Install dietpi on a pi 4 and following usual steps with connecting to wifi, reboot and wifi will not work

#### Expected behaviour
Wifi should work as normal

#### Actual behaviour
Wifi does not work at all
Wifi "Not Found" in dietpi-config network after first reboot

#### Extra details
A lot of updates to do with firmware occurred during first update
Same issue with 64bit dietpi

**Comment by MichaIng** [comment]
Many thanks for your report.

How did you enable WiFi? Note that `AUTO_SETUP_NET_WIFI_ENABLED=1` needs to be set in `/boot/dietpi.txt`, respectively `dietpi.txt` in the FAT partition that can be mounted on Windows, to enable WiFi auto-configuration on first boot. Else WiFi modules will be disabled for next reboot. Otherwise you can use `dietpi-config` to enable WiFi then, which also assures that onboard WiFi and modules are kept active/loaded on next boot.

To check whether onboard WiFi has been successfully enabled: `grep 'dtoverlay=disable-wifi' /boot/config.txt` must not print anything.

Ah one thing I can imaging:
- First boot, you have not altered dietpi.txt to auto-configure WiFi => onboard WiFi is disabled **for next boot**.
- You use `dietpi-config` to configure WiFi but do not re-enable onboard WiFi => WiFi scanning etc works, since onboard WiFi is currently active, but after reboot it is inactive.
- Solution: Take care that `Onboard WiFi : [On]` is set, else it will not be available on next boot.
- Seems not too intuitive, however I don't know how to do it better since onboard WiFi cannot be enabled/disabled within the same session, but only for next boot. And even with onboard WiFi, one might want to use a stronger external adapter and then disable onboard WiFi instead 🤔. However larger network setup rework is in progress, probably I find a way to make this more intuitive.

**Comment by CactiChameleon9** [comment]
Oh... so I probably did something wrong then :D. Ill have a look and get back to you.

**Comment by CactiChameleon9** [comment]
On boot it states that a valid connection was found but systemd-timesyncd never completes.

**Comment by CactiChameleon9** [comment]
Yeah... wifi works now. Thanks. I was wondering what onboard WiFi was, that makes sense now that it is the wifi on the board. Maybe inbuilt would be a better word?

**Comment by MichaIng** [comment]
> Maybe inbuilt would be a better word?

"onboard" is actually the right word to say that is it baked into the (main)board/PCB, you say onboard audio and onboard Ethernet as well. Probably I find a way to auto-detect when the onboard adapter is configured and automatically enable/keep it enabled then.

**Comment by CactiChameleon9** [comment]
Fair enough - onboard it is. Also that would be cool if that feature could get implemented.

**Comment by Joulinar** [comment]
Hi guys,

I guess we can close the topic?

**Comment by MichaIng** [comment]
From my end yes, I'll have it in mind when coding the new menus.

**Comment by CactiChameleon9** [comment]
Yep, you can close this. Thanks for all of your help
