### ISSUE TITLE
Warning/error when viewing results of dietpi-drive_manager

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#3691]
Checking/repairing Dietpi root volume suing dietpi-drive_manager gives following warning/error:

`Please pass 'fsck.mode=force' on the kernel command line rather than creating /forcefsck on the root file system.`

```
root@DietPi:~# journalctl -t systemd-fsck
-- Logs begin at Wed 2020-07-22 17:20:43 CEST, end at Wed 2020-07-22 17:22:17 CEST. --
Jul 22 17:20:43 DietPi systemd-fsck[100]: Please pass 'fsck.mode=force' on the kernel command line rather than creating /forcefsck on the root file system.
Jul 22 17:20:44 DietPi systemd-fsck[100]: e2fsck 1.44.5 (15-Dec-2018)
Jul 22 17:20:44 DietPi systemd-fsck[100]: Pass 1: Checking inodes, blocks, and sizes
Jul 22 17:21:00 DietPi systemd-fsck[100]: Pass 2: Checking directory structure
Jul 22 17:21:09 DietPi systemd-fsck[100]: Pass 3: Checking directory connectivity
Jul 22 17:21:10 DietPi systemd-fsck[100]: Pass 4: Checking reference counts
Jul 22 17:21:11 DietPi systemd-fsck[100]: Pass 5: Checking group summary information
Jul 22 17:21:11 DietPi systemd-fsck[100]: rootfs: 111294/925520 files (0.2% non-contiguous), 1703970/3758080 blocks
Jul 22 17:21:16 DietPi systemd-fsck[168]: Please pass 'fsck.mode=force' on the kernel command line rather than creating /forcefsck on the root file system.
Jul 22 17:21:17 DietPi systemd-fsck[168]: fsck.fat 4.1 (2017-01-24)
Jul 22 17:21:17 DietPi systemd-fsck[168]: /dev/mmcblk0p1: 305 files, 108479/516190 clusters
```

**Comment by MichaIng** [comment]
Jep, `/forcefsck` is deprecated, but sadly there is no "modern" alternative to force an fsck only for the next boot. Adding that kernel cmdline entry is not even possible on all devices without larger effort and it needs to be removed manually afterwards. So we'd need to figure out how to safely apply it on all devices, need to place a flag file and place + enable a service for next reboot which checks for that flag file, removes the cmdline entry, disables and removes itself... Completely unhandy, nothing I'm wasting time on 😉.

Theoretically tune2fs can be used to force systemd-fsck for next reboot, but it only supports ext4 file system and in cases it can create a boot loop:
1. initramfs does fsck because of kernel cmdline, does reboot
2. After reboot systemd-fsck does not find the tmpfs flag from initramfs and does fsck because of tune2fs flag, then reboots
3. initramfs does again fsck because of cmdline...
4. ...and so on... 

Not sure if there is now a mechanism to prevent this, however I ram into this once with my RPi. So there is a strong need for a single time flag which removes itself, and `/forcefsck` is the only one that exists and still works on Debian Bullseye/testing.

**Comment by maartenlangeveld** [comment]
Ok, thanks MichaIng ! Makes sense.
