### ISSUE TITLE
dietpi.txt  |  Update Optimized and Additional Linux Software for installation

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#374]
@Fourdee 

please update 

`#DietPi-Optimized Software to automatically install | Requires AUTO_Install_Index=1`

and 

`#Linux Additional Software to automatically install | Requires AUTO_Install_Index=1`

in `dietpi.txt` , so we can do  AUTO_Install all the new Software since v115.

**Comment by Fourdee** [comment]
@k-plan 

I keep the dietpi.txt file upto date on github. We no longer patch existing installation dietpi.txt automation entries, as it was pointless to add the option after 1st run.

Simply grab the latest dietpi.txt from https://github.com/Fourdee/DietPi/blob/master/dietpi.txt. It contains all the current and available program automation options.
Write image, copy to /boot/, enable your options, job done.

**Comment by k-plan** [comment]
@Fourdee 

```
#Linux Additional Software to automatically install | Requires AUTO_Install_Index=1
#   1=install
AUTO_DietpiSoftware_Install_VIMFULL=0
AUTO_DietpiSoftware_Install_SSHCLIENT=0
# - This will be automatically mounted to /mnt/samba. Use DietPi-Config settings section in this file to enter your details (SambaClient_*)
AUTO_DietpiSoftware_Install_SMBCLIENT=0
# - This will be automatically mounted to /mnt/ftp_client. Use DietPi-Config settings section in this file to enter your details (curlftpfs_*)
AUTO_DietpiSoftware_Install_CURLFTPFS=0
AUTO_DietpiSoftware_Install_GITCLIENT=0
AUTO_DietpiSoftware_Install_BUILDESSENTIAL=0
AUTO_DietpiSoftware_Install_ALSABASE=0
AUTO_DietpiSoftware_Install_XSERVERXORG=0
AUTO_DietpiSoftware_Install_FFMPEG=0
AUTO_DietpiSoftware_Install_ORACLEJAVA=0
AUTO_DietpiSoftware_Install_NODEJS=0
AUTO_DietpiSoftware_Install_LOGGING_RSYSLOG=0
```

No mc, tcpdump, iperf, MTR-Tiny ... and so on

As far as I can remember, you will do a re-image for all devices in v.120. Will be nice to see it in    there .

> Simply grab the latest dietpi.txt from https://github.com/Fourdee/DietPi/blob/master/dietpi.txt. It contains all the current and available program automation options.
> Write image, copy to /boot/, enable your options, job done.

Nice hint, thank you very much. 👍 

But didn't help in the moment for mc, iperf, tcpdump, mtr-tiny.

**Comment by Fourdee** [comment]
@k-plan 

> mc, iperf, tcpdump, mtry-tiny

Cheers, I'll take a look

**Comment by xenfomation** [comment]
@Fourdee  @k-plan 

I may be jumping in where I shouldn't have been, but I remember one of my first tasks was to help add these:

mc, iperf, tcpdump, mtr, vim, vim-timy, etc

I just wanted to see if these are appearing in the builds or if I need to revisit dietpi-software as I have the following as of build 118/119 (committed, etc):

### Network Utilities```

 [ ]            ────Network Tools─────────────────────────────▒   │  
                │    [ ] iftop      Displays bandwidth usage information.         ▒   │  
                │    [ ] IPTraf     Interactive Colorful IP LAN Monitor.          ▒   │  
                │    [_] Iperf      Internet Protocol bandwidth measuring tool.   ▒   │  
                │    [_] MTR-Tiny   Full screen ncurses traceroute tool.          ▒   │  
                │    [*] nLoad      Realtime console network usage monitor.       ▒   │  
                │    [ ] tcpdump    Command-line network traffic analyzer.        ▒   │    

```

### MC Editors Etc
```

 [ ]            ────Editors────────────────────────────────── ▒   │  
                │    [ ] Emacs      GNU Emacs editor.                             ▒   │  
                │    [ ] Jed        Editor for programmers.                       ▒   │  
                │    [*] Vim        Vi Enhanced Text Editor.                      ▒   │  
                │    [ ] Vim-Tiny   Compact release of Vim.                       ▒   │                

```

Point is -- to both of you, if I missed adding any utilities -- please let me know and I will adjust accordingly.  

The original list of software (CLI or Otherwise) was 60+ tiny, useful things we all used.  I do remember in talking with @rhkean that I tripped down to "test Vim-Tiny" as I was getting familiar with the dietpi-software codes and flags.

Let me know, @Fourdee, if I need to go back in and add, check flags, or clean-up code for:

### Network tools 
telnet
iperf (really iperf3)
traceroute & tracepath
whois / nslookup
nmap
rfkill
mtr/mtr-tiny

Utilites:
mkisofs
makepassword
openssl utils
hdparm
dtrx (compression utility)


... much more, but then again -- just seeing if I missed anything.
```

**Comment by xenfomation** [comment]
I have no idea how I closed this ticket?  AUGH.

SO -- 

@Fourdee @k-plan

I may be jumping in where I shouldn't have been, but I remember one of my first tasks was to help add these:

mc, iperf, tcpdump, mtr, vim, vim-timy, etc

I just wanted to see if these are appearing in the builds or if I need to revisit dietpi-software as I have the following as of build 118/119 (committed, etc):

###Network Utilities

```
[ ] ────Network Tools─────────────────────────────▒ │

│ [ ] iftop Displays bandwidth usage information. ▒ │

│ [ ] IPTraf Interactive Colorful IP LAN Monitor. ▒ │

│ [] Iperf Internet Protocol bandwidth measuring tool. ▒ │

│ [] MTR-Tiny Full screen ncurses traceroute tool. ▒ │

│ [*] nLoad Realtime console network usage monitor. ▒ │

│ [ ] tcpdump Command-line network traffic analyzer. ▒ │
```

### MC Editors Etc

```

[ ] ────Editors────────────────────────────────── ▒ │

│ [ ] Emacs GNU Emacs editor. ▒ │

│ [ ] Jed Editor for programmers. ▒ │

│ [*] Vim Vi Enhanced Text Editor. ▒ │

│ [ ] Vim-Tiny Compact release of Vim. ▒ │

```

Point is -- to both of you, if I missed adding any utilities -- please let me know and I will adjust accordingly.  

The original list of software (CLI or Otherwise) was 60+ tiny, useful things we all used.  I do remember in talking with @rhkean that I tripped down to "test Vim-Tiny" as I was getting familiar with the dietpi-software codes and flags.

Let me know, @Fourdee, if I need to go back in and add, check flags, or clean-up code for:

### Network tools

telnet
iperf (really iperf3)
traceroute & tracepath
whois / nslookup
nmap
rfkill
mtr/mtr-tiny

Utilites:
mkisofs
makepassword
openssl utils
hdparm
dtrx (compression utility)

... much more, but then again -- just seeing if I missed anything.

**Comment by Fourdee** [comment]
Ok, updated the missing dietpi.txt automation entries ^^.

@xenfomation 

> Let me know, @Fourdee, if I need to go back in and add, check flags, or clean-up code for:

hdparm is installed and configured on DietPi by default.

As for the rest, you can check the current list here:
https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L7882-L7915. Then you can choose if you want to add any more in.

**Comment by k-plan** [comment]
@Fourdee 

>  Ok, updated the missing dietpi.txt automation entries ^^.

### Testing:

```
root@Rpi_3-TEST:~# cat /boot/dietpi.txt
 . . .
 #Automated Software Installations:
#       0=Disabled
#       1=DietPi-Automation (use software lists below to select the software you require)
AUTO_Install_Index=1
 . . .
#Linux Additional Software to automatically install | Requires AUTO_Install_Index=1
#   1=install
AUTO_DietpiSoftware_Install_VIMFULL=0
AUTO_DietpiSoftware_Install_SSHCLIENT=0
# - This will be automatically mounted to /mnt/samba. Use DietPi-Config settings section in this file to enter your details (SambaClient_*)
AUTO_DietpiSoftware_Install_SMBCLIENT=0
# - This will be automatically mounted to /mnt/ftp_client. Use DietPi-Config settings section in this file to enter your details (curlftpfs_*)
AUTO_DietpiSoftware_Install_CURLFTPFS=0
AUTO_DietpiSoftware_Install_GITCLIENT=0
AUTO_DietpiSoftware_Install_BUILDESSENTIAL=0
AUTO_DietpiSoftware_Install_ALSABASE=0
AUTO_DietpiSoftware_Install_XSERVERXORG=0
AUTO_DietpiSoftware_Install_FFMPEG=0
AUTO_DietpiSoftware_Install_ORACLEJAVA=0
AUTO_DietpiSoftware_Install_NODEJS=0
AUTO_DietpiSoftware_Install_VIFM=0
AUTO_DietpiSoftware_Install_QUITERSS=0
AUTO_DietpiSoftware_Install_GNUEMACS=0
AUTO_DietpiSoftware_Install_JED=1
AUTO_DietpiSoftware_Install_VIMTINY=0
AUTO_DietpiSoftware_Install_MC=1
AUTO_DietpiSoftware_Install_IFTOP=0
AUTO_DietpiSoftware_Install_IPTRAF=0
AUTO_DietpiSoftware_Install_IPERF=1
AUTO_DietpiSoftware_Install_MTRTINY=1
AUTO_DietpiSoftware_Install_NLOAD=0
AUTO_DietpiSoftware_Install_TCPDUMP=1
AUTO_DietpiSoftware_Install_LOGGING_RSYSLOG=0
```

```
root@Rpi_3-TEST:~# cat /root/DietPi-Automation.log
cat: /root/DietPi-Automation.log: No such file or directory
```

```
root@Rpi_3-TEST:~# iperf
-bash: iperf: command not found

root@Rpi_3-TEST:~# mc
-bash: mc: command not found

root@Rpi_3-TEST:~# tcpdump -help
tcpdump version 4.6.2
libpcap version 1.6.2
OpenSSL 1.0.1k 8 Jan 2015

root@Rpi_3-TEST:~# mtr --v
mtr 0.85

```

![160605-0002](https://cloud.githubusercontent.com/assets/17237601/15805829/88e148c8-2b35-11e6-8f07-6abbd5e5d65b.gif)
![160605-0003](https://cloud.githubusercontent.com/assets/17237601/15805832/940bf78e-2b35-11e6-8c69-f85e518f3765.gif)
![160605-0001](https://cloud.githubusercontent.com/assets/17237601/15805834/9ecace70-2b35-11e6-8514-e47257da0f17.gif)

---

@xenfomation 

> Point is -- to both of you, if I missed adding any utilities -- please let me know and I will adjust accordingly

I don`t miss anything. Only the option to automated installation your integrated tools in`dietpi.txt`.

**Comment by Fourdee** [comment]
@k-plan 
Thanks for the test results :+1:  I'll take a look.

**Comment by Fourdee** [comment]
@k-plan 
MC should be MIDNIGHTCOMMANDER.
iperf is missing the installation code in dietpi-software.

**Comment by Fourdee** [comment]
@k-plan 
Done. I'll mark this as closed, please reopen if needed.

**Comment by k-plan** [comment]
@Fourdee 

only tested with mc, iperf, tcpdump and mtr.

![160612-0001](https://cloud.githubusercontent.com/assets/17237601/15991567/8244f524-30b6-11e6-9194-3b84c7281728.gif)

![160612-0002](https://cloud.githubusercontent.com/assets/17237601/15991569/8d56d57c-30b6-11e6-8728-1deb919580dc.gif)

```
root@RPi-UniFi:~# mtr --v
mtr 0.85

```

Sorry, but mtr-tiny is missing in `dietpi-uninstall`

**Comment by Fourdee** [comment]
@k-plan 

> Sorry, but mtr-tiny is missing in dietpi-uninstall

Thanks, i'll take a look. :+1:

**Comment by Fourdee** [comment]
Fixed, was an issue with the dietpi-software installation flag not being set to completed. Same as the VIFM one:
![image](https://cloud.githubusercontent.com/assets/7077026/16007184/d9a8039e-3168-11e6-89e2-c21410c79d38.png)
