### ISSUE TITLE
DietPi-Software | Switching Ralmlog to #2, leads Sonarr, Lidarr, Radarr to fail

### ISSUE THREAD

**Issue by Joulinar** [MichaIng/DietPi#3819]
@MichaIng 

There is a report on the forum about this issue. https://dietpi.com/phpbb/viewtopic.php?f=11&t=8163

Looks like switching the Log mode leads Sonarr, Lidarr, Radarr to fail. It seems files in `/var/log` are missing after switching to the new log mode. I was able to replicate the issue and indeed creating the files is fixing it. For starting the service, it's enough to have the file created. Even if root is owning the file 😉 
```
touch /var/log/sonarr
systemctl restart sonarr.service
```

I guess it's happen somewhere on migrating data

 ```
DietPi-Software
─────────────────────────────────────────────────────
 Mode: Installing DietPi-RAMlog: minimal, optimised logging

[  OK  ] DietPi-Software | Storing /var/log metadata to disk
[  OK  ] DietPi-Software | Cleaning /var/log mountpoint
[  OK  ] DietPi-Software | Mounting tmpfs to /var/log
[  OK  ] DietPi-Software | Restoring metadata to /var/log tmpfs
```

On my test, I noticed that `/var/log` was totally empty right after log mode switch and before reboot.

```
root@DietPiVM1:/var/log# ls -la
total 4
drwxrwxrwt  2 root root   40 Oct 11 01:29 .
drwxr-xr-x 12 root root 4096 Apr 16 12:07 ..
root@DietPiVM1:/var/log#
```
Probably the restore is not working correctly? 🤔 

As far as I can see, to restore data, just a restart of the ramlog service is triggered. 
https://github.com/MichaIng/DietPi/blob/208ab64c88ce168d2b3af4205544ea66edeacaf4/dietpi/dietpi-software#L6602

Should we not trigger `G_EXEC /boot/dietpi/func/dietpi-ramlog 0` before?

**Comment by MichaIng** [comment]
I think the only thing that is missing is a `/boot/dietpi/func/dietpi-ramlog 0` indeed because the service is already running, hence `systemctl start dietpi-ramlog` is simply without any effect. The installer seems to expect that DietPi-RAMlog was disabled before. Also there is no unmount done.

I think we should assure that the service is stopped. So if it is `systemctl is-active dietpi-ramlog`, run `systemctl stop dietpi-ramlog`, else `dietpi-ramlog 1`. Similarly, if `findmnt /var/log`, `umount -R /var/log` to assure we really clean the dir below the mount point and no the tmpfs.

**Comment by MichaIng** [comment]
This should have fixed it: https://github.com/MichaIng/DietPi/commit/84e2efb175f38b52cf1e62645adc1094d31bacbf
I'll run some tests.
**EDIT: Ran through all scenarios, install, uninstall and reinstall, working fine now.**

Changelog: https://github.com/MichaIng/DietPi/commit/ec95958918e71cf7593a5cefd604d6a77ebcd212

**Comment by Joulinar** [comment]
yep seems to be working now
