### ISSUE TITLE
Cloudshell not show Pihole Stats

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#3992]

**Comment by nonnorm** [comment]
Hello,
As of Pi-hole v5 a database file is used to log queries.  This scene was built with earlier versions in mind, which used text files instead.  Since DietPi doesn't find the text file, it automatically deselects the scene.

**Comment by ghost** [comment]
> Hello,
> As of Pi-hole v5 a database file is used to log queries. This scene was built with earlier versions in mind, which used text files instead. Since DietPi doesn't find the text file, it automatically deselects the scene.

text file is
/var/log/pihole.log
or
/etc/pihole/gravity.list ??

**Comment by nonnorm** [comment]
The file is `/etc/pihole/gravity.list`.

**Comment by MichaIng** [comment]
We'll use the FTL interface directly instead of scraping logs files or the database. That's what the "Faster Than Light" interface is made for 😉.

Here the API: https://docs.pi-hole.net/ftldns/telnet-api/
That can be used via socket file directly as well, e.g. see how Chronometer does it: https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/chronometer.sh#L14-L40
Or PADD: https://github.com/pi-hole/PADD/blob/master/padd.sh#L119-L148

**Comment by MichaIng** [comment]
Pi-hole stats have been fixed: https://github.com/MichaIng/DietPi/commit/8e766d310b0b8e9e6ed42c7b12031eee4dad9cf8

Additionally, in case of failure, the first output line, normally showing time, CloudShell version or uptime, is replaced with an error message, based on step at which the Pi-hole FTL connection failed. So e.g. if Pi-hole has not started yet, if it has stopped again (gracefully), or if it crashed or had an internal error so that connection to the FTL socket failed. In case of failure, the previously obtained data are still shown, below the error message.

I mainly added this for debugging reasons our side, but I think it's useful for users as well.
