### ISSUE TITLE
DietPi-Set_swapfile | zram is not applied on first boot

### ISSUE THREAD

**Issue by Dr0bac** [MichaIng/DietPi#4002]
On fresh dietpi install and before first boot i opened dietpi.txt and edited few lines.

For swap file i entered

`AUTO_SETUP_SWAPFILE_SIZE=1`

and

`AUTO_SETUP_SWAPFILE_LOCATION=zram`

When i go to dietpi_config/Advanced Options

I get this result

![IMG_20201224_003515__01.jpg](https://user-images.githubusercontent.com/43797966/103093985-62682680-45fc-11eb-9715-c9a50c94e745.jpg)

Is this correct output for zram configuration?

Also, where exactly zram keep swapfile? If i understand correctly swap file is located on ram memory and not on sd card or external hdd?

**Comment by MichaIng** [comment]
Many thanks for your report. I'll try to replicate.

The zram implementation does not create a swap "file" but uses the zram block device itself as swap space, similar to a swap partition. Indeed the `dietpi-config` output doesn't look like it worked correctly but default `/var/swap` file was used.

Easiest command to check which swap spaces are really used: `swapon` (without arguments)

**Comment by Dr0bac** [comment]
````
root@DietPi:~# swapon
NAME      TYPE SIZE USED PRIO
/var/swap file   1G   0B   -2
````

how can i change to zram method?

**Comment by Joulinar** [comment]
you can try following `/boot/dietpi/func/dietpi-set_swapfile 1 zram`

**Comment by Dr0bac** [comment]
Thank you. success!

````
root@DietPi:~# swapon
NAME       TYPE      SIZE USED PRIO
/dev/zram0 partition 487M   0B   -2
````
in dietpi-drive_manager i get these two new drives, this is normal behavior after enabling zram?

![fffff](https://user-images.githubusercontent.com/43797966/103107262-4f9c2480-45f1-11eb-9956-1f53dde87a39.png)

**Comment by MichaIng** [comment]
There was indeed a bug in the logic of the script that dropped zram/zram0 dietpi.txt entries. Actually this was to prevent the attempt of removing the `/dev/zram0` block device as if it was an ordinary file, but the dietpi.txt entry was not used at all then, hence was reset to default during first boot setup.
Fixed with: https://github.com/MichaIng/DietPi/commit/8eb0973a7dd8f3c6a7e58b8624a8509eea37fcf2
Changelog: https://github.com/MichaIng/DietPi/commit/c2a699612530c727aac3565e8c29b40b2152271b
