### ISSUE TITLE
RAMlog #2 - where is the syslog?

### ISSUE THREAD

**Issue by Gill-Bates** [MichaIng/DietPi#4109]
A great feature of Dietpi is to write the logs to RAM to save the SD card.

For this purpose the menu `dietpi-software` offers three different options to choose from:

![image](https://user-images.githubusercontent.com/25774289/107876349-c48b2c80-6ec5-11eb-911d-0bdb56fe1c0c.png)

- `RAMlog #1` Seems to be clear: here nothing is written to the SD card at all.
- `Full` I also understand: here Dietpi behaves like an ordinary Linux distribution. All logs taking place inside `/var/log`

But what about `RAMlog #2`? Where can I find the `syslog` on the file system?
```
root@dietpi:/var/log# ls -lh
total 8.0K
-rw-r--r-- 1 root    root      0 Feb 14 10:17 AdGuardHome.err
-rw-r--r-- 1 root    root      0 Feb 14 09:26 AdGuardHome.out
-rw-r--r-- 1 root    root      0 Feb 13 23:53 alternatives.log
drwxr-xr-x 2 root    root    100 Feb 13 23:52 apt
-rw-rw---- 1 root    utmp      0 Feb 14 09:26 btmp
-rw-r--r-- 1 root    root      0 Feb 13 23:53 dpkg.log
-rw-r----- 1 root    adm       0 Feb 14 00:00 fail2ban.log
-rw-r----- 1 root    adm       0 Feb 13 17:39 fail2ban.log.1
-rw-r--r-- 1 root    root      0 Feb 13 23:17 fontconfig.log
-rw-rw-r-- 1 root    utmp    292 Feb 14 13:03 lastlog
drwxr-xr-x 2 mongodb mongodb  60 Feb 13 17:54 mongodb
drwxr-xr-x 2 root    adm      80 Feb 13 23:44 nginx
-rw------- 1 root    root      0 Feb 14 10:17 php7.3-fpm.log
drwx------ 2 root    root     40 Jan 18 17:28 private
drwxr-x--- 3 unifi   unifi   100 Feb 13 17:55 unifi
-rw-rw-r-- 1 root    utmp    384 Feb 14 13:03 wtmp
```

**Comment by Joulinar** [comment]
Hi,

As stated on the screen short you posted, log files are saved to `/root/logfile_storage/*` before clean up

**Comment by MichaIng** [comment]
`/root/logfile_storage/` contains the accumulated `/var/log/` file content, but not the "syslog", if you mean that literally. E.g. `/var/log/syslog` is created by `rsyslog` from what it gets from `systemd-journald`, hence requires full logging option.

However, `systemd-journald` runs and logs anyway (to RAM) and instead of having another daemon that writes those logs to a plain text file, you can access them directly via: `journalctl`
Use `journalctl -u dietpi-ramlog` to see logs for the dietpi-ramlog service, likewise for any other particular service/unit/target/mount, and you can sort and filter and format the output in many ways.

**Comment by MichaIng** [comment]
I mark this as closed. Feel free to reopen if required.
