### ISSUE TITLE
[question] is there a way to dismiss system update?

### ISSUE THREAD

**Issue by k1r0s** [MichaIng/DietPi#4167]
I get this message whenever I open a term promp: DietPi-Update | Latest version  : v6.35.0

Is there a way to dismiss it?

**Comment by nonnorm** [comment]
There is no way to dismiss it, as it is reminding you to update your system, but you can use `dietpi-update` to run the update.

**Comment by MichaIng** [comment]
Same with the APT update message. I was thinking to make the banner itself optional, or making the upper parts of it optional as well, but generally I like to remind users about any kind of updates since I find it important to update DietPi and APT packages, whenever there is some time to spare and in case a server downtime possible. Most problems appear when deferring such too long so that the update includes a huge number of APT packages and incremental DietPi patches.

**Comment by k1r0s** [comment]
yep, i've already removed some banner parts although this one is the most annoying but i get the point. I'm planning to upgrade asap 

thanks!

**Comment by MichaIng** [comment]
If you want to apply the upgrades in a controlled manner, I suggest to apply `apt upgrade` first manually, having a careful look through the list. If it's many packages, `apt install <package1> <package2> ...` can be used to upgrade only a few step by step and check the result. When all APT package upgrades gone through successful, the rest of `dietpi-update` is much less of an issue.
