### ISSUE TITLE
DietPi-Software | Syncthing

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#422]
> http://dietpi.com/phpbb/viewtopic.php?f=12&t=531#p2305

Prebuilt deb packages: http://apt.syncthing.net/

**Comment by joaofl** [comment]
/etc/init.d/syncthing script for Raspberry Pi (or any Ubuntu/Debian)

https://gist.github.com/arudmin/5a13e9105814c3f568ec

**Comment by Fourdee** [comment]
@joaofl Thanks.
Bumped to v124. I keep getting asked for this one, so lets get it in :+1:

**Comment by Fourdee** [comment]
Package availability notes (http://apt.syncthing.net/):
- :u55b6: ARMv6
- :u6307: ARMv7
- :u5408: ARM64 | Not available

```
W: Failed to fetch http://apt.syncthing.net/dists/syncthing/InRelease  Unable to find expected entry 'release/binary-arm64/Packages' 
```
- :u55b6: x86_64

Edit, scrap repo. We'll use the tar binary blobs.

**Comment by Fourdee** [comment]
This program is awesome, although, a little reading is needed by end user to understand how to set it up.
![image](https://cloud.githubusercontent.com/assets/7077026/16949999/dbdc3d88-4db5-11e6-9ad8-f2fda49a0412.png)

**Comment by joaofl** [comment]
More or less I would say. The basics are almost plug and play. You only
need the others device key to pair the two clients. Then, adding folders
and sharing them comes as an option at each device you add.

If I can help on something, let me know.

No dia terça-feira, 19 de julho de 2016, Dan notifications@github.com
escreveu:

**Comment by Fourdee** [comment]
@joaofl 
With our install, i've allowed access over LAN.

```
sed -i '/:8384<\/address>/c\        <address>0.0.0.0:8384<\/address>' "$HOME"/.config/syncthing/config.xml
```

How do you run your setup? eg: Do you use web interface over LAN, external access through port forwarding?

I created a systemd service for this also:

```
cat << _EOF_ > /etc/systemd/system/syncthing.service
[Unit]
Description=Syncthing

[Service]
Type=oneshot
ExecStart=/bin/bash -c '/usr/bin/syncthing > /var/log/syncthing.log &'
ExecStop=/usr/bin/killall -w syncthing
RemainAfterExit=yes
User=root

[Install]
WantedBy=multi-user.target
_EOF_
systemctl enable syncthing.service
systemctl daemon-reload
```

**Comment by joaofl** [comment]
That is good. I would also enable enable https for the web gui, and disable the "open browser" option, otherwise it will get launched at one's desktop, if they have it.

Want me to send you a config file example?

**Comment by Fourdee** [comment]
@joaofl 

> Want me to send you a config file example?

Please if you can. Remove any passwords/auth keys etc before posting.

**Comment by Fourdee** [comment]
Docs: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=2363#p2363

**Comment by joaofl** [comment]
@Fourdee 

Follows an example of config file.

It enables secure remote access to the Web-GUI, which is very important for headless setups.

[config.xml.zip](https://github.com/Fourdee/DietPi/files/371742/config.xml.zip)

***Forgot to mention: this config file is from Syncthing version 0.14, released today, and is incompatible with the previous version.

**Comment by Fourdee** [comment]
@joaofl 
thanks, pretty much identical. I've added `<startBrowser>false</startBrowser>` config.xml.

Note to self: arm64 install is not applying GUI user/password. Danger prompt remains. armv6+ fine.

**Comment by joaofl** [comment]
@Fourdee 
It is identical, but to every major release, back compatibility is broken for other reasons, and for that they keep the config file version at the header: "configuration version="15""
And this would make it incompatible with 0.13.xx. But anyway, dietpi will start from 0.14, so it doesn't matter, but could create a bug, since you are working on it right now that they did this release.

**Comment by joaofl** [comment]
@Fourdee 
Forgot to answer your question: "How do you run your setup? eg: Do you use web interface over LAN, external access through port forwarding?"

Yes. I use no-ip + port forwarding

**Comment by Fourdee** [comment]
@joaofl 

> And this would make it incompatible with 0.13.xx. But anyway, dietpi will start from 0.14, so it doesn't matter, but could create a bug, since you are working on it right now that they did this release.

During installation, we get syncthing to generate the config. Then we only change specific values in the config.xml. So in theory, unless those variable names change in config.xml, the version should have no effect on the installation.

I'll also disable automatic upgrades aswell in the config.

**Comment by Fourdee** [comment]
Completed.

**Comment by joaofl** [comment]
@Fourdee 

I was thinking these days about moving my syncthing config folder to the dietpi_userdata folder. This because, in case i have that folder on a pen drive over USB3, I can get much faster indexing, db r/w operations, etc...

In this sense, what do you think of having the config folder inside dietpi_userdata? I saw that it can become a bit tricky because of the inotify and this API key, but I could give it a try.

Having all my config files inside the same folder interests me, specially for backup proposes.

**Comment by Fourdee** [comment]
@joaofl 

> This because, in case i have that folder on a pen drive over USB3, I can get much faster indexing, db r/w operations, etc...
In this sense, what do you think of having the config folder inside dietpi_userdata? 

Yep, makes sense 👍 . If the DB is movable, DietPi user data directory should be the target.
We did this for MySQL recently, would be great if we can follow this up with other software, that has its own internal DB/files.

**Comment by joaofl** [comment]
Finally did it: https://github.com/Fourdee/DietPi/pull/1103

Tested and working. Don't know what do you think of running the service as dietpi user.

**Comment by joaofl** [comment]
> Note to self: arm64 install is not applying GUI user/password.

@Fourdee 

After long time, while setting up my new cloud, I decided to give this issue a try. I already managed to get the password generated and hashed according to the algorithm syncthing use to hide the plain text inside the config file. Now its a matter of inserting this line inside into the setup. However, I'm not really sure about the exact right approach.

In the following 2 lines, I install a python dependency and run the python script that generates and print the hashed password:
```
# - Install requisites in order to generate the bcrypted default password for the webUI
apt install -y python3-bcrypt
python3 -c 'import bcrypt as b; print(b.hashpw("PASS_HERE".encode(), b.gensalt()).decode()); '
```
This should be added to the config.xml file, so that we get something like this:
```
    <gui enabled="true" tls="true" debugging="false">
        <address>0.0.0.0:8384</address>
        <apikey>whatever</apikey>
        <user>dietpi</user>
        <password>$2b$hashed_pass_here</password>
        <theme>default</theme>
    </gui>

```
Now it is a meter of to putting the 'apt install' at the right place, and to get the output from the python script into the config file, along with the user name. We should also use the `$GLOBAL_PW` var somehow inside the python script.

Note that the `<user>` and `<password>` fields are not there by default, so I'm not sure how `sed` would do the job.

Can you give me some directions on the best practices? Think I can implement it.

**Comment by MichaIng** [comment]
@joaofl 
I hope there is a way without python-bcrypt? Since Syncthing does not rely on it, it should be. I am not keen to install whole python dependency chain just for this 😉.

<s>@Fourdee 
> I'll also disable automatic upgrades aswell in the config.

We should re-enable, generally. Rely on internal updater handle/updating existing config correctly. If users update via dietpi-software reinstall, this might break thinks instead, since internal config/database update steps are missing.

This is something I would do in general:
- If software has an internal updater, enable it in every case, have our install code allowing this in every case. Only internal updates can respect existing install best, where manual upgrades in case always bear the risk to break existing install.
- In case of internal updater make dietpi-software skip the download & install step, only do config injection, systemd unit creation, user/permissions setup and such.
- Rely on future versions still working with our installer/uninstaller. We have not the manpower to go though all those software titles every DietPi release to bring them up-to-date. Check: https://github.com/Fourdee/DietPi/issues/1340
Most of them are out of date again, and I didn't check for a longer while... Switch to a download link that automatically points to latest release (api.github.com) where possible.
- If we ship outdated versions, users most likely update anyway and in case will chose an unreliable way.</s>

**Comment by joaofl** [comment]
@MichaIng 
I tough python3 was there by default. It actually was already in my PC DietPi image.

It seems that there is no native bcrypt. From what I've read, one can get it from the `apache-utils` package:

> You can (ab)use htpasswd from apache-utils package, provided you have version 2.4 or higher.
> htpasswd -bnBC 10 "" password | tr -d ':\n'

I presume Syncthing uses some Go packages for that. No?

@MichaIng 
Regarding your second comment, even if we disable auto-upgrade, there still a pop-up message in the web interface that allows the user to do it manually. I think it makes sense, since the upgrade can cause some interruption, and one may want to do it on its own command.

**Comment by MichaIng** [comment]
@joaofl 
Ah, so this option is only for really applying the update, while update checks are anyway done regularly?

Jep then I agree to leave it disabled.

> I presume Syncthing uses some Go packages for that. No?

No idea. Since it comes with a large binary only that runs without any dependencies, it is possible that some libraries are included to achieve this.
**€: `bcrypt.GenerateFromPassword([]byte("pass"), 0)`**
Interesting: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=700758
- bcrypt encryption disabled on Debian: https://packages.debian.org/stretch/bcrypt
- Blowfish considered insecure, alternative recommended, e.g. sha256
- [ ] Is blowfish the only pw-hashing method, supported by Syncthing? We should open feature request to change that, dropping bcrypt support. At least have a look into this...
Ah: https://github.com/syncthing/syncthing/issues/931#issuecomment-62279117
- [x] Possibility to set clear text password first and leave hashing to loader on startup?
**€: Nope, not anymore: https://forum.syncthing.net/t/option-to-set-unhashed-password-in-config-xml/10550**
- I read everywhere about an API do add user/password (https://forum.syncthing.net/t/option-to-set-unhashed-password-in-config-xml/10550), but can't find it. REST API only allows to upload a whole new config file: https://docs.syncthing.net/dev/rest.html
  - Recheck code. Indeed when settings are changed, the affected value is added to settings array, but whole settings array is saved to file, not just the individual setting:
https://github.com/syncthing/syncthing/blob/master/cmd/stcli/cmd_gui.go#L110
https://github.com/syncthing/syncthing/blob/master/cmd/stcli/utils.go#L105
https://github.com/syncthing/syncthing/blob/master/cmd/stcli/client.go#L110
  - Exactly the HTTP POST API is used, which should be what I found in the docs.
- Lol, same thought I had, why password is (badly) hashed, but API key not 😆: https://forum.syncthing.net/t/proposal-for-hashing-api-keys/7493
___________
Might I ask you to open a new issue about this? This one is closed and very old. Now it's about optimizing the pre-configuration steps of our install/config script.
