### ISSUE TITLE
No home directory of `dietpi` user on RPi 64bit image

### ISSUE THREAD

**Issue by grzesuav** [MichaIng/DietPi#4231]
#### Required Information
- DietPi version | `v7.0.2`
- Distro version | `buster`
- Kernel version | `Linux DietPi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux`
- SBC model | `RPi 4 Model B (aarch64)`
- Power supply used | Official Rpi4 power supply, 5v 3A
- SDcard used | Class 10 good ram

#### Steps to reproduce

1. login as root, then `su dietpi`
2. `cd ~`
3. The message is `bash: cd: /home/dietpi:` no such directory

#### Expected behaviour

- should move to this directory

#### Actual behaviour

- directory not exists

**Comment by nonnorm** [comment]
Linking 2 other posts with the same problem:
https://dietpi.com/phpbb/viewtopic.php?f=11&t=8862
https://dietpi.com/phpbb/viewtopic.php?f=9&t=8863

**Comment by MichaIng** [comment]
I see, I changed the PREP script to have a more complete cleanup and default system config file restoring (e.g. Armbian and others ship with some custom files, while we want the Debian package defaults). The "dietpi" user needs to be created afterwards, so that it's home dir + skeleton shell configs remain present. I'll repack the recently updated images.

Fix in the PREP script: https://github.com/MichaIng/DietPi/commit/4c0173aabefca4fab05b9b05c2899f80a0e9c464

**Comment by MichaIng** [comment]
~Most images have been repacked, the last affected ones will be done tomorrow.~
**EDIT: All images have been fixed.**

**Comment by idealwebsolutions** [comment]
Any idea when this will be packed in?

**Comment by grzesuav** [comment]
Thanks @MichaIng , closing issue then
