### ISSUE TITLE
Gitea is outdated

### ISSUE THREAD

**Issue by GitHubGeek** [MichaIng/DietPi#4233]
#### Required Information

- DietPi version | 7.0.2
- Distro version | stretch
- Kernel version | `4.14.180+ #1 SMP PREEMPT Tue Oct 13 13:28:54 UTC 2020 armv7l GNU/Linux`
- SBC model | Odroid HC1

#### Additional Information (if applicable)

- Software title | Gitea

#### Steps to reproduce

Gitea is a few versions behind. Latest is 1.14; DietPI includes 1.11

**Comment by nonnorm** [comment]
Hello,
Thank you for the information, however, this does not appear to be the case.  DietPi uses at a minimum version `1.13.2` (also, I can't find any stable version `1.14`, the latest is `1.13.6`), though it always tries to get the latest.  Could it be that the version of Gitea that you have installed is old?  If so, running `dietpi-software reinstall 165` should update it, without removing anything.

**Comment by MichaIng** [comment]
Correct, it's always the most recent version installed, but since it's not an APT package or so, it needs to be reinstalled to have it updated. I'll add this info to our documentation: https://github.com/MichaIng/DietPi-Docs/pull/411

The latest stable version is btw 1.13.6 according to GitHub release tags: https://github.com/go-gitea/gitea/releases
I updated our fallback URL: https://github.com/MichaIng/DietPi/commit/a5ef6bb072c0f44211e1f82d893cf2213c313967
But as ravenclaw900 correctly stated, this is only relevant when the download file naming schemes change, so that the auto-detection of the most recent version fails.

**Comment by Joulinar** [comment]
v1.14.0 is still in development and has a RC flag. Might be available soon. 

Anyway, can this topic be closed? I guess questions was answered.

**Comment by GitHubGeek** [comment]
Thanks for the help. I didn't understand how the update work for Gitea.
