### ISSUE TITLE
Failed to try-restart sshswitch.service: Unit sshswitch.service is masked.

### ISSUE THREAD

**Issue by Gill-Bates** [MichaIng/DietPi#4261]
Hey there,

during `apt dist-upgrade` I encounter following error message:

```
Unpacking raspberrypi-sys-mods (20210310) over (20210208) ...
Setting up systemd-sysv (241-7~deb10u7+rpi1) ...
Setting up libssl1.1:armhf (1.1.1d-0+deb10u6+rpt1) ...
Setting up libcurl3-gnutls:armhf (7.64.0-4+deb10u2) ...
Setting up raspberrypi-sys-mods (20210310) ...
Blocking vscode repo...
Failed to try-restart sshswitch.service: Unit sshswitch.service is masked.
Failed to try-restart sshswitch.service: Unit sshswitch.service is masked.
Failed to try-restart sshswitch.service: Unit sshswitch.service is masked.
Failed to try-restart sshswitch.service: Unit sshswitch.service is masked.
Setting up libpython3.7-minimal:armhf (3.7.3-2+deb10u3) ...
```

Bug or Feature? It confuses me that there anything went wrong during the upgrade process.

**Comment by Joulinar** [comment]
Hi,

Many thanks for your message. Best to you knowledge, this can be ignored safely.

**Comment by Gill-Bates** [comment]
Thanks @Joulinar. Is there a chance, to change the console output to a less confusing message like:

`Failed to try-restart sshswitch.service: Unit sshswitch.service is masked (Message can be ignored).`

**Comment by Joulinar** [comment]
This output is provided by `apt` package installer and not really influenced by DietPi script. I guess it is the `raspberrypi-sys-mods` package causing the message.

**Comment by MichaIng** [comment]
It's part of `raspberrypi-sys-mods` indeed, which contains some useful tweaks and some that are not relevant for DietPi. That service is to have OpenSSH enabled at boot, when `/boot/ssh` exists. Creating that file is the way to have SSH enabled on first boot of the Raspberry Pi OS image, where it is disabled by default. On DietPi, SSH is enabled by default and the Dropbear SSH server is installed instead of the OpenSSH server. That service has hence no use on DietPi, would fail and is hence masked on our images.

I see that the message could be confusing, but a failing service at boot would as well, and as Joulinar says, we have no control over the install script of that package.
_________
When starting our own APT server, we could host a repacked version of that package, with some things removed that we don't need 🤔. This also allows us to remove things like this VSCode repo injection in the first place. I don't think they'll do such again, the reputation damage was to large, but they did already touch APT lists in the past in a way that caused an error with the mirror director we used that time 😄.

**Comment by Joulinar** [comment]
Guys, I guess we can close this topic as we are not able to influence. Do you agree?
