### ISSUE TITLE
DietPi-DDNS | Change wording on token confirmation box

### ISSUE THREAD

**Issue by danmoo117** [MichaIng/DietPi#4320]
Hi guys, DuckDNS seems to be working nicely with the new dietpi-ddns feature so thanks for adding this in, however one of the menu pages could cause confusion as it asks for a "password" when it actually wants confirmation of the duckdns token. See screenshots.

This is the first duckdns token page which is fine.
![image](https://user-images.githubusercontent.com/79992202/116612500-88496300-a92f-11eb-9ab8-3b0e5aeba1e1.jpeg)

However when progressing this is the token confirmation page but it asks for a password. This confused me for a minute so it will likely confuse others.
![image](https://user-images.githubusercontent.com/79992202/116612697-c47cc380-a92f-11eb-9cca-5353288d656e.jpeg)

Thanks.

**Comment by Joulinar** [comment]
Hi,

yes this is known and cannot be changed for the time being https://github.com/MichaIng/DietPi/pull/4299#issuecomment-826379864

**Comment by danmoo117** [comment]
No worries, didn't see it logged anywhere so thought I'd raise it. 👍🏻

**Comment by Joulinar** [comment]
no problem, that's totally fine. If you are ok I'm going to close this one as it's working as designed at the moment. Maybe it will change in future.

@MichaIng 
or do you like to keep it open as reminder 😉

**Comment by MichaIng** [comment]
To not make it too complicated (code/function wise), what do you think about making the wording more generic, like:
```
Please confirm your input:
```
or
```
Please enter the input again:
```
or "value" instead of "input"?
_________
Another question I asked myself: Is it too annoying to enter the long token with asterisks mask two times? I wasn't sure how to evaluate the sensitivity of that DDNS passwords/tokens, so decided to stay on the strict side. Attackers with access to you DNS resolution could build fake websites to catch you sensitive data or things like private cloud/web application credentials and such. No problem with SSH copy&paste, but on a local server console I could imagine this being quite difficult.

**Comment by Joulinar** [comment]
well as it's such a long token, I simply copy it from DuckDNS site. Maybe that's how user will do it?

**Comment by MichaIng** [comment]
That was my through as well. Only difficult situation would be a headless system without an SSH client at hand, where you access via attached monitor + keyboard and have no web browser to copy the token from. But that's probably only a hypothetical edge case 😄.

**Comment by MichaIng** [comment]
Changed it now to these hardcoded but generic messages around the password box:
```
[FAILED] No input made, please try again...
Please retype and confirm your input:
[FAILED] Inputs do not match, please try again...
```
