### ISSUE TITLE
Dietpi-Letsencrypt issue

### ISSUE THREAD

**Issue by staxfax** [MichaIng/DietPi#4336]
#### Details:
- Date           | Mon May  3 16:36:57 CEST 2021
- DietPi version | v7.1.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspberry Pi OS Lite (64-bit)
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | Linux STAX-RPF 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux
- Distro         | buster (ID=5,RASPBIAN=0)
- Command        | lighty-enable-mod dietpi-https
- Exit code      | 2
- Software title | DietPi-LetsEncrypt
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
already enabled
Run "service lighttpd force-reload" to enable changes
```

**Comment by MichaIng** [comment]
Many thanks for your report. While you can ignore the error and override it by changing the command to "true" or ":", it is a bug, since it is known that this command produces an error code when a Lighttpd config is enabled already. I'll fix it by ~accepting the particular exit code~ checking first whether the config is enabled or disabled currently.

**Done: #4337**
