### ISSUE TITLE
Enable G_AGUG output

### ISSUE THREAD

**Issue by C0D3-M4513R** [MichaIng/DietPi#4344]
#### Is your feature request related to a problem? Please describe:

Today I booted my pi up, after a while.
As expected, there were a couple of software updates.
When I did `dietpi-update`, I was "stuck" on: 
```[ INFO ] DietPi-Update | APT upgrade, please wait...```
It sat there for at least 15 minutes.
I would have liked some output, so I know, that my pi isn't stuck on some obscure issue, e.g. failing some download, or some packages, that want downgrading.

#### Describe the solution you'd like:

- Remove -qq from the following line ?https://github.com/MichaIng/DietPi/blob/86c5e377c607c2e1d8e97138c7cb9d377120a55d/dietpi/func/dietpi-globals#L1372

#### Describe alternatives you've considered:

- None

**Comment by MichaIng** [comment]
Many thanks for your report.

Removing `-qq` is not really an option, as it implies processing messages that would mess logging. Note that G_AGUP also aims to be practical for non-interactive execution and with output redirected to a log file.

I think we need to revert the default APT list compression that we enabled a few versions ago. While this reduces disk writes notably, it leads to those long parsing times. I'll first add another change to reduce G_AGUP calls, storing info/timestamp of the last call, so that subsequent calls are in case skipped, then add a toggle for list compression to `dietpi-config`, changing the default to plain text lists. Or I'll leave lists compressed, but re-enable the binary cache file. Needs some testing which step has best performance per disk writes ratio 🙂.

> failing some download, or some packages, that want downgrading.

You would see it if any of such errors would be the reason. `-qq` only adds automatic confirmation and hides processing output, like the percentage of read lists and such, but all results and errors are printed.

Related issue: #4172
And: #3926

Ah, the first matches quite precisely your issue, so let's close this as duplicate and keep ideas/discussion in #4172.
