### ISSUE TITLE
Automation_Custom_Script.sh enable RPI camera module and reboot

### ISSUE THREAD

**Issue by UntriexTv** [MichaIng/DietPi#4360]
Hello i am working on project (and deadline is coming rly fast) and i need to enable rpi camera in first boot. I managed to do it, with `/boot/dietpi/func/dietpi-set-hardware rpi-camera enable` but it works only after i manually restart rpi.
I tried `reboot` on the end of script, but that only restarts whole process. Is there any way to set that restart is needed after completing setup?
P.S. setup is automatic and i only want to plug rpi with flashed card into power and it should work.

**Comment by Joulinar** [comment]
Hi,

did you tried using `/usr/sbin/reboot` in your script?

**Comment by UntriexTv** [comment]
Thank you i will try. (Setup takes more that 30 minutes)
But i think it will restart installation again, because the script will not end (it will reboot while in the custom script) so dietpi will think it crashed and it will start again (it will repeat infinitely).
I found in dietpi-config variable REBOOT_REQUIRED or something like that, and i was wondering, if dietpi-setup has something similar and if i could somehow set it to 1

**Comment by MichaIng** [comment]
I see the issue. When you reboot from within the script, the install stage won't be stored, so it will repeat, leading to a reboot -> setup -> reboot loop.

Variables cannot be set from within a script, it is always an isolated environment. To get information out, one needs to write them to a file and read it back form the parent script.

In earlier DietPi versions we forced a reboot after dietpi-software finished, but removed that since there is nearly no software install that requires it, and if so, the user can do it manually. But especially on RPi, there are changes which require a reboot, basically everything were `/boot/config.txt` is changed. That is not important when things are disabled (headless mode, WiFi, ...) but when things are enabled that are disabled by default, like the extended GPU features (required for RPi camera module), when increasing the GPU memory or adding further device tree overlays. And as part of the first boot setup, when changing the hostname, this also has no effect until reboot.

Two ideas:
- Add dietpi.txt setting to do a reboot after first run setup.
- Run the custom script after setting the install stage to finished, so that a reboot won't run dietpi-software again. If for some reason someone wants to have the first run setup repeated based on a conditions checked from within the custom script, then it is currently possible to kill the parent dietpi-software script (or reboot) while with that change one would need to manually reset the install stage `/boot/dietpi/.install_stage` first. But I cannot imaging a case where this would matter. If something fails, a manual investigation is required or wanted most likely, instead of automatically repeating the first run setup.
- Turning the REBOOT_REQUIRED variable into a flag file, like `/run/dietpi/reboot_required` that is checked by dietpi-config, dietpi-software and dietpi-update. The benefit is that it can be set from sub shells and sub scripts, so e.g. we can set it from the scripts which change the hostname or enable the RPi extended GPU features regardless from where they are called.

**Comment by UntriexTv** [comment]
@MichaIng Yeah exactly. Could you or somebody please tell me which script is setting the install stage as finished so i could just add `/usr/sbin/reboot` on the end?
I tried putting it on the end of dietpi-autostart, but it is still looping.
Thank you

**Comment by MichaIng** [comment]
Instead of changing core scripts, add the following to the end of your custom script, before calling reboot:
```
echo 2 > /boot/dietpi/.install_stage
```
Only the dietpi-autostart choice won't be applied. Here the actual code part in dietpi-software:
```
			if [[ -f '/root/AUTO_CustomScript.sh' ]]; then

				local fp_log='/var/tmp/dietpi/logs/dietpi-automation_custom_script.log'

				G_DIETPI-NOTIFY 2 'Running custom script, please wait...'
				G_EXEC_NOEXIT=1 G_EXEC chmod +x /root/AUTO_CustomScript.sh
				/root/AUTO_CustomScript.sh 2>&1 | tee $fp_log
				if (( ${PIPESTATUS[0]} )); then

					G_DIETPI-NOTIFY 0 "Custom script: $fp_log"

				else

					G_DIETPI-NOTIFY 1 "Custom script: $fp_log"

				fi

				G_EXEC_NOEXIT=1 G_EXEC rm /root/AUTO_CustomScript.sh

			fi

			# Apply AutoStart choice
			/boot/dietpi/dietpi-autostart "$AUTOINSTALL_AUTOSTARTTARGET"

			# Set Install Stage to Finished
			G_DIETPI_INSTALL_STAGE=2
			echo $G_DIETPI_INSTALL_STAGE > /boot/dietpi/.install_stage
```

**Comment by UntriexTv** [comment]
Ok great. Thank you so much

**Comment by matteocarnelos** [comment]
As an alternative you can spawn a background shell that checks the `/boot/dietpi/.install_stage` file and eventually reboots the system.
To do so, just add the following to `Automation_Custom_Script.sh`:
```bash
(while [ "$(</boot/dietpi/.install_stage)" != 2 ]; do sleep 1; done; /usr/sbin/reboot) >/dev/null 2>&1 &
```
By doing so all the commands executed after the script will be executed.

**Comment by MichaIng** [comment]
Btw, since a few DietPi versions, the custom script is called after the setup stage has been applied. So it is now save to call a `reboot` from `Automation_Custom_Script.sh` when required. I'll mark this hence as solved/closed.
