### ISSUE TITLE
General | FStrim causing corrupt filesystem

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#440]
Although unproven, since this has been running as a daily task for our users, the number of filesystem corruptions has increased from our users.

I believe this to be the cause. FStrim will be disabled until further testing can be completed.

**Comment by Fourdee** [comment]
Disabled as of v125.

Note:
Requires testing to prove stability before we add this back in.

**Comment by Fourdee** [comment]
Leaving this as disabled. Not worth the risk of creating possible filesystem corruption to users system.

**Comment by TheOriginalMrWolf** [comment]
Hi,

Almost 4½ years later and it seems that fstrim is still disabled (DietPi v6.34.3, on Odroid N2) - any plans to re-enable on, say, a weekly basis?  Not having this causes significant slowdowns & additional wear due to write amplification.

I would hope that the underlying issue is resolved by now?

Thanks!
