### ISSUE TITLE
Fan Control

### ISSUE THREAD

**Issue by Rick847** [MichaIng/DietPi#4454]
I If you could add a fan control option in the DietPi-config where you only enter the GPIO pin with a desired temperature that turns on the fan at max temp and turns off at min temp, that would be awesome :)

**Comment by MichaIng** [comment]
Many thanks for your request. I was starting with a script to control the CPU fan interface, when a regular (PWM) fan socket is available:
- #1818 
- https://github.com/MichaIng/DietPi/blob/dev/.meta/dietpi-fan_control

Making this usable in a more generic way to control any GPIO-attached fan, would be nice indeed. But it's probably not that trivial. A hysteresis is required to avoid high frequent on-off switching around the temperature point.

But more problematic is probably the interface to communicate with the GPIO on each SBC in general. We need a generic method, as implementing this for each SBC/SoC individually would be a huge overhead.

I'll close this issue in favour of the previous one. It's nice to have but from my end has low priority, especially because from all I found it needs to be done differently on each device, which pulls too much time from other topics where with less effort, more can be reached for all systems/users. So that is something where you guys (the community) needs to help, continuing or re-starting what I started once. We're always open for PRs 😃.
