### ISSUE TITLE
questions: youtube-dl

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#4585]
Had youtube-dl binary installed manually with a cron job to update it weekly.

```
ls -l /etc/cron.weekly
total 12
-rw-r--r-- 1 root root 102 Oct 11  2019 .placeholder
-rwxr-xr-x 1 root root 813 Feb 10  2019 man-db
-rwxr-xr-x 1 root root 193 Jul 25 10:22 youtube-dl

nano /etc/cron.weekly/youtube-dl
#!/bin/sh
#
# download latest version youtube downloader

wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl >/dev/null 2>&1
chmod a+rx /usr/local/bin/youtube-dl
```

With DietPi v7.4.2. I have installed youtube-dl through dietpi-software. Have following questions:

1. Why is youtube-dl installed as script to run youtube-dl-py2 and not as a single binary ?
2. Is youtube-dl updated regularly this way?

Thanks, Maarten

**Comment by MichaIng** [comment]
Hi Maarten, thanks for your question.

We missed to have the docs ready for youtube-dl to explain this:
- `/usr/local/bin/youtube-dl` is a Python script with `python` shebang. So when calling it just like that, it will execute with Python 2, or, when not installed, fail. But it is Python 3 compatible.
- Since Python 2 is deprecated since beginning of 2020, we try to avoid using or even installing it whenever possible. So we store the `youtube-dl` script with a Python 2 suffix and create a Python 3 wrapper at the original location. So when calling `youtube-dl` from console, it will run with Python 3.

It's basically [this](https://github.com/ytdl-org/youtube-dl/issues/27649) we workaround.

**Comment by maartenlangeveld** [comment]
@MichaIng,

I understand now, thanks a lot !!!
