### ISSUE TITLE
RPi Zero W DietPi v7.5.2. bullseye - reset All options to defaults DietPi-Justboom gives error

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#4694]
**alsa-lib parser.c:2179:(load_toplevel_config) Unable to find the top-level configuration file '/usr/share/alsa/ucm2/ucm.conf'.
alsa-lib main.c:1014:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2**

```
alsa-lib parser.c:2179:(load_toplevel_config) Unable to find the top-level configuration file '/usr/share/alsa/ucm2/ucm.conf'.
alsa-lib main.c:1014:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2
Found hardware: "RPi-WM8804" "" "" "" ""
Hardware is initialized using a generic method
[  OK  ] DietPi-Set_hardware | sed -Ei s/^[[:blank:]]*(hdmi_drive(:[01])?=.*$)/#\1/ /boot/config.txt
[  OK  ] DietPi-Set_hardware | sed -Ei /^[[:blank:]]*dtoverlay=dietpi-disable_(hdmi_audio|headphones)/d /boot/config.txt
[  OK  ] DietPi-Set_hardware | Desired setting in /boot/config.txt was already set: dtparam=audio=off
[ INFO ] DietPi-Set_hardware | Applying new sound card settings...
[  OK  ] DietPi-Set_hardware | Desired setting in /boot/dietpi.txt was already set: CONFIG_SOUNDCARD=justboom-digi
[  OK  ] DietPi-Set_hardware | Added setting dtoverlay=justboom-digi to end of file /boot/config.txt
[  OK  ] DietPi-Set_hardware | alsactl -g store
[  OK  ] soundcard justboom-digi | Completed
[ SUB1 ] DietPi-Set_hardware > soundcard (justboom-digi)
[ INFO ] DietPi-Set_hardware | Checking for required APT packages: alsa-utils
[  OK  ] DietPi-Set_hardware | All required APT packages are already installed.
[ INFO ] DietPi-Set_hardware | Resetting all sound card settings...
[  OK  ] DietPi-Set_hardware | rm /etc/asound.conf
[  OK  ] DietPi-Set_hardware | rm /var/lib/alsa/asound.state
```

**Comment by MichaIng** [comment]
The major issues with DietPi-JustBoom have been fixed with DietPi v7.7: https://github.com/MichaIng/DietPi/commit/9d6197f

I'll now check the mixer reset on RPi Zero, but related errors are basically harmless and can be ignored: This may happen if the sound driver / device tree overlay has not been loaded yet (the latter requires a reboot) or if for some other reasons certain controls cannot be set/reset or when they do not follow common standards. ALSA uses a generic template to reset all controls, but the ones of the sound card may not match any of those, so it is then left as it was. The RPi repository ships an own/changed template file for onboard sound, but obviously it doesn't cover all external ones, even when drivers/overlays are provided. In this case I cannot replicate it since I have no JustBoom Digi HAT. If this is seen as problem, it could be reported to the RPi repo maintainers and with some luck, the control template/reset file may be extended to cover this sound card: https://github.com/RPi-Distro/repo/issues

The only important output line finally is the last:
```
Hardware is initialized using a generic method
```

I'll mark the issue hence as closed. Feel free to reopen when required.
