### ISSUE TITLE
XU4 (odroid hc1) bullseye image coming?

### ISSUE THREAD

**Issue by eikaramba** [MichaIng/DietPi#4894]
i'm waiting quite some time now to reimage my hc1 from odroid with the latest bullseye. and i just saw that finally you updated the images here https://dietpi.com/downloads/images/
first of thank you very much. **however i need to ask why the XU4 images are only buster and not bullseye**.

please don't misunderstand me, **i'm super happy even if there will never be a bullseye release and don't expect anything from you**. i just want to know whether i should wait more or if it is unlikely that there will be an bullseye release for these devices.

i will certainly also try to migrate from stretch->buster->bullseye but last time after trying it the system stoped booting up and i needed to completely restore the image.

**Comment by eikaramba** [comment]
Ok i am currently tryint out bullseye. i can already confirm that removing `console=ttySAC2,115200n8` from boot.ini did not do any harm. i was able to boot from sd card and login via SSH as normal.

**Comment by MichaIng** [comment]
Many thanks for testing.

You removed boot/kernel messages from the serial console but the login getty is still enabled:
```sh
systemctl disable --now serial-getty@ttySAC2
```
In `dietpi-config` when hitting the toggle, both is removed, the boot/kernel messages and the login getty. But indeed the entry in `boot.ini` is the only thing which may have caused this boot hang at this early stage.

Out of interest:
```sh
ls -l /dev/tty1
echo test > /dev/tty1
head -1 /dev/tty1
```
This TTY should be completely unused on a system with no screen port. I guess is is present and can be manually read and written to, but since no screen/framebuffer is attached to it, and no local input device, it should remain completely unused. SSH sessions use pseudo-terminal devices like `/dev/pts/0` and serial consoles use `/dev/ttyS<something>`, and for host<>container communication and similar there would be the `/dev/console` meta device available. However, as it is reasonably used for boot and kernel messages (when using the image on Odroids with a screen), it must be assured that the attempt to read/write it does not cause issues.

**Comment by eikaramba** [comment]
i am unfortunately not such a linux pro and honestly understand only a fraction ;)

did you asked me to provide me outputs of the forementioned commands?
if so here:

`ls -l /dev/tty1`
crw--w---- 1 root tty 4, 1 Oct 31 19:13 /dev/tty1

`echo test > /dev/tty1`
-bash: /dev/tty1: Permission denied

`head -1 /dev/tty1`
head: cannot open '/dev/tty1' for reading: Permission denied
resp. nothing with sudo

**Comment by MichaIng** [comment]
Ah yes, `sudo`/root is required, or being a member of the `tty` group. To be sure, can you again try:
```sh
echo test | sudo tee -a /dev/tty1
```
Great that everything is working again. I'll re-allow disabling the serial console on XU4 variants then but add a notice that on headless devices, when difficult or impossible to attach a screen and keyboard, it is recommended to leave it enabled, so that debugging and fixing issues during early boot or when the network/SSH server does not come up, is possible e.g. with a serial USB adapter cable and a notebook with PuTTY.

**Comment by eikaramba** [comment]
no problem, output of `echo test | sudo tee -a /dev/tty1` is just:
test

**Comment by MichaIng** [comment]
Okay great, it shouldn't really cause any issues then 🙂.

**Comment by MichaIng** [comment]
I'll mark this as closed for now. An image with Linux 5.4 will be uploaded soon.
