### ISSUE TITLE
DietPi doesn't boot Rpi4 board 

### ISSUE THREAD

**Issue by giusanny** [MichaIng/DietPi#5263]
DietPi version | 8.1.2
Distro version | bullseye
Kernel version | `Linux 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l GNU/Linux`
SBC model | RPi 4 Model B (armv7l)
Power supply used 5V 3A
SDcard used SanDisk ultra 32GB and Samsung 32GB (same results)

Related to #5104  

Same test of #5104 so having 2 identical Rpi4 with the same Sunfounder touch screen 10.1'' without any other USB devices plugged into, on the first Rpi4 everything boots and works fine, then if i put the same SD in the second Rpi4 it does not boot till the end and the touch shuts down after this last screen
![image](https://user-images.githubusercontent.com/44324877/153454616-f6191400-6262-4ba6-8964-0de8a5bff03b.png)

I have done the same test with the two SD (Samsung and Sandisk) with same results
```
cmdlinetxt 
root=PARTUUID=4dbce400-02 rootfstype=ext4 rootwait net.ifnames=0 logo.nologo console=tty1 ipv6.disable=1 fsck.mode=skip
```

How and where can i read some more logs of boot script execution to get some other information?

Expected behaviour
The image copied into the SD has to work in the two Rpi4 in the same way or showing logs to understand the cause

Actual behaviour
DietPi boots only on one Rpi4

**Comment by MichaIng** [comment]
Many thanks for your report.

Do you have SSH access to that RPi 4?

Since the last log is the `console-setup` service, I suspect that it is the culprit. It reloads the console with a different font style and key map, which you should recognise on the other RPi 4 where the screen turns black for a fraction of a second and then wakes up again with mentioned changed fonts. Probably due to some minor hardware differences (e.g. revision code) and some voltage/power quirks or so it doesn't come back on the second RPi 4. Is this an HDMI touch screen?

**Comment by giusanny** [comment]
Thanks for you reply first of all.

After the touch shuts down seems like Rpi4 is dead so i have no SSH access, but reading your reply I tried to startup disconnecting the monitor and changing the power supply and it worked!

So there was voltage problems but only with that Rpi4 using that power supply and that specific image (with a rasbian image or a new Dietpi image everything worked right also with the old power supply and touch monitor connected ...very strange)

**Comment by Joulinar** [comment]
Do you use any overcooking profile?

**Comment by giusanny** [comment]
1. here there is the profile
![image](https://user-images.githubusercontent.com/44324877/153605319-037cc249-3a2b-400c-be61-ce109b817a79.png)


2. I have no power supply problems
throttled=0x0

but when i have thee problem the Rpi4 shuts down as the monitor goes off so i cant get any command results :(

echo $G_HW_REVISION results
- c03111 the one that works
- c03112 the one that not works

**Comment by MichaIng** [comment]
So at least there is a hardware difference which can explain the different behaviour. You could enable persistent system logs for a while to possibly get some more info about what happened before the crash:
```sh
dietpi-software uninstall 103
mkdir /var/log/journal
reboot
```
Then `journalctl` includes logs from previous boot sessions. To revert:
```sh
dietpi-software install 103
systemct stop systemd-journald
rm -R /var/log/journal
reboot
```

**Comment by MichaIng** [comment]
I'll mark this as closed, but feel free to reopen when you have news.

**Comment by nboyan** [comment]
@MichaIng, I think you can reproduce it quickly when plugging two USB devices. The next step is to write in the terminal reboot command and wait. The device would not start until eth cable was unplugged and plugged.

**Comment by MichaIng** [comment]
> I think you can reproduce it quickly when plugging two USB devices.

No, I have up to 4 USB devices attached to my RPis and never faced a reboot issue. If this was related, then the only explanation would be insufficient PSU or that all USB devices consume more than 1.2A (absolute maximum across all USB ports).

Note that there can be various reasons for reboot problems, while we tried to rule some our here already, and your symptoms with the Ethernet cable are different as well. So for better investigation I suggest you open a new issue with fresh template instead of posting here.
