### ISSUE TITLE
[Discuss] Semantic Versioning in DietPi.

### ISSUE THREAD

**Issue by bhaveshgohel** [MichaIng/DietPi#601]
Hello @Fourdee ,
Today when i ssh to my RaspberryPi i see a message like  "Run now to update DietPi (from V132 to V136)."
And i wonder will this update are minor or major update to current version. Will upgrading breaks some things? 

![dietpi](https://cloud.githubusercontent.com/assets/5253753/20165061/097a581e-a730-11e6-9310-e973f86164c5.jpg)

I agree i can see the changelog file and guess the change. but this issue can easily solved by [Semantic Versioning](http://semver.org/).

We can implement it from today like V136 to V1.3.6! (just a suggestion)

Pl discuss. :smiley: 

-Bhavesh Gohel

**Comment by Fourdee** [comment]
@bhaveshgohel 

Excellent idea 👍

**Comment by bhaveshgohel** [comment]
Hello Dan ( @Fourdee ),
Just curious to know if any second though on this implementation?

**Comment by Fourdee** [comment]
@bhaveshgohel 

> Will upgrading breaks some things?

Generally speaking, our updates "should not" break current installations. We run many tests our end, to ensure they are stable before releasing to the public. However, issues may occur, but we do try to resolve them with urgency.

I like the idea of Semantic Versioning, but we would need to completely rewrite the current update system to support it. It would also very likely mean a complete image/update reset, rendering the current installations "un-patch-able" with the new system.

Its not something we want to do currently (due to the above), but i'll add this to the milestone for image resets and take a look then.
https://github.com/Fourdee/DietPi/milestone/25

**Comment by Fourdee** [comment]
We'll implement this starting from DietPi v6.0: https://github.com/Fourdee/DietPi/issues/1355

**Comment by Fourdee** [comment]
Completed.
vMAJOR_VERSION.SUB_VERSION
![image](https://user-images.githubusercontent.com/7077026/34481672-589cca0c-efab-11e7-8f11-668f67b26fa7.png)
