### ISSUE TITLE
Steam + Vulkan support (Proton) | Notes

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#6262]
As title, steam requires a Vulkan driver stack/support for DirectX wrapper.

---

- Intel:
- :u6307: Intel Iris onboard GPU
```
mesa-vulkan-drivers:amd64 
mesa-vulkan-drivers:i386 #Required for steam
```

---

- :u6307: Nvidia 1660ti
```
nvidia-driver
nvidia-vulkan-icd
nvidia-vulkan-common

#+STEAM
nvidia-driver-libs:i386
libnvidia-glvkspirv:i386
nvidia-vulkan-icd:i386
```
---

- AMD unknown (no access to HW)

---

To consider:
- Adding Vulkan to base driver installs by default? It will replace OpenGL at some point.

---

Docs to enable proton (disabled by default):
- Load Steam
- Click View
- Settings
- SteamPlay
- ```Enable Steam Play for all other titles```

**Comment by MichaIng** [comment]
Many tanks for the info. While the Nvidia drivers will most likely work better, do Mesa Vulkan drivers work with Nvidia GPU as well?

I'm thinking about adding this to the `dietpi-config` menu as well:
- An additional menu entry to install Vulkan drivers
- Usually Mesa drivers will be installed (works with all platforms), but if Nvidia drivers are enabled already, the Nvidia Vulkan drivers will be installed
- When enabling Nvidia drivers while Vulkan drivers are enabled, those will be switched to Nvidia Vulkan drivers as well
- And generally we can enable this menu for AMD as well: The Radeon drivers are available for all architectures, the Nvidia drivers for ARM64. SBCs can in theory work with external graphic cards.

**Comment by Fourdee** [comment]
@MichaIng 
Maybe something like this? https://github.com/Fourdee/DietPi/blob/dev/dietpi/func/dietpi-set_hardware#L2262-L2303

Then call from ```dietpi-config```?

**Comment by MichaIng** [comment]
> I personally would install Vulkan support as part of any driver stack, that supports it.

You mean when selecting any of the three options of this menu? That makes it simpler, actually fine with me. The `mesa-vulkan-drivers` should be generally right on AMD GPUs as well, as it explicitly pulls `libdrm-amdgpu1` as dependency.

Only downside is that then there is no option to install Vulkan on other GPUs like Rockchip Mali on SBCs. OpenGL/EGL libs are basically pulled in with any graphics software, including the X11 core package, so there is no point installing those explicitly or as additional option. But for Vulkan and also in cases GLES2 this is different, so having an option to enable/install those on any GPU is actually nice.

Currently we install GLES2 on demand for e.g. Kodi on ARM. We could definitely do the same with Vulkan for Steam. We also do an Nvidia GPU check there to decide whether to install the `nvidia-driver-libs:i386` or not. I'm not sure how reliable this check is, but based on it we could install as well `nvidia-vulkan-icd` or otherwise `mesa-vulkan-drivers`.

**Comment by MichaIng** [comment]
> Maybe something like this?

Jep makes sense to add it there, so we can call this from `dietpi-config` as well as `dietpi-software`.

In `dietpi-config`, it makes sense then to make this a single driver stack selection, and I'd add "Generic" then: None, Intel, Nvidia, AMD, Generic (`mesa-vulkan-drivers` and probably `libgles2`). Storing this as new `dietpi.txt` option for non-interactive/first-run-setup Steam installs, and allow interactive selection as well? And during non-interactive Steam installs, if nothing was chosen, we can at least auto-detect Nvidia cards and then also install the i386 libs as we do currently:
```sh
[[ -e '/sys/module/nvidia/version' ]] && nvidia=('nvidia-driver-libs:i386')
```

**Comment by Fourdee** [comment]
@MichaIng Yep sounds good. I'll continue with changes and let you know when its ready.

**Comment by MichaIng** [comment]
> DietPi-Automation | Add ``GPU_INDEX=``` support?

Would be great. Could be added to `DietPi-Automation_Pre()` or `DietPi-Automation_Post()`. Ignore the obsolete info that network connectivity wouldn't be assured in `DietPi-Automation_Pre()`: On first login, `dietpi-update` runs and checks for + requires network connectivity, and we to `G_AGDUG` in `DietPi-Automation_Pre()`. So it makes more sense to decide whether the GPU driver should be installed before or after software installs. I've no clear preference. If `dietpi-set_hardware` adjusts the `dietpi.txt` setting as well, and change done by software installs, e.g. if the Steam install changes it from "None" to "Nvidia", would be preserved in both cases.

**Comment by Fourdee** [comment]
@MichaIng 
I went for a system where we can reinstall drivers + i386 extras as needed, using ```dietpi-set_hardware```
So if a user installs steam after a GPU driver install, it will re-check during steam install. Cover all possibilites.
https://github.com/MichaIng/DietPi/issues/6262#issuecomment-1481270323

Will do some testing and get back to you :+1:

**Comment by Fourdee** [comment]
@MichaIng 
Ah looks like config inject is setting ```Setting in /boot/dietpi.txt adjusted: CONFIG_GPU_INDEX=enable``` instead of indexs. 
Anyway to tell G_CONFIG_INJECT to not override value sent?

**Comment by MichaIng** [comment]
> Ignore me, due to 🤣

I never liked this `1 => enable`/`0 => disable` translation but like it to be rather explicit. We could switch consequently to `0`/`1` (does not need to be beautiful here, we use it internally only) or `enable`/`disable`. Or otherwise to keep changes minimal, translate it the other way round: `enable => 1`, `disable => 0`.

> not patching for some reason?

New patch file is here: https://github.com/Fourdee/DietPi/blob/dev/.update/patches

**Comment by Fourdee** [comment]
@MichaIng 
> I never liked this 1 => enable/0 => disable translation but like it to be rather explicit. 

Let me know how you want it. Either by ```GPU_DEVICE=Nvidia``` or ```GPU_INDEX=2```. I can change if needed?

> DietPi systems older than v7.x

Nice :+1:

**Comment by MichaIng** [comment]
> Let me know how you want it. Maybe `GPU_DEVICE=Nvidia` instead of `GPU_INDEX=2`. I can change if needed?

Using textual inputs seems quite a good solution as well. Probably `GPU_DRIVER` to be a bit more precise what it is about?

**Comment by Fourdee** [comment]
> Using textual inputs seems quite a good solution as well. Probably GPU_DRIVER to be a bit more precise what it is about?

Yep. Done a rewrite, changed from index based to name system. 

Just doing patch + fresh driver install tests now. Will get back to you with PR when done.

**Comment by Fourdee** [comment]
Pretty much done.

:u6307: Tested patch with both Nvidia and Intel. Steam working fine now on both.

Added a "Custom" GPU driver option to allow user/manual setups, and have DietPi ignore any driver changes. Felt this was needed, espically for exisiting installs.

Patch now prompts user to select new GPU driver for x86. 

ToDo: 
- Patch notes
- PR

**Comment by MichaIng** [comment]
Done with DietPi v8.16 🚀
