### ISSUE TITLE
Unable to uninstall python or home assistant

### ISSUE THREAD

**Issue by InnovoDeveloper** [MichaIng/DietPi#6432]
- DietPi has encountered an error                                   -
- Please create a ticket: https://github.com/MichaIng/DietPi/issues -
- Copy and paste only the BLUE lines below into the ticket          -
---------------------------------------------------------------------
#### Details:
- Date           | Tue Jun 13 16:17:54 PDT 2023
- DietPi version | v8.18.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Armbian
- Hardware       | NanoPi NEO (armv7l) (ID=60)
- Kernel version | `Linux MagicCube 5.15.93-sunxi #23.02.2 SMP Fri Feb 17 23:49:46 UTC 2023 armv7l GNU/Linux`
- Distro         | bullseye (ID=6)
- Command        | `rm -Rf /root/.cache/pip /home/homeassistant/.cache/pip`
- Exit code      | 1
- Software title | DietPi-Software
#### Steps to reproduce:

1.  Try to uninstall Python
2. Try to Uninstall Home Assistant
#### Expected behaviour:

Files should be deleted
#### Actual behaviour:

Getting stuck on directory not empty.  Starting a shell and trying to delete the  directories manually doesn't delete the directories. 

#### Extra details:

Removing the SD card, deleting the files manually from another machine gets the process going.- ...
#### Additional logs:
```
rm: cannot remove '/home/homeassistant/.cache/pip/http/c/4/9': Directory not empty
rm: cannot remove '/home/homeassistant/.cache/pip/http/8/1': Directory not empty
rm: cannot remove '/home/homeassistant/.cache/pip/http/0/a/a/a/7': Directory not empty
rm: cannot remove '/home/homeassistant/.cache/pip/http/7/2/d': Directory not empty
rm: cannot remove '/home/homeassistant/.cache/pip/http/b/2/5': Directory not empty

**Comment by MichaIng** [comment]
Sorry for the late reply. I guess this is due to filesystem errors. The `pip` cache contains a huge number of small files and directories where some corruption is more likely, especially when using an SD card.

In the meantime we have the `pip` cache disabled. It usually is not required but only uses disk space. Very rare case that one needs to install or compile the same module with same version multiple times.

Since you found a solution, I'll close this issue. Feel free to reopen if required.
