### ISSUE TITLE
Failed to update VaultWarden as part of dietpi-update to DietPi v8.18.2

### ISSUE THREAD

**Issue by kaelbashir** [MichaIng/DietPi#6490]
#### Details:
- Date           | Tue Jul 18 10:48:44 EDT 2023
- DietPi version | v8.19.0 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=1)
- Command        | `apt-get -y --allow-change-held-packages install ./vaultwarden_armv7l.deb`
- Exit code      | 100
- Software title | DietPi-Software
#### Steps to reproduce:
1. run dietpi-update
#### Expected behaviour:
- Successful dietpi-update
- Successful VaultWarden upgrade
#### Actual behaviour:
- Unable to continue, DietPi-Software will now terminate.
- VaultWarden upgrade failed
- Unable to correct problems, you have held broken packages.
#### Additional logs:
```
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 vaultwarden : Depends: openssl (>= 1.1.1n-0+deb11u5) but 1.1.1n-0+deb11u4+rpt1 is to be installed
               Depends: libssl1.1 (>= 1.1.1n-0+deb11u5) but 1.1.1n-0+deb11u4+rpt1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Joulinar** [comment]
Can you share following,

```
dpkg --print-architecture
```

I guess you kernel switched to 64bit mode even your are running 32bit userland.

**Comment by MichaIng** [comment]
Looks like Raspbian is shipping an older OpenSSL than Debian. But actually the packages are there already: http://raspbian.raspberrypi.org/raspbian/pool/main/o/openssl/?C=M;O=D
The package list however indeed still points to `deb11u4`.

The RPi repo actually ships the `+rpt1` variant. Also here, the `deb11u5` packages exist already since the beginning of the month: https://archive.raspberrypi.org/debian/pool/main/o/openssl/?C=M;O=D
Ah, and there the list also contains the correct latest version: https://archive.raspberrypi.org/debian/dists/bullseye/main/binary-armhf/Packages

Checking on RPi Zero W:
```
libssl1.1/stable 1.1.1n-0+deb11u5+rpt1 armhf [upgradable from: 1.1.1n-0+deb11u4+rpt1]
openssl/stable 1.1.1n-0+deb11u5+rpt1 armhf [upgradable from: 1.1.1n-0+deb11u4+rpt1]
```
Not sure how long this is, but @kaelbashir please simply retry as I get the exact needed update now. Everything else would be alarming, since this version contains security patches: https://metadata.ftp-master.debian.org/changelogs//main/o/openssl/openssl_1.1.1n-0+deb11u5_changelog

**Comment by Joulinar** [comment]
can you share following output:

```
apt update
apt show libssl1.1
```

BTW, no need to do screen prints. You should be able to copy/paste content directly from SSH terminal.

**Comment by Joulinar** [comment]
can you share your source file configuration? Something doesn't seem to be correct there.

```
for i in /etc/apt/sources.list{,.d/*.list}; do echo "$i:"; cat "$i"; done
```

**Comment by Joulinar** [comment]
> /etc/apt/sources.list.d/raspi.list:
> #deb https://archive.raspberrypi.org/debian/ bullseye main
> deb https://mirror.umd.edu/raspbian/raspbian/ bullseye main

Any reason for disabling `https://archive.raspberrypi.org`? I would recommend reverting that change and activate it again. Your manually added mirror `https://mirror.umd.edu` doesn't seems to be up to date causing your issue.

**Comment by Joulinar** [comment]
> /etc/apt/sources.list.d/tailscale.list:
#Tailscale packages for ubuntu focal
deb https://pkgs.tailscale.com/stable/ubuntu focal main

Another topic, why you are using Ubuntu package source for Tailscale?? There is a Debian package source as well and we have included it into our software catalogue.

**Comment by Joulinar** [comment]
ok, I'm going to close the issue as it has been resolved. Feel free to reopen if needed.
