### ISSUE TITLE
Dietpi-backup recovery failing

### ISSUE THREAD

**Issue by Maggus101** [MichaIng/DietPi#6521]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
- Distro version | DietPi_NativePC-UEFI-x86_64-Bookworm
- Kernel version | `uname -a`
- SBC model | Lenovo ThinkCentre M90n-1
- Power supply used | (EG: 5V 1A RAVpower)
- SD card used | (EG: SanDisk ultra)

#### Additional Information (if applicable)
- Software title | Dietpi-backup
- Was the software title installed freshly or updated/migrated? Fresh
- Can this issue be replicated on a fresh installation of DietPi? Yes

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

Fatal issue with upgrade to bookworm. Reinstalling and trying to do restore backup from external HDD. Gets through to the 'Please reboot' screen and boots into GNU Grub interface

#### Expected behaviour

Reboot into dietpi

#### Actual behaviour

boots into GNU Grub interface

#### Extra details

- ...
![IMG20230731155816](https://github.com/MichaIng/DietPi/assets/40856424/3d7eac8a-0979-4320-813e-cdc16af324a7)
![IMG20230731155743](https://github.com/MichaIng/DietPi/assets/40856424/090c63e3-842e-44e9-8c8d-5ddebd3afb14)
![IMG20230731155735](https://github.com/MichaIng/DietPi/assets/40856424/83917d59-535d-4ed8-8f53-048a3b262bcd)

**Comment by MichaIng** [comment]
> Fatal issue with upgrade to bookworm.

What exactly was the fatal issue?

> Reinstalling and trying to do restore backup from external HDD.

What do you mean by "reinstall"? Did you flash a fresh DietPi image? This one `DietPi_NativePC-UEFI-x86_64-Bookworm`?

If so, was the previous image as well a UEFI image? Theoretically, those should not contain a bootloader stage outside of any filesystem but only the part within the EFI partition and the configs on the rootfs. So restoring the backup should theoretically work in this case. I see the those files all being restored on your photo. And the GRUB command prompt shows that it is a version from Debian Bullseye, so that seem to have been restored successfully, or it was not updated yet when you ran into the "fatal issue" during the Bookworm upgrade.

What I can think of is that the partition and/or filesystem UUIDs do not match. The new image cam with new ones, but the configs of the backup refer to the old ones. But `dietpi-backup` actually should handle this case: Did you see this line indicating a GRUB update before the "Restore completed" promt?
```
[ .... ] update-grub
```
with a moving dot, turning into a OK:
```
[  OK  ] update-grub
```
