### ISSUE TITLE
DietPi-Software | openHAB: Migrate to "stable" suite

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#6731]
Is there any particularly reason that for openHAB, DietPi is using testing and not stable?

I did an DietPi upgrade from 8.19.1 to 8.23.3 and also got openHAB updated but not to latest stable version (4.0.4), which I would have expected, instead it was to 4.1.0-M3.

I of course can only speak for myself but personally I prefer stable versions.

**Comment by MichaIng** [comment]
Thanks for your question. The reason is that openHAB 3 did not fully support Java 17, and at the time of implementation, openHAB 4 was still in testing: https://github.com/MichaIng/DietPi/pull/6334#issuecomment-1528729163

This however changed, so we can migrate to stable suite: #6732

But I think for Buster, we need to limit it to latest v3. Currently it is still in the repo, so some APT preference should do.
