### ISSUE TITLE
 DietPi-Software | Public key is not available from 'apt-get update'

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#677]
Hardware: ODroid C2 (aarch64)
Configuration: Completely fresh install DietPi_v139_OdroidC2-arm64-(Jessie)

During the use of the command
apt-get update

**Produces**
Reading package lists... Done
W: GPG error: http://www.deb-multimedia.org jessie InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5C808C2B65558117

**Comment by Fourdee** [comment]
@LexiconCode 

Thanks for report.

Yep, it appears we left in the deb multimedia repo on our current C2 image. This is patched for new installations in v141, removing the repo (as its not needed) and therefore error.

~~For existing installations, as some software in ```dietpi-software``` use this repo i'll see if we can patch the required apt-key.~~

```
if [ -f /etc/apt/sources.list.d/deb-multimedia.list ]; then

     apt-get install -y --force-yes deb-multimedia-keyring

fi
```

Turns out ```dietpi-software``` uses ```/etc/apt/sources.list.d/debmultimedia.list``` when its required, whereas fp for our image is ```/etc/apt/sources.list.d/deb-multimedia.list```. so we can safely remove ```/etc/apt/sources.list.d/deb-multimedia.list``` for existing installations aswell, during patch.

**Comment by Fourdee** [comment]
Resolved with v142 patch:
```
		#-------------------------------------------------------------------------------
		#Deb multimedia repo left on C2 image, remove for ALL installs: https://github.com/Fourdee/DietPi/issues/677
		#	debmultimedia.list is used by dietpi-software.
		rm /etc/apt/sources.list.d/deb-multimedia.list &> /dev/null
```
