### ISSUE TITLE
 DietPi-Software | Apt-Fast - Downloading packages in parallel, with multiple connections per package.

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#698]
[Apt-Fast](https://github.com/ilikenwf/apt-fast) is a shellscript wrapper for apt-get and aptitude that can drastically improve apt download times by downloading packages in parallel, with multiple connections per package.

**Quick Install**
You can quickly install apt-fast by running:
`/bin/bash -c "$(curl -sL https://git.io/vokNn)"`

Then simply run apt-fast instead of apt-get or aptitude.

We could use apt-fast instead of apt-get.

**Comment by Fourdee** [comment]
@LexiconCode 

> drastically improve apt download times 

Sounds awesome 👍 I'll take a look and see if we can integrate it.

https://github.com/ilikenwf/apt-fast/blob/master/quick-install.sh

Install, without Git deps ( 6,994 KB):
```
apt-get install -y aria2
wget https://raw.githubusercontent.com/ilikenwf/apt-fast/master/apt-fast -O /usr/bin/apt-fast
chmod +x /usr/bin/apt-fast
wget https://raw.githubusercontent.com/ilikenwf/apt-fast/master/apt-fast.conf -O /etc/apt-fast.conf
```

test
```
root@DietPi:~# apt-fast install -y --force-yes --reinstall alsa-utils
```

Lest try it in DietPi-Software

**Comment by Fourdee** [comment]
Odroid C2, 140mb/s R/W EMMC, 100Mbit internet

LAMP stack install (No apt mirrors added):
- ```time dietpi-software install 74```
- 🈯️ ```apt-get``` = ```real    2m14.208s```
- 🈴 ```apt-fast``` = ```real    2m20.798s```

😕 

LAMP stack install (```MIRRORS=( 'http://ftp.uk.debian.org/debian,http://ftp.us.debian.org/debian,http://ftp.de.debian.org/debian' )```)
- 🈴 ```apt-fast``` = ```real    2m21.152s```

I think the issue is, ```apt-fast``` has to process download list, which is actually slowing down the installation time:
```
Working... this may take a while.
```

This may have use on Raspbian (due to poor performance with mirror director), but debian repo's are generally fast, so no benefit.

I'll leave support for ```apt-fast``` in ```dietpi-software```, however, not making a default for install. Manual install using: https://github.com/Fourdee/DietPi/issues/698#issuecomment-270915190

**Comment by Fourdee** [comment]
@LexiconCode 
I'll mark this as closed, but your welcome to test, support for ```apt-fast``` available in testing branch:
https://github.com/Fourdee/DietPi/blob/master/TESTING-BRANCH.md

Make sure to install ```apt-fast```:
https://github.com/Fourdee/DietPi/issues/698#issuecomment-270915190
