### ISSUE TITLE
Multiple shells installed by default?

### ISSUE THREAD

**Issue by Creative-Difficulty** [MichaIng/DietPi#7160]
By running `cat /etc/passwd` i can see that every non-system user (root, dietpi and other "user created" users) uses `/bin/bash` as the shell. I want to create a new user and the default config in `/etc/default/useradd` says this: 
```bash

# The SHELL variable specifies the default login shell on your
# system.
# Similar to DSHELL in adduser. However, we use "sh" here because
# useradd is a low level utility and should be as general
# as possible
SHELL=/bin/sh

```
So it sets the default shell to `bin/sh`, even though all other (non-system) users use `/bin/bash`.
Also, when running `stat /bin/sh`, I find out that it's a symlink to `/bin/dash`, however `/bin/bash` is also present as the default shell. This is quite confusing. Also in the forums @MichaIng wrote, that `/bin/bash` should be used as the shell for new users: https://dietpi.com/forum/t/change-default-root-users-for-security/5810/2. So why the confusion? Any help would be appreciated!

**Comment by MichaIng** [comment]
This is pretty expected: `dash` is Debian's bourne shell, with very limited features, not great for interactive use with login users. `bash` is the "bourne again shell" with additional features for scripting and especially also for interactive use, and hence present and used by default on almost all distros. Nearly every distro has at least those two (types of) shells.

`/bin/sh` is commonly a symlink to the system's bourne shell implementation, in this case provided by the `dash` package. Since it is assumed to be always present, even on minimal distros, and as a bourne shell assured to be POSIX compatible, it the best default in general.

For login users, one commonly uses `adduser` instead of `useradd`, which is better suited for interactive usage and as well for creating interactive/login users, and it consequently also uses `/bin/bash` as default shell. `useradd` is more for scripting, maintainer scripts etc for creating system users with minimal default setup and defaults more suited for non-interactive use, hence consequently also `/bin/sh` as default shell.
