### ISSUE TITLE
DietPi-Config | Add CPU/ARM min frequencies for RPi

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#73]
> https://www.raspberrypi.org/forums/viewtopic.php?p=819840#p819840

**Comment by Fourdee** [comment]
Done as a toggle option. v93.

DietPi-Config (RPi) -> Performance Options -> Lower Min Freqs
New menu option to toggle the use of lower minimum freqs in config.txt(arm_freq_min=100 etc). Allows for potential power saving.

**Comment by Fourdee** [comment]
Update, some issues when  using the _freq_min settings:
- Setting any of the _freq_min settings causes initial_turbo to be disabled.
- Using a value of core_freq_min=75. Causes the display to turn on and off. A direct link to what state the scaling frequency is at that time. Off when CPU is idle, On when CPU is scaled to max.

I've disabled this feature in DietPi-Config, and will try the RPi forums for information.

EDIT: Posted on RPi forums for advice/info. https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=121914&p=822170#p822170

**Comment by Fourdee** [comment]
> https://www.raspberrypi.org/forums/viewtopic.php?p=822170#p822170

No response from RPi community, and, no official documentation which covers a compatible list of frequencies.

For the mean time, this feature will remain disabled until further testing, and/or, documentation is available.

**Comment by Fourdee** [comment]
Marking this as closed. Min frequency feature will stay disabled for foreseeable future.

**Comment by MichaIng** [comment]
Works well now:
```
2019-10-10 18:52:03 root@micha:~# grep -E '(arm_freq|initial)' /DietPi/config.txt
initial_turbo=20
#arm_freq=900
arm_freq_min=150
```
Lowest supported value is 100 AFAIK, although I can't find the source anymore. However it simply does not make any sense to set it lower, since ondemand governor would then nearly never settle down due to high % CPU usage. Note that RPi only jumps between lowest and highest freq but does not support multiple freq steps by default. So a too low minimum means maximum clocks run more often. Best tradeoff on my particular case was 150.

**Comment by MichaIng** [comment]
Re-added: https://github.com/MichaIng/DietPi/commit/1082b1864dc07e665a2c3915f4d4cfb817910002
