### ISSUE TITLE
Diet Pi Image for Banana Pi

### ISSUE THREAD

**Issue by Mister-XY** [MichaIng/DietPi#824]
Hello, is it possible to get an Image from Dietpi for Banana Pi?
Here is an ARMBian Version for it
https://www.armbian.com/banana-pi/

**Comment by Invictaz** [comment]
Yeah, I hope Allwinner A10 / A20 support is coming. Not all hardware acceleration is working yet but at least it's a start. A lot has changed since 2013/2014 and Cedrus has some libvdpau implementation.

https://github.com/linux-sunxi/linux-sunxi
http://linux-sunxi.org/Cedrus
http://linux-sunxi.org/Sunxi-cedrus
http://linux-sunxi.org/Cedrus/libvdpau-sunxi
https://github.com/codesnake/aml-mali
https://github.com/huceke/libcedar
https://github.com/tnmeyer/xbmc
https://twistedlinux.wordpress.com/2016/03/15/build-initramfsinitrd-for-a10a20/
https://twistedlinux.wordpress.com/2016/03/14/build-a10a20-with-hardware-acceleration/#more-649
https://github.com/linux-sunxi/libvdpau-sunxi
https://github.com/mosterta/libvdpau-sunxi/commits/master
http://linux-sunxi.org/Mainlining_Effort
http://www.phoronix.com/scan.php?page=news_item&px=Linux-4.8-Sound
http://forum.kodi.tv/showthread.php?tid=254202
https://www.phoronix.com/scan.php?page=news_item&px=Allwinner-A10-DRM-Display

**Comment by Mister-XY** [comment]
And now?

**Comment by Invictaz** [comment]
@Mister-XY we wait for @Fourdee 
Since there is a ton of other work to do it might take a while. Since there are already ARMBIAN packages available for A10/A20 it might be possible. The LIBVDPAU-SUNXI is the hardest to get right since there is a lot of repo's and info but no real mainlining. In order to not violate the GPL DietPi can only use the open sourced efforts and not the closed source binaries from Allwinner (I think).

**Comment by Fourdee** [comment]
https://github.com/Fourdee/DietPi/issues/938#issue-227327655

**Comment by Fourdee** [comment]
Closing as we no longer support or provide images for BPi devices.
