### ISSUE TITLE
DietPi.com | TLS/HTTPS

### ISSUE THREAD

**Issue by shellshocker** [MichaIng/DietPi#830]
There is no TLS-cert on the website and also no checksum to verify the image. From a security perspective -> this is bad. ;-)

**Comment by Fourdee** [comment]
@shellshocker 

Thanks for the feedback 👍 

- We'll get the TLS cert and https redirect added to dietpi.com with cerbot. We need to migrate our server anyway (upgrade to Jessie from Wheezy), will do that at the same time.
- CRC/MD5 hash for images: https://github.com/Fourdee/DietPi/issues/831

**Comment by trajano** [comment]
Please fix the title so it shows TLS not TSL.

**Comment by ChargingBulle** [comment]
any update on this?  
It can't take nearly a year to upgrade to HTTPS...

**Comment by Fourdee** [comment]
Ok, lets get the ball rolling on this:
- Server upgrade/transition to Stretch
- HTTPS via certbot

Email sent to MVS, requesting a new VPS we can use for the transition. Old one can then be dropped once completed.

**Comment by MichaIng** [comment]
@Fourdee 
This means also phpbb update, right? I am excited like a little boy a day before Christmas eve 😃.

**Comment by Fourdee** [comment]
> This means also phpbb update, right?

Yep 😃, just hope it migrates easily (doubt it)

**Comment by Fourdee** [comment]
New server, 
- Debian 9
- Dual core 3GHz
- 2GB RAM
- 20GB SSD

```
root@DietPi:~# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel Xeon E312xx (Sandy Bridge)
```

**Comment by Fourdee** [comment]
Import of phpbb3 forums is a failure:
- phpbb3 backup restore
- phpmyadmin SQL import

Both fail with multiple endless errors. Most likely too much has changed since 3.0 and 3.2 currently. May not be possible ☹️ 

---

We may need to upgrade dietpi.com to 3.2 (risky + downtime), before we can transfer:
https://www.phpbb.com/support/docs/en/3.2/ug/upgradeguide/upgrade3/

🈯️ Install 3.0 on new server, import, migrate to 3.2.

**Comment by MichaIng** [comment]
@Fourdee 
And after upgrade, to have a clean phpBB and phpMyAdmin instance, export again from new server, reflash clean image and import again 😆. No I think the effort is not worth it 😋.

**Comment by Fourdee** [comment]
@MichaIng 

http://185.101.93.93/phpbb

**Comment by dennisvanderpool** [comment]
I just visited the site and noticed your remark. Just let me know if i can help (testing).

**Comment by Fourdee** [comment]
Status:
- 🈯️ PHPBB migration + upgrade to 3.2.2. Mirror issue with PHPdebug, due to centre BB code (should now be resolved)
- 🈯️ dietpi-survey
- 🈯️ DietPi site + downloads
- 🈯️ (domain record updated, pending DNS refresh) | Activate / IP swap from old server to new server
- 🈯️ DietPi update mirror
- 🈯️ Setup HTTPS and forced http redirect
```
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/dietpi.com/fullchain.pem. Your cert will
   expire on 2018-07-26. To obtain a new or tweaked version of this
   certificate in the future, simply run certbot again with the
   "certonly" option. To non-interactively renew *all* of your
   certificates, run "certbot renew"
```
![image](https://user-images.githubusercontent.com/7077026/39373538-d1996d4a-4a3f-11e8-91cd-bad1fc1eac75.png)
- 🈯️ Re-enable forums
- Re-enable access.log and server stats? Hmm, kind of like it running on DietPi-RAMlog 😃 
- Setup monthly cron job for certbot autorenew. | i'll do this manually.
- 🈯️ Test

**Comment by Fourdee** [comment]
@dennisvanderpool 

> I just visited the site and noticed your remark. Just let me know if i can help (testing).

👍 Should now be ready for testing, as long as your DNS server has updated:
http://dietpi.com

It should redirect you to https

**Comment by ChargingBulle** [comment]
![img](https://image.ibb.co/f11Kgx/image.png)
some parts still feel unsafe

**Comment by Fourdee** [comment]
@JonasDralle 

Thanks for the report 👍 

Appears Firefox doesnt like http links used on the site, or it doesn't like the http redirect, we'll try to resolve:
> For your own domain, serve all content as HTTPS and fix your links.  Often, the HTTPS version of the content already exists and this just requires adding an "s" to links - http:// to https://.

🈯️ Resolved:
![image](https://user-images.githubusercontent.com/7077026/39405758-cc1ab25c-4ba2-11e8-8fe2-016b4b9ea722.png)

**Comment by Fourdee** [comment]
Completed.

**Comment by MichaIng** [comment]
SSL Labs result looks good. Cipher suites could be a bid stricter, but some old clients would be excluded.
Mozilla SSL generator with intermediate settings always provided 95%/A+ as far as I remember, but hmm, actually this looks exactly like what you are using (besides disabled OCSP stapling: https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=apache-2.4.25&openssl=1.0.2l&hsts=yes&profile=intermediate
Maybe SSL Labs become stricter lately 😉.
