### ISSUE TITLE
DietPi-Software | Docker

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#870]
> http://dietpi.com/phpbb/viewtopic.php?f=12&t=640&p=6708#p6663

**Comment by phonicmouse** [comment]
+1

**Comment by nicbkw** [comment]
+1

**Comment by telamon** [comment]
DietPi would've been a nice dist if it had better docker-support as the availability of containers on the hub really does outperform dietpi's custom menus and software install scripts.
 
I tried using hypriot's docker packages but my Xu4 + dietpi kernel-panics whenever i try to start a container that uses --net=host priviledge. Had a few kernel-panics related to AuFS it seems as well but sadly I never get the chance to inspect the errors since the logs never get flushed to disk and are gone without a trace after reboot. :(  :+1:  for docker support.

**Comment by bduisenov** [comment]
Hi @Fourdee, do you have this in the roadmap already?

**Comment by Fourdee** [comment]
@bduisenov 

Do now, i'll pop this into v156 milestone. Will take a look during that phase.

**Comment by bartaspoz** [comment]
v156 released and I see that you moved docker to v157 milestones. Did you encountered problems or just this is so time consuming? :)

**Comment by Fourdee** [comment]
@bduisenov 

> Did you encountered problems or just this is so time consuming? :)

Lack of available time from my end, and, we needed to release v156 to resolve bugs which would effect our users.

I will get round to it, although, no ETA yet.

**Comment by telamon** [comment]
Hey, a little status update. I recently upgraded my diet pi version and also purged out the docker provided by hypriot and replaced it with the official installation via get.docker.com which now contains arm distributions. And so far the old kernel panic issue has been resolved. I cannot reproduce it ant more.

**Comment by Fourdee** [comment]
Added in by @techdabbler for v157 👍 

Tested with x86_64 and RPi 3:
Marking as completed.

**Comment by bartaspoz** [comment]
Hi, firstly, I couldn't find Docker in gui in optimized software list. Found ID and tried to install by:
dietpi-software install 162

And recieved bellow errors:
 Executing docker install script, commit: 490beaa 
Either your platform is not easily detectable or is not supported by this 
installer script. 

And next:
Failed to stop docker.service: Unit docker.service not loaded.
sed: can't read /lib/systemd/system/docker.service: No such file or directory

Test performed on: Odroid C2

**Comment by bartaspoz** [comment]
A llittle followup. Managed to install docker manually from repo, but containers don't want to work, error during start as below:

could not create session key: function not implemented

Is there anything we can do?

Test platform: Odroid C2

**Comment by bduisenov** [comment]
Hi @bartaspoz, I'm facing the same issue with docker installation. Neither can see the docker item in the list of dietpi-software

**Comment by ghost** [comment]
@bartaspoz - This is as expected and designed.  The official docker script doesn't support ARM8 so dietpi does not display the menu item on ARM8 devices and if you force install it will fail. It appears the Odroid C2 is ARM8.

@bduisenov ate you also on ARM8 or on a different arch?

**Comment by bduisenov** [comment]
@techdabbler Armv8-A, Quad-Core ARM Cortex A53 64-Bit Processor

**Comment by ghost** [comment]
@bduisenov - That makes sense then too. Def it is due to docker not officially supporting raspbian and arm8. I didn't do anything fancy but package up the official installer.  If anyone out there knows steps to get docker to work on raspbian arm8 I can add the steps to dietpi-software installer.

**Comment by bduisenov** [comment]
@techdabbler got it, thanks for the explanation.

**Comment by bartaspoz** [comment]
People say that probably enabling keychain functionality in the kernel is needed in order to get it work (error: could not create session key: function not implemented). The keychain is enabled by default on 3.18+ Kernel, and latest available for DietPI is 3.14+. I'm not an linux expert, can you tell us if updating kernel to 3.18+ is possible on DietPI?

Additionally, do you know why I'm receiving this strange notification?:
dietpi-update    = Run now to update DietPi (from V157 to V156).

**Comment by bartaspoz** [comment]
@techdabbler you're right. But there is a possibility to install armhf on arm64, which I have done. Firstly you have to enable armhf architecture support on your C2 (don't remember how, done it some long time ago)

 And next, regarding Docker, you have to add new repo as below
deb [arch=armhf] https://download.docker.com/linux/debian jessie stable

And Install docker by:
apt-get install docker-ce

And it installs, daemon starts without any problems, but containers won't work :( Probably because of the session keychain, as I wrote before. Here's link to identical problem that someone had:
https://github.com/moby/moby/issues/33976

**Comment by ghost** [comment]
@bartaspoz - This starts to sound like it is outside my wheel house.  I don't know anything about the kernel or how to replace it or update it in dietpi.  

Nor do I know about the weird v157 to v156 message you are getting.  

I'd recommend maybe you open up another current issue with arm8 and docker and see if anyone else is able to help you.  Continuing on this thread since it is marked closed seems less likely someone else might see it and be able to help you. 

Just my 2 cents worth.

**Comment by lpninja** [comment]
Anyone installed Docker on ROCK_64? The chip is a _Rockchip RK3328 Quad-Core ARM Cortex A53 64-Bit Processor_

**Comment by j2l** [comment]
> 
> 
> Anyone installed Docker on ROCK_64? The chip is a _Rockchip RK3328 Quad-Core ARM Cortex A53 64-Bit Processor_

Docker is available from the dietpi-software menu, but I didn't find any working orchestrator/router.

Did someone successfully run one?

**Comment by lpninja** [comment]
@j2l yes we ran docker on it.
