### ISSUE TITLE
General | Change default user to dietpi

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#896]
currently ```root```

> https://github.com/Fourdee/DietPi/issues/796#issuecomment-296365067

**Comment by sootstone** [comment]
Would it be possible to make username changeable in dietpi.txt on first install?

**Comment by Fourdee** [comment]
@sootstone 

> Would it be possible to make username changeable in dietpi.txt on first install?

Good idea 👍 , i'll see what we can do.

**Comment by Fourdee** [comment]
We'll attempt to achieve this for v6.0, however, we have a limit of 1 month for completion with many other features yet to implement, so this may be a continuing process in v6.0's future.
https://github.com/Fourdee/DietPi/issues/1355

**Comment by Fourdee** [comment]
Not enough time to make this into v6.0, and, is low priority.

Moving to v6.1

**Comment by MichaIng** [comment]
Agree, also I would make it optional, or default, but optional to just stay with root. Generally I agree to use non-root user for security reasons, but on otherwise secure/updated servers with just ports 80+443 forwarded, limited hardened web services there and for local access, strong password + SSH key authentication, I would clearly prefer the comfort advantages of by default using root for server maintenance.

But all our scripts should just work the same, if started with sudo, right?

**Comment by Fourdee** [comment]
@MichaIng 

> But all our scripts should just work the same, if started with sudo, right?

Yep, ```sudo``` elevates to ```root``` user. Effectively the same as logging in as root.

**Comment by Fourdee** [comment]
Currently, following has been implemented:
- Use of, and support for ```dietpi``` user on SSH/local terminal login and usage

Pending:
- Desktops/VNC as ```dietpi``` user?
- Implement unique users for each software installation title that requires it (different ticket: https://github.com/Fourdee/DietPi/issues/1877)

**Comment by Fourdee** [comment]
Marking as closed, in favor of: https://github.com/Fourdee/DietPi/issues/1877
