### ISSUE TITLE
DietPi-Software | ~~PiCast~~ Youtube player

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#915]
> https://github.com/lanceseidman/PiCAST

**Comment by Fourdee** [comment]
In short, PiCast is not Chromecast, or in any way compatible. Its current abilities are playing youtube videos from a URL link, that must be inputted via a browser.
![image](https://cloud.githubusercontent.com/assets/7077026/25660134/ccedbfb0-3002-11e7-83e6-10b058a4ff91.png)

Its essentially a highly glorified youtube video player, with no relation to Chromecast.

The "developer" of PiCast has clearly incorrectly abused the word "Chromecast" to pull in interest and support, where its not due.

**Comment by Invictaz** [comment]
There are more 

https://github.com/spygi/personal/blob/master/raspberry-youtube/server.py
https://github.com/andresromero/RPI-Cast
https://github.com/vincelwt/RaspberryCast

Not sure which is "the best". Since they all use an own implementation of Youtube. If it's unmaintained it does not work anymore. Might as well choose the easiest method or best maintained.
