### ISSUE TITLE
DietPi Image for Beagle Bone Black

### ISSUE THREAD

**Issue by lucario1001** [MichaIng/DietPi#931]
### Testing Image (Not available any more since [ DietPi  v6.x ](https://github.com/Fourdee/DietPi/issues/1385)): 
`DietPi_v158_BBB-armv7-(Stretch).7z`
### How to flash SD to EMMC: https://github.com/Fourdee/DietPi/issues/931#issuecomment-346447628

---

wondering if it can be made 
AM335x 1GHz ARM® Cortex-A8

also love your software

works well on the raspberry pi 👍

**Comment by Fourdee** [comment]
@lucario1001 

Thanks for the request. DietPi (being extremely lightweight) would run really well on this single core board.

I did email beaglebone over 3 months ago, requesting dev sample boards, then we can implement a DietPi image and support it. However, still no response as of yet.

**Comment by Fourdee** [comment]
Lets give twitter a bash:
https://twitter.com/DietPi_/status/861230917322502144

**Comment by lucario1001** [comment]
cool thanks 👍 soon hope we might have a image for it

**Comment by pdp7** [comment]
@jadonk @robertcnelson what do you think?

**Comment by scottwilliamsinaus** [comment]
+1 for this! BBB has a following amongst audiophiles for its ability to have the I2S output synced to an external master clock. Also, the Botic overlay (https://github.com/miero/botic-dev) on BBB is the only way to get hires multichannel output from a SBC at present (I think - happy to be corrected), so incorporating that would be fantastic. 
Brilliant work with DietPi otherwise! It has turned Linux from being a drag to fun, and saved me countless hours. Donation made!

**Comment by isso** [comment]
+1
Anything we can do to accelerate this?

**Comment by Fourdee** [comment]
@iSsO 
Ordered one on RS, should be here next week (back order)
![image](https://user-images.githubusercontent.com/7077026/31774331-491d555a-b4dd-11e7-81d0-97af98170c88.png)

**Comment by isso** [comment]
Great news, I've just ordered the newly announced PocketBeagle one, it will arrive next week as well.

I think they are using the same processor, but the pocket is using a integrated module (Octavo) instead of the bare IC.

Do you think DietPi can work on the pocket as well?

I can help in testing if you need to.

**Comment by RobertCNelson** [comment]
For BeagleBoard.org, these devices share the same bootloader (v2017.09) and same kernel (v4.4.x-ti/v4.9.x-ti/v4.14.x-ti) just different device-tree binary.

Regards,

**Comment by lucario1001** [comment]
still have my beagle bone black if you need help testing

**Comment by Fourdee** [comment]
Arrived 😄 

#### Notes:
- Write EMMC to SD > https://elinux.org/BeagleBone_Black_Extracting_eMMC_contents#Alternatives
- Write SD to EMMC > https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#Flashing_eMMC
- ```rsync dosfstools``` required?

_NB: BBB LEDS are blinding and distracting lol, like looking at the sun._

---

```fstab``` under SD boot (emmc is k1p1):
```
/dev/mmcblk0p1  /  ext4  noatime,errors=remount-ro  0  1
debugfs  /sys/kernel/debug  debugfs  defaults  0  0

```
---

- 🈴 Our current removal of packages in prep script breaks boot of the device. Need to debug.

- nodejs
- apache2
- core
- 🈴 misc
```
Package 'btrfs-tools' is not installed, so not removed
The following packages will be REMOVED:
  alsa-utils* autoconf* automake* autotools-dev* bb-cape-overlays* bind9-host*
  bone101* cpufrequtils* device-tree-compiler* git* git-core* git-man*
  haveged* hostapd* i2c-tools* iperf* libasound2* libasound2-data*
  libdbus-1-dev* lsof* m4* ncurses-term* pkg-config* rfkill* screen*
```
```device-tree-compiler``` required for ```bb-cape-overlays* device-tree-compiler```
```git``` required for ```bone101* git* git-core*```

---

- 1st run of DietPi results in failed boot (middle 2 blue LED's lit), due to FS expansion. Not compatible with BBB's unique boot system. Fixed image size (4GB) for EMMC.
- FS size incorrect (corruption???)
```
root@DietPi:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p1  3.3G  2.7G  407M  87% /

root@DietPi:~# cd /
root@DietPi:/# treesize
2.6 GB .
1.6 GB ./var

root@DietPi:/# cd /var
root@DietPi:/var# treesize
1.6 GB .
59.6 MB ./lib
23.2 MB ./cache
24.0 KB ./spool
16.0 KB ./local
12.0 KB ./log
8.0 KB ./backups
4.0 KB ./tmp
4.0 KB ./opt
4.0 KB ./mail
```
- 🈯️ Due to swap generation, will disable.

---

Large image size:
- remove ```/opt/source``` ```/opt/cloud9``` ?

**Comment by Fourdee** [comment]
### Performance:

- CPU: https://github.com/Fourdee/DietPi/issues/1253#issuecomment-346441545
- Network: 100MBit
- Heat Eff, unable to determine, CPU temp in kernel not implemented.
- Onboard EMMC:
![image](https://user-images.githubusercontent.com/7077026/33141045-d11cc49a-cfa9-11e7-8df2-8044484579a5.png)

**Comment by Fourdee** [comment]
### How to flash EMMC (rev C):
- Boot system with DietPi on SD card (hold S2 during power on for 2-5 seconds)
- DietPi may reboot system automatically after updates, if so, hold down the S2 button again.
- Wait for ```dietpi-software``` screen to show, then exit.
- Edit ```/DietPi/uEnv.txt``` and enable line at bottom (remove ```#```) ```cmdline=init=/opt/scripts/tools/eMMC/init-eMMC-flasher-v3.sh```
- Reboot system
- Wait for device to flash (LED's in up and down motion). Device will power down once its completed.
- Eject SD and power on.

**Comment by Fourdee** [comment]
> https://twitter.com/DietPi_/status/933419127276036096

Completed. Image now live.

**Comment by antonellocaroli** [comment]
I can not find the image on the download page

**Comment by Fourdee** [comment]
@antonellocaroli 

Apologies, the image is no longer available/maintained due to low user count. You can install DietPi on the system using PREP:
https://github.com/Fourdee/DietPi/issues/1285#issue-280771944

**Comment by zhanglongqi** [comment]
@Fourdee Just curious about how you know the user count? what is the data source?

**Comment by MichaIng** [comment]
E.g. the survey statistics give/gave a hint: https://dietpi.com/survey/#device
See for "BBB", two reported systems, probably one was Fourdees testing system. Since there is no BBB image download available anymore this cannot be compared well now, but it was when Fourdee closed this ticket.

But you can always use https://github.com/MichaIng/DietPi/blob/dev/PREP_SYSTEM_FOR_DIETPI.sh to migrate from (mostly) any Debian-based image to DietPi.

**Comment by LaurensVanAcker** [comment]
I tried this script one a BeagleBone Black rev C, but the connection drops at `Removing connman (1.36-2) ...`.

**Comment by RobertCNelson** [comment]
@LaurensVanAcker that's expected, all the official BeagleBoard.org images use connman as the default network connection tool..

**Comment by MichaIng** [comment]
Yes, with connman and NetMan this is a known issue: #2054
For some reason, on uninstall, those completely deconfigure/break the current network connection. So `ifupdown` needs to be installed, `/etc/network/interfaces` configured and then either after an `ifup --force eth0`/`ifup --force wlan0` it's already possibly to uninstall connman/NetMan, or it needs to be disabled and then a reboot done to have `ifupdown` taking over:
```
systemctl disable connman
systemctl enable networking
reboot
```

**Comment by jnk19** [comment]
Any update on this? I use the build script everything finish normal ( I had pre removed connman and config `/etc/network/interfaces`) but after reboot I have "black screen" and no more connection with SSH. Anyone have resolve this?

**Comment by MichaIng** [comment]
Which base image did you use? The Debian 1GB console images seem to be the best start: https://beagleboard.org/latest-images

Can you also show the full output of DietPi-PREP?

What I recognised is that there is a custom APT source in the main sources.list. You should add it before running PREP as dedicated source:
```sh
echo 'deb https://repos.rcn-ee.com/debian/ buster main' > /etc/apt/sources.list.d/bbb.conf
```
Replace `buster` with `bullseye` if you plan to upgrade. After PREP, before rebooting, you may want to reinstall the packages which are shipped by the image:
```
apt install bb-bbai-firmware bb-cape-overlays bb-customizations bb-wl18xx-firmware
```
It adds Bluetooth and WiFi firmware (from what I understand, though BBB doesn't have any of both, does it?) and a bunch of services and scripts where I'm not sure which one may be required (one does something on U-Boot configs on kernel upgrade).

You do not have a UART adapter to watch early boot logs from an external console, do you?

**Comment by RobertCNelson** [comment]
I've moved these to our forum's.: https://forum.beagleboard.org/tag/bbbio_debian

The Bullseye images now use systemd-networkd vs connman..  (Debian no longer has a maintainer for connman..)

Regards,

**Comment by jnk19** [comment]
I use this image: AM3358 Debian 10.3 2020-04-06 4GB eMMC IoT Flasher 

No BBB do not have Bluetooth or Wireless (except the Wireless version I do not use that) so probably not need these packages you mention on you post.

No unfortunately I do not have a UART adapter, but I can get the output of DietPI-PREP.

I will try the new images with bullseye release that @RobertCNelson provided and I will try to build there also.

I hope all goes well.

**Comment by RobertCNelson** [comment]
That IoT image has a lot of extra stuff.. Node-RED, CLoud9, etc.. it would be best to start with a console bsae, you want to use DietPi's scripts..

**Comment by MichaIng** [comment]
Many thanks for chiming in. Great that there are Bullseye snapshots already. Should then be preferred for a DietPi-PREP run. `systemd-networkd` does not abort the network connection when stopped, so that issue would then be solved for BBB.

Awesome to see that recent Linux versions are provided, this is very rare among SBC manufacturers.

Having a look through the latest am335x Bullseye snapshot:
- @RobertCNelson would you consider moving the `repos.rcn-ee.com` repository into a dedicated file in `/etc/apt/sources.list.d`? This is mostly a convention to have only the major distribution repository (Debian) in `sources.list` and others in dedicated files.
- There is not a U-Boot package `bb-u-boot-am335x-evm` which one may want to install as well. I guess it does not automatically flash U-Boot on upgrade, but provides the new images and a script to flash them.
- `bb-customizations`, mentioned above, is btw an important one, which updates the symlinks used by the bootloader to kernel, dtb and initramfs on kernel upgrades. Though, since there is no kernel meta package (at least not pre-installed), the kernel currently needs to be upgraded manually:
    ```sh
    apt search 'linux-image-.*-ti-r[0-9]'
    ```

**Comment by giusCB** [comment]
hi guys, i've a little stock of BB Black. 
Can someone summarize how to flash dietpi system on emmc memory ?
(amny) Thanks in advance

**Comment by Joulinar** [comment]
Does this blog might be helpful https://dietpi.com/blog/?p=1236

**Comment by giusCB** [comment]
thanks for the reply,
there is something more specifically for the BBB ?

**Comment by Joulinar** [comment]
nope
