### ISSUE TITLE
DietPi-Process_tool | Ability to add custom entries

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#944]
eg: include file
> http://dietpi.com/phpbb/viewtopic.php?f=9&t=826

**Comment by MichaIng** [comment]
@Fourdee
Easiest would be probably to add an entry to dietpi.txt?

**Comment by Fourdee** [comment]
@MichaIng 

Performance wise, probably best in this case to have a include file eg:
```
if [ -f /DietPi/dietpi/.dietpi-process_tool_include]; then

import contents to array

fi
```

As ```dietpi.txt``` grep scrape would take much longer, and sed to clear up the var before import.

**Comment by MichaIng** [comment]
@Fourdee 
Ah yeah that's true, especially since dietpi-services is called quite often.

We could also write the list directly into dietpi-services, into a certain place, marked by special comments. DietPi-Update would need to redo this.
Anyway we would need to somehow trigger `dietpi_controlled` on new entries, maybe introducing a new dietpi-services command option that rereads the include list, (in case writes it directly into dietpi-services, ) and does dietpi_controlled on those new services. This then needs to be published within the include file/dietpi.txt, so users know they have to manually run it after changing something.

€: Huh? Somehow mixed it up with `dietpi-services` 😆 where such a custom entries list already exist. I moreless copied the method for `dietpi-process_tool`.

**Comment by MichaIng** [comment]
PR: https://github.com/Fourdee/DietPi/pull/1616

Merged, I mark as closed
