### ISSUE TITLE
Swapfile is too big for my SD-card (768mb) v149

### ISSUE THREAD

**Issue by S60Team** [MichaIng/DietPi#956]
I have a problem on my RPI v1 (256mb RAM, 2Gb MicroSD):
Swapfile is too big for my SD-card (768mb) (v149)
Before that, i have ~50mb on v148 and it worked well.
Can you make a configuration for swapfile size Before update, maybe in v150?
Please!

**Comment by nickfox-taterli** [comment]
2GB MicroSD are too small....

**Comment by S60Team** [comment]
But system is hang up...
So i copied all configs and reinstalled the system,
then changed swapfile in dietpi-config.
Problem solved. Kinda

**Comment by Fourdee** [comment]
@S60Team 

As of v149 (and the v148 RPI image), swapfile size is now 1GB - RAM. So in your case, 768MB~ would be generated for swapfile to prevent out of memory issues, due to users installing multiple software titles.

You can disable swapfile generation, after writing DietPi image, and, prior to booting device for 1st time in ```/boot/dietpi.txt```:
```Swapfile_Size=0```
