### ISSUE TITLE
Wi-Fi devices cannot get a IP addresses using a RPi 3 as a hotspot and Pi-hole acting as DHCP server

### ISSUE THREAD

**Issue by enolp** [MichaIng/DietPi#992]
I'm unable to get IP addresses on my Wi-Fi devices setting a Raspberry Pi 3 as a Wi-Fi hotspot and also, Pi-hole acting as a DHCP server.

ics-dhcp-service fail to load at startup and i tried to mask it to see if that solves my problem but it doesn't. However, I went into dietpi-config in order to configure my Wi-Fi hotspot but there is a limited number of options, and I couldn't disable de DHCP options for the Wi-Fi hotspot.

My idea is, using my RPi 3 as a Wi-Fi hotspot to replace the crappy one which comes with my router and get ad-blocking at the same time.

Bug report: c9ff04fd-1317-4c51-9890-7204c43139f0-0

**Comment by enolp** [comment]
Doing a search on the internet to see how can I solve my issue, I found this article: https://frillip.com/using-your-raspberry-pi-3-as-a-wifi-access-point-with-hostapd/ which uses dnsmasq (instead of ics-dhcp-server) like pihole.

I'll do some tests because I think it is not complicated to do and that setup is easy to do.

UPDATE 0:

The tutorial seems to work but i cannot reach the internet. DHCP works fine but now i don't know what's causing the failure.

UPDATE 1:

I don't know what I did before but now nothing works...... I would like someone help me with this because having installed dnsmasq, dietpi installs ics-dhcp-server and I don't know why. Do you think I should to ask this in the Pihole github/reddit?

**Comment by Fourdee** [comment]
@enolp 

> Doing a search on the internet to see how can I solve my issue, I found this article: https://frillip.com/using-your-raspberry-pi-3-as-a-wifi-access-point-with-hostapd/ which uses dnsmasq (instead of ics-dhcp-server) like pihole.

This is near exact same as the DietPi-Software: WiFi Hotspot installer.

> Do you think I should to ask this in the Pihole github/reddit?

https://www.reddit.com/r/pihole/comments/4fdcb2/turn_raspberry_pi_into_a_adblocking_wifi_router/

**Comment by k-plan** [comment]
@enolp

> I don't know what I did before but now nothing works...... 

Better to start now from the scratch.


> I would like someone help me with this because having installed dnsmasq, dietpi installs ics-dhcp-server and I don't know why.

- write a new DiePi image on a sd card

- go through first installation process

- set up via `dietpi-config` eht0 interface with a static ip address, e.g 192.168.0.100, with correct default gateway and a valid dns server 

- enable Onboard WiFi in  `dietpi-config`

- `reboot` your RPi3

- install via ` dietpi-software` WiFi Hotspot

- edit `nano /etc/dhcp/dhcpd.conf` and change `option domain-name-servers`
```
ddns-update-style none;
default-lease-time 600;
max-lease-time 7200;
authoritative;
log-facility local7;

subnet 192.168.42.0 netmask 255.255.255.0 {
        range 192.168.42.10 192.168.42.50;
        option broadcast-address 192.168.42.255;
        option routers 192.168.42.1;
        option domain-name "local";
        option domain-name-servers 192.168.42.1, 192.168.0.100;
}

```

- `reboot` your RPi3

- take a look in `dietpi-config` if  WiFi Hotspot is running. You can as well change SSID, channel, Country Code, secret here.
![170605-0001](https://cloud.githubusercontent.com/assets/17237601/26782000/abdfe1aa-49f1-11e7-9c67-841a69fc5998.gif)
![170605-0002](https://cloud.githubusercontent.com/assets/17237601/26782012/b6c51144-49f1-11e7-8645-775f61baf18a.gif)

- If WiFi Hotspot is up and running, install `Pi-hole` via  `dietpi-software`. Make sure  what `Webserver Preference  ` is set to ` Lighttpd` before your start ` Install`

- In `Pi-hole` install assistant, choose running interface `eth0`  - not `wlan0` !!

- After finish installation and auto reboot your device, type in terminal: `pihole -a -i all`
Or you can do this via pihole web-interface, e.g.: `192.168.0.100/pihole` => `Login` => `Settings` => `Advanced DNS settings` and choose: `Listen on all interfaces`
![170605-0003](https://cloud.githubusercontent.com/assets/17237601/26782502/3faba3ae-49f4-11e7-81c4-102e40a435a7.gif)

- Imported: And don't activated `Pi-hole DHCP Server`!

- Now you can watch in PiHole `Dashboard` web-interface your connected Wifi HotSpot clients  (IP: 192.168.42.10 - 192.168.42.50) filtered DNS Queries.

It's tested and running here.

----------------------

`ics-dhcp-server` will run for Wifi HotSpot on `wlan0`
![170605-0004](https://cloud.githubusercontent.com/assets/17237601/26782831/a813fcce-49f5-11e7-9679-8e695e496f86.gif)


`dnsmasq` is running on `eth0` as DNS Server AND DNS Client at the same time, to get DNS resolution and to feed DNS Queries.
So PiHole `dnsmasq` DHCP Server will as well run on eth0 ... not on wlan0 !


```
DietPi-Services
──────────────────────────────────────
 Mode: restart
 Please wait...

 [Ok] cron
 [Ok] lighttpd
 [Ok] php5-fpm
 [Ok] dnsmasq
 [Ok] pihole-FTL
 [Ok] isc-dhcp-server
 [Ok] hostapd

```

**BTW:**
Editing `/etc/dnsmasq.conf` can/will be a problem, because pihole will start `/usr/sbin/dnsmasq ` with it's own parameter settings. Have a look in `/etc/pihole/setupVars.conf`


```
PIHOLE_INTERFACE=eth0
IPV4_ADDRESS=192.168.0.100/24
QUERY_LOGGING=true
INSTALL_WEB=true
WEBPASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
PIHOLE_DNS_1=192.168.0.1
PIHOLE_DNS_2=8.8.8.8
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
DNSSEC=false
DNSMASQ_LISTENING=all
```

**Comment by Fourdee** [comment]
Marking as closed, please reopen if required.

**Comment by enolp** [comment]
I almost forgot about this issue but finally I could do some tests.

@k-plan 

Doing that now my ethernet devices can't get an local IP address but my wireless devices get internet access just fine.

I wonder if I have to edit the /etc/dnsmasq.conf file
